import type { AssessmentQuestionSeed } from "../types.js";

// Source: 3_career_assessment_questionnaire.html — 73 questions, 4 sections, cohort
// "CLASS_9_10". PWC's proprietary scoring/weighting logic for trait aggregation and
// career-stream mapping is not yet supplied — only the per-question weight and (for
// aptitude) difficulty tags present in the source form are captured here.
//
// IMPORTANT: aptitude (APTITUDE section) questions have no `correctOption` seeded.
// The source form does not mark correct answers, and guessing them would silently
// bake a wrong answer key into real student scoring — PWC must supply/confirm the
// official answer key before these can be auto-graded.

interface LikertItem {
  code: string;
  fieldKey: string;
  trait: string;
  traitCode: string;
  text: string;
}

function likertQuestions(
  section: AssessmentQuestionSeed["section"],
  items: LikertItem[],
  startOrder: number
): AssessmentQuestionSeed[] {
  return items.map((item, i) => ({
    section,
    order: startOrder + i,
    questionCode: item.code,
    fieldKey: item.fieldKey,
    questionText: item.text,
    format: "LIKERT_5",
    trait: item.trait,
    traitCode: item.traitCode,
  }));
}

const riasecItems: LikertItem[] = [
  {
    code: "Q1",
    fieldKey: "riasec_realistic_r1",
    trait: "REALISTIC",
    traitCode: "R1",
    text: "I enjoy building or fixing things with my hands — like putting together models (Lego, Rubik's cube, etc.) or playing with gadgets, or figuring out how everyday objects work.",
  },
  {
    code: "Q2",
    fieldKey: "riasec_realistic_r2",
    trait: "REALISTIC",
    traitCode: "R2",
    text: "I prefer working outdoors or in hands-on environments or practicals, rather than spending most of my time at a desk or in a classroom.",
  },
  {
    code: "Q3",
    fieldKey: "riasec_realistic_r3",
    trait: "REALISTIC",
    traitCode: "R3",
    text: "I enjoy working with tools, devices, or mechanical things — understanding how they work and what makes them function excites me rather than reading about them in books.",
  },
  {
    code: "Q4",
    fieldKey: "riasec_realistic_r4",
    trait: "REALISTIC",
    traitCode: "R4",
    text: "I find working with physical objects and tools (practical work) more satisfying than working with people or ideas (theoretical work).",
  },
  {
    code: "Q5",
    fieldKey: "riasec_investigative_i1",
    trait: "INVESTIGATIVE",
    traitCode: "I1",
    text: 'I love asking "why" and trying to understand the science or logic behind things I observe.',
  },
  {
    code: "Q6",
    fieldKey: "riasec_investigative_i2",
    trait: "INVESTIGATIVE",
    traitCode: "I2",
    text: "I enjoy solving problems that require careful analysis and logical thinking.",
  },
  {
    code: "Q7",
    fieldKey: "riasec_investigative_i3",
    trait: "INVESTIGATIVE",
    traitCode: "I3",
    text: "I like reading about scientific discoveries, experiments, or research findings.",
  },
  {
    code: "Q8",
    fieldKey: "riasec_investigative_i4",
    trait: "INVESTIGATIVE",
    traitCode: "I4",
    text: "I prefer finding answers through research and data, rather than through imagination or gut feeling.",
  },
  {
    code: "Q9",
    fieldKey: "riasec_artistic_a1",
    trait: "ARTISTIC",
    traitCode: "A1",
    text: "I enjoy creating things by drawing, writing, music, photography, or designing something original or new.",
  },
  {
    code: "Q10",
    fieldKey: "riasec_artistic_a2",
    trait: "ARTISTIC",
    traitCode: "A2",
    text: "I often express my feelings or ideas through art, stories, or creative projects.",
  },
  {
    code: "Q11",
    fieldKey: "riasec_artistic_a3",
    trait: "ARTISTIC",
    traitCode: "A3",
    text: "I feel attracted to careers that let me be creative — like film making, graphic design, photography, or writing.",
  },
  {
    code: "Q12",
    fieldKey: "riasec_artistic_a4",
    trait: "ARTISTIC",
    traitCode: "A4",
    text: "I enjoy work that has no fixed rules — where I can experiment and find my own way of doing things.",
  },
  {
    code: "Q13",
    fieldKey: "riasec_social_s1",
    trait: "SOCIAL",
    traitCode: "S1",
    text: "I enjoy helping friends or classmates when they are struggling with personal or academic problems.",
  },
  {
    code: "Q14",
    fieldKey: "riasec_social_s2",
    trait: "SOCIAL",
    traitCode: "S2",
    text: "I find it rewarding to teach, counsel or guide others, even in informal settings / occasions.",
  },
  {
    code: "Q15",
    fieldKey: "riasec_social_s3",
    trait: "SOCIAL",
    traitCode: "S3",
    text: "I care about making a positive difference in people's lives or in my community and would want to do something.",
  },
  {
    code: "Q16",
    fieldKey: "riasec_social_s4",
    trait: "SOCIAL",
    traitCode: "S4",
    text: "I prefer careers that involve working with and understanding people, over careers that involve machines or physical objects.",
  },
  {
    code: "Q17",
    fieldKey: "riasec_enterprising_e1",
    trait: "ENTERPRISING",
    traitCode: "E1",
    text: "I enjoy taking charge of situations — leading a group project, organizing events, or coming up with plans.",
  },
  {
    code: "Q18",
    fieldKey: "riasec_enterprising_e2",
    trait: "ENTERPRISING",
    traitCode: "E2",
    text: "I like persuading or convincing people — whether it's pitching an idea, winning a debate, or getting others to see my point of view.",
  },
  {
    code: "Q19",
    fieldKey: "riasec_enterprising_e3",
    trait: "ENTERPRISING",
    traitCode: "E3",
    text: "I get excited thinking about starting my own project, club, or venture — or creating something completely from scratch in a new way.",
  },
  {
    code: "Q20",
    fieldKey: "riasec_enterprising_e4",
    trait: "ENTERPRISING",
    traitCode: "E4",
    text: "I often rely on instinct and ideas, rather than detailed research or rules when making decisions.",
  },
  {
    code: "Q21",
    fieldKey: "riasec_conventional_c1",
    trait: "CONVENTIONAL",
    traitCode: "C1",
    text: "I like organising data, maintaining records, and following systematic procedures. It gives me satisfaction.",
  },
  {
    code: "Q22",
    fieldKey: "riasec_conventional_c2",
    trait: "CONVENTIONAL",
    traitCode: "C2",
    text: "I prefer following clear procedures and guidelines, rather than doing things as I go.",
  },
  {
    code: "Q23",
    fieldKey: "riasec_conventional_c3",
    trait: "CONVENTIONAL",
    traitCode: "C3",
    text: "I feel comfortable in systematic or organised environments, where my responsibilities and tasks are clearly defined.",
  },
  {
    code: "Q24",
    fieldKey: "riasec_conventional_c4",
    trait: "CONVENTIONAL",
    traitCode: "C4",
    text: "I prefer following established rules and standard methods, over experimenting with new or unconventional approaches.",
  },
];

const bigFiveItems: LikertItem[] = [
  {
    code: "Q25",
    fieldKey: "bigfive_openness_o1",
    trait: "OPENNESS",
    traitCode: "O1",
    text: "I enjoy exploring new ideas, topics or areas of knowledge even when they are not related to my studies.",
  },
  {
    code: "Q26",
    fieldKey: "bigfive_openness_o2",
    trait: "OPENNESS",
    traitCode: "O2",
    text: "I find myself curious about cultures, philosophies or ways of thinking that are very different from my own.",
  },
  {
    code: "Q27",
    fieldKey: "bigfive_openness_o3",
    trait: "OPENNESS",
    traitCode: "O3",
    text: "I enjoy trying new and different experiences — I would rather explore the unknown than stick to familiar routines.",
  },
  {
    code: "Q28",
    fieldKey: "bigfive_openness_o4",
    trait: "OPENNESS",
    traitCode: "O4",
    text: "I prefer sticking to topics and activities I already know well rather than venturing into unfamiliar territory.",
  },
  {
    code: "Q29",
    fieldKey: "bigfive_conscientiousness_c1",
    trait: "CONSCIENTIOUSNESS",
    traitCode: "C1",
    text: "I plan my work ahead of time and continue to do my tasks as I planned, even when they get tedious or difficult.",
  },
  {
    code: "Q30",
    fieldKey: "bigfive_conscientiousness_c2",
    trait: "CONSCIENTIOUSNESS",
    traitCode: "C2",
    text: "I pay close attention to detail and dislike submitting work that is incomplete or sloppy.",
  },
  {
    code: "Q31",
    fieldKey: "bigfive_conscientiousness_c3",
    trait: "CONSCIENTIOUSNESS",
    traitCode: "C3",
    text: "I set goals for myself and work systematically towards achieving them, even without being told to.",
  },
  {
    code: "Q32",
    fieldKey: "bigfive_conscientiousness_c4",
    trait: "CONSCIENTIOUSNESS",
    traitCode: "C4",
    text: "I often leave tasks till the last minute and find it hard to stick to a schedule or plan.",
  },
  {
    code: "Q33",
    fieldKey: "bigfive_extraversion_e1",
    trait: "EXTRAVERSION",
    traitCode: "E1",
    text: "I feel energized and comfortable in social settings like parties — I enjoy meeting new people and striking up conversations.",
  },
  {
    code: "Q34",
    fieldKey: "bigfive_extraversion_e2",
    trait: "EXTRAVERSION",
    traitCode: "E2",
    text: "I feel comfortable speaking up, sharing my views, or taking a visible role in group activities or class discussions.",
  },
  {
    code: "Q35",
    fieldKey: "bigfive_extraversion_e3",
    trait: "EXTRAVERSION",
    traitCode: "E3",
    text: "After spending time in a group of people, I feel refreshed and ready for more social interaction.",
  },
  {
    code: "Q36",
    fieldKey: "bigfive_extraversion_e4",
    trait: "EXTRAVERSION",
    traitCode: "E4",
    text: "I find social gatherings like annual day, sports day, birthday party, religious festivals, group outing, etc draining and often prefer to spend time alone or with just one or two people.",
  },
  {
    code: "Q37",
    fieldKey: "bigfive_agreeableness_ag1",
    trait: "AGREEABLENESS",
    traitCode: "AG1",
    text: "I naturally consider how my actions might affect others before making a decision.",
  },
  {
    code: "Q38",
    fieldKey: "bigfive_agreeableness_ag2",
    trait: "AGREEABLENESS",
    traitCode: "AG2",
    text: "After a disagreement or argument, I find it fairly easy to let go and move on without thinking on it for long — I don't like holding grudges.",
  },
  {
    code: "Q39",
    fieldKey: "bigfive_agreeableness_ag3",
    trait: "AGREEABLENESS",
    traitCode: "AG3",
    text: "I genuinely enjoy cooperating and collaborating with others, even when it means adjusting my own ideas.",
  },
  {
    code: "Q40",
    fieldKey: "bigfive_agreeableness_ag4",
    trait: "AGREEABLENESS",
    traitCode: "AG4",
    text: "I tend to argue my point stubbornly during disagreements, and find it hard to see the other person's perspective.",
  },
  {
    code: "Q41",
    fieldKey: "bigfive_emotional_stability_es1",
    trait: "EMOTIONAL_STABILITY",
    traitCode: "ES1",
    text: "I remain cool and composed in stressful situations, like exams or conflicts, without panicking.",
  },
  {
    code: "Q42",
    fieldKey: "bigfive_emotional_stability_es2",
    trait: "EMOTIONAL_STABILITY",
    traitCode: "ES2",
    text: "I recover quickly after setbacks, failures or disappointments, and get back to normal fairly fast.",
  },
  {
    code: "Q43",
    fieldKey: "bigfive_emotional_stability_es3",
    trait: "EMOTIONAL_STABILITY",
    traitCode: "ES3",
    text: "When I face uncertainty or high-pressure situations like exams or tough decisions, I tend to worry a lot and find it hard to stay calm.",
  },
  {
    code: "Q44",
    fieldKey: "bigfive_emotional_stability_es4",
    trait: "EMOTIONAL_STABILITY",
    traitCode: "ES4",
    text: "I feel most comfortable and productive when I follow familiar routines and predictable schedules.",
  },
];

const cognitiveItems: LikertItem[] = [
  {
    code: "Q65",
    fieldKey: "cognitive_learning_velocity_lv1",
    trait: "LEARNING_VELOCITY",
    traitCode: "LV1",
    text: "When I encounter a new subject or skill, I pick it up quickly and enjoy the challenge of learning something unfamiliar.",
  },
  {
    code: "Q66",
    fieldKey: "cognitive_learning_velocity_lv2",
    trait: "LEARNING_VELOCITY",
    traitCode: "LV2",
    text: "I actively seek feedback on my work and use it to improve quickly, even if the feedback is critical or not appealing.",
  },
  {
    code: "Q67",
    fieldKey: "cognitive_learning_velocity_lv3",
    trait: "LEARNING_VELOCITY",
    traitCode: "LV3",
    text: "I find it hard to adjust when my teachers change their teaching style, or when I have to switch to a completely new way of studying or doing things.",
  },
  {
    code: "Q68",
    fieldKey: "cognitive_uncertainty_tolerance_ut1",
    trait: "UNCERTAINTY_TOLERANCE",
    traitCode: "UT1",
    text: "I am comfortable starting a project or task even when I am not sure how it will turn out — not knowing the outcome excites rather than worries me.",
  },
  {
    code: "Q69",
    fieldKey: "cognitive_uncertainty_tolerance_ut2",
    trait: "UNCERTAINTY_TOLERANCE",
    traitCode: "UT2",
    text: "When I have to make a difficult decision and don't have all the answers, I can still make up my mind and move forward rather than waiting endlessly.",
  },
  {
    code: "Q70",
    fieldKey: "cognitive_uncertainty_tolerance_ut3",
    trait: "UNCERTAINTY_TOLERANCE",
    traitCode: "UT3",
    text: "When there is no clear plan or I cannot predict what will happen next, I feel very unsettled and find it difficult to take any action.",
  },
  {
    code: "Q71",
    fieldKey: "cognitive_autonomy_preference_ap1",
    trait: "AUTONOMY_PREFERENCE",
    traitCode: "AP1",
    text: "I prefer working independently on projects, where I decide how to approach the task, rather than following someone else's instructions step by step.",
  },
  {
    code: "Q72",
    fieldKey: "cognitive_autonomy_preference_ap2",
    trait: "AUTONOMY_PREFERENCE",
    traitCode: "AP2",
    text: "When something goes wrong in my work or project, I prefer to think it through and fix it on my own rather than immediately asking a teacher or friend for help.",
  },
  {
    code: "Q73",
    fieldKey: "cognitive_autonomy_preference_ap3",
    trait: "AUTONOMY_PREFERENCE",
    traitCode: "AP3",
    text: "I feel more confident and produce better results when someone gives me detailed guidance and checks on my progress regularly, rather than leaving me to work alone.",
  },
];

const APTITUDE_OPTION_SUFFIX = { value: "E", label: "E. Not sure" };

const aptitudeItems: AssessmentQuestionSeed[] = [
  {
    section: "APTITUDE",
    order: 45,
    questionCode: "Q45",
    fieldKey: "aptitude_numerical_nr1",
    trait: "NUMERICAL",
    traitCode: "NR1",
    difficulty: "EASY",
    weight: 1,
    format: "MCQ_SINGLE",
    questionText: "A shopkeeper sells a pen for ₹30, making a profit of 20%. What is the cost price of the pen?",
    options: [
      { value: "A", label: "A. ₹22" },
      { value: "B", label: "B. ₹25" },
      { value: "C", label: "C. ₹24" },
      { value: "D", label: "D. ₹28" },
      APTITUDE_OPTION_SUFFIX,
    ],
  },
  {
    section: "APTITUDE",
    order: 46,
    questionCode: "Q46",
    fieldKey: "aptitude_numerical_nr2",
    trait: "NUMERICAL",
    traitCode: "NR2",
    difficulty: "EASY",
    weight: 1,
    format: "MCQ_SINGLE",
    questionText: "If 3x + 7 = 22, what is the value of x?",
    options: [
      { value: "A", label: "A. 5" },
      { value: "B", label: "B. 7" },
      { value: "C", label: "C. 3" },
      { value: "D", label: "D. 9" },
      APTITUDE_OPTION_SUFFIX,
    ],
  },
  {
    section: "APTITUDE",
    order: 47,
    questionCode: "Q47",
    fieldKey: "aptitude_numerical_nr3",
    trait: "NUMERICAL",
    traitCode: "NR3",
    difficulty: "MEDIUM",
    weight: 1.5,
    format: "MCQ_SINGLE",
    questionText:
      "A train travels 240 km in 3 hours, then 180 km in 2 hours. What is the average speed for the entire journey?",
    options: [
      { value: "A", label: "A. 80 km/h" },
      { value: "B", label: "B. 84 km/h" },
      { value: "C", label: "C. 90 km/h" },
      { value: "D", label: "D. 78 km/h" },
      APTITUDE_OPTION_SUFFIX,
    ],
  },
  {
    section: "APTITUDE",
    order: 48,
    questionCode: "Q48",
    fieldKey: "aptitude_numerical_nr4",
    trait: "NUMERICAL",
    traitCode: "NR4",
    difficulty: "MEDIUM",
    weight: 1.5,
    format: "MCQ_SINGLE",
    questionText:
      "A product is first discounted by 25% and then the discounted price is further reduced by 10%. If the original price is ₹800, what is the final price?",
    options: [
      { value: "A", label: "A. ₹520" },
      { value: "B", label: "B. ₹540" },
      { value: "C", label: "C. ₹560" },
      { value: "D", label: "D. ₹500" },
      APTITUDE_OPTION_SUFFIX,
    ],
  },
  {
    section: "APTITUDE",
    order: 49,
    questionCode: "Q49",
    fieldKey: "aptitude_numerical_nr5",
    trait: "NUMERICAL",
    traitCode: "NR5",
    difficulty: "HARD",
    weight: 2,
    format: "MCQ_SINGLE",
    questionText:
      "Riya invests ₹12,000 at 10% compound interest per year for 2 years, while Meera invests the same amount at 11% simple interest for 2 years. How much more does Meera earn than Riya?",
    options: [
      { value: "A", label: "A. ₹24" },
      { value: "B", label: "B. ₹120" },
      { value: "C", label: "C. ₹240" },
      { value: "D", label: "D. ₹144" },
      APTITUDE_OPTION_SUFFIX,
    ],
  },
  {
    section: "APTITUDE",
    order: 50,
    questionCode: "Q50",
    fieldKey: "aptitude_verbal_vr1",
    trait: "VERBAL",
    traitCode: "VR1",
    difficulty: "EASY",
    weight: 1,
    format: "MCQ_SINGLE",
    questionText: "Choose the word most opposite in meaning to: FRUGAL",
    options: [
      { value: "A", label: "A. Careful" },
      { value: "B", label: "B. Economical" },
      { value: "C", label: "C. Extravagant" },
      { value: "D", label: "D. Thrifty" },
      APTITUDE_OPTION_SUFFIX,
    ],
  },
  {
    section: "APTITUDE",
    order: 51,
    questionCode: "Q51",
    fieldKey: "aptitude_verbal_vr2",
    trait: "VERBAL",
    traitCode: "VR2",
    difficulty: "EASY",
    weight: 1,
    format: "MCQ_SINGLE",
    questionText: "Complete the analogy: Stethoscope : Doctor :: Blackboard : ___",
    options: [
      { value: "A", label: "A. Carpenter" },
      { value: "B", label: "B. Teacher" },
      { value: "C", label: "C. Lawyer" },
      { value: "D", label: "D. Judge" },
      APTITUDE_OPTION_SUFFIX,
    ],
  },
  {
    section: "APTITUDE",
    order: 52,
    questionCode: "Q52",
    fieldKey: "aptitude_verbal_vr3",
    trait: "VERBAL",
    traitCode: "VR3",
    difficulty: "MEDIUM",
    weight: 1.5,
    format: "MCQ_SINGLE",
    questionText:
      'Read: "Despite the heavy rainfall, the farmers were relieved because the crops badly needed water." Which conclusion is most accurate?',
    options: [
      { value: "A", label: "A. The farmers were unhappy about the rain." },
      { value: "B", label: "B. The rain was beneficial despite being heavy." },
      { value: "C", label: "C. The crops were damaged by the rain." },
      { value: "D", label: "D. The farmers had predicted the rainfall." },
      APTITUDE_OPTION_SUFFIX,
    ],
  },
  {
    section: "APTITUDE",
    order: 53,
    questionCode: "Q53",
    fieldKey: "aptitude_verbal_vr4",
    trait: "VERBAL",
    traitCode: "VR4",
    difficulty: "MEDIUM",
    weight: 1.5,
    format: "MCQ_SINGLE",
    questionText: 'Read: "All scientists are curious. Priya is curious. Therefore, Priya is a scientist." This argument is:',
    options: [
      { value: "A", label: "A. Invalid — being curious doesn't prove Priya is a scientist." },
      { value: "B", label: "B. Valid — the conclusion logically follows." },
      { value: "C", label: "C. Valid — Priya must be a scientist if she is curious." },
      { value: "D", label: "D. Invalid — scientists cannot be curious." },
      APTITUDE_OPTION_SUFFIX,
    ],
  },
  {
    section: "APTITUDE",
    order: 54,
    questionCode: "Q54",
    fieldKey: "aptitude_verbal_vr5",
    trait: "VERBAL",
    traitCode: "VR5",
    difficulty: "HARD",
    weight: 2,
    format: "MCQ_SINGLE",
    questionText:
      'Read the passage: "The city\'s water supply depends on a reservoir that is fed by two rivers. River A contributes 60% of the water in the wet season but only 30% in the dry season. River B contributes the rest. The city has been experiencing an unusually dry year." Which statement is most logically supported?',
    options: [
      { value: "A", label: "A. River B is currently the dominant source of water for the city." },
      { value: "B", label: "B. River A always provides more water than River B." },
      { value: "C", label: "C. The reservoir is empty this year." },
      { value: "D", label: "D. River B contributes 40% in the wet season." },
      APTITUDE_OPTION_SUFFIX,
    ],
  },
  {
    section: "APTITUDE",
    order: 55,
    questionCode: "Q55",
    fieldKey: "aptitude_logical_lr1",
    trait: "LOGICAL",
    traitCode: "LR1",
    difficulty: "EASY",
    weight: 1,
    format: "MCQ_SINGLE",
    questionText: "What comes next in the sequence: 3, 6, 12, 24, ___?",
    options: [
      { value: "A", label: "A. 36" },
      { value: "B", label: "B. 48" },
      { value: "C", label: "C. 42" },
      { value: "D", label: "D. 32" },
      APTITUDE_OPTION_SUFFIX,
    ],
  },
  {
    section: "APTITUDE",
    order: 56,
    questionCode: "Q56",
    fieldKey: "aptitude_logical_lr2",
    trait: "LOGICAL",
    traitCode: "LR2",
    difficulty: "EASY",
    weight: 1,
    format: "MCQ_SINGLE",
    questionText: "If all Apples are Fruits, and some Fruits are Red, which of the following must be true?",
    options: [
      { value: "A", label: "A. All Apples are Red." },
      { value: "B", label: "B. All Apples are Fruits." },
      { value: "C", label: "C. Some Apples are Red." },
      { value: "D", label: "D. No Red things are Apples." },
      APTITUDE_OPTION_SUFFIX,
    ],
  },
  {
    section: "APTITUDE",
    order: 57,
    questionCode: "Q57",
    fieldKey: "aptitude_logical_lr3",
    trait: "LOGICAL",
    traitCode: "LR3",
    difficulty: "MEDIUM",
    weight: 1.5,
    format: "MCQ_SINGLE",
    questionText:
      "Five students — Arjun, Bhavi, Chetan, Divya, and Esha — are seated in a row. Chetan sits to the left of Arjun. Arjun sits to the left of Bhavi. Esha sits between Arjun and Bhavi. Bhavi sits to the left of Divya. Who sits in the middle?",
    options: [
      { value: "A", label: "A. Arjun" },
      { value: "B", label: "B. Bhavi" },
      { value: "C", label: "C. Esha" },
      { value: "D", label: "D. Chetan" },
      APTITUDE_OPTION_SUFFIX,
    ],
  },
  {
    section: "APTITUDE",
    order: 58,
    questionCode: "Q58",
    fieldKey: "aptitude_logical_lr4",
    trait: "LOGICAL",
    traitCode: "LR4",
    difficulty: "MEDIUM",
    weight: 1.5,
    format: "MCQ_SINGLE",
    questionText:
      "A pattern alternates between a filled shape and an empty shape of the same type, rotating 90° clockwise each step. The sequence so far is: Filled Circle → Empty Square → Filled Triangle → Empty Circle. What comes next?",
    options: [
      { value: "A", label: "A. Filled Square" },
      { value: "B", label: "B. Empty Triangle" },
      { value: "C", label: "C. Filled Circle" },
      { value: "D", label: "D. Empty Square" },
      APTITUDE_OPTION_SUFFIX,
    ],
  },
  {
    section: "APTITUDE",
    order: 59,
    questionCode: "Q59",
    fieldKey: "aptitude_logical_lr5",
    trait: "LOGICAL",
    traitCode: "LR5",
    difficulty: "HARD",
    weight: 2,
    format: "MCQ_SINGLE",
    questionText: "In a coding language: DOG = 26, CAT = 24, BAT = 23. Following the same logic, what does FISH equal?",
    options: [
      { value: "A", label: "A. 38" },
      { value: "B", label: "B. 42" },
      { value: "C", label: "C. 40" },
      { value: "D", label: "D. 34" },
      APTITUDE_OPTION_SUFFIX,
    ],
  },
  {
    section: "APTITUDE",
    order: 60,
    questionCode: "Q60",
    fieldKey: "aptitude_spatial_sr1",
    trait: "SPATIAL",
    traitCode: "SR1",
    difficulty: "EASY",
    weight: 1,
    format: "MCQ_SINGLE",
    questionText:
      "A square piece of paper is folded in half horizontally (top over bottom), then folded again in half vertically (left over right). A hole is punched in the top-right corner of the folded piece. How many holes appear when the paper is fully unfolded?",
    options: [
      { value: "A", label: "A. 1" },
      { value: "B", label: "B. 4" },
      { value: "C", label: "C. 2" },
      { value: "D", label: "D. 8" },
      APTITUDE_OPTION_SUFFIX,
    ],
  },
  {
    section: "APTITUDE",
    order: 61,
    questionCode: "Q61",
    fieldKey: "aptitude_spatial_sr2",
    trait: "SPATIAL",
    traitCode: "SR2",
    difficulty: "EASY",
    weight: 1,
    format: "MCQ_SINGLE",
    questionText: "If you look in a mirror, what time does the mirror image show for a clock whose time is 3:00?",
    options: [
      { value: "A", label: "A. 3:00" },
      { value: "B", label: "B. 9:00" },
      { value: "C", label: "C. 6:00" },
      { value: "D", label: "D. 12:00" },
      APTITUDE_OPTION_SUFFIX,
    ],
  },
  {
    section: "APTITUDE",
    order: 62,
    questionCode: "Q62",
    fieldKey: "aptitude_spatial_sr3",
    trait: "SPATIAL",
    traitCode: "SR3",
    difficulty: "MEDIUM",
    weight: 1.5,
    format: "MCQ_SINGLE",
    questionText:
      "A 3×3×3 cube is painted red on all 6 faces and then cut into 27 equal smaller cubes. How many of the smaller cubes have exactly 2 faces painted red?",
    options: [
      { value: "A", label: "A. 8" },
      { value: "B", label: "B. 12" },
      { value: "C", label: "C. 6" },
      { value: "D", label: "D. 4" },
      APTITUDE_OPTION_SUFFIX,
    ],
  },
  {
    section: "APTITUDE",
    order: 63,
    questionCode: "Q63",
    fieldKey: "aptitude_spatial_sr4",
    trait: "SPATIAL",
    traitCode: "SR4",
    difficulty: "MEDIUM",
    weight: 1.5,
    format: "MCQ_SINGLE",
    questionText:
      "A shape is made up of 6 equal squares joined edge-to-edge (a net of a cube). When folded into a cube, which face is opposite the base? Net layout: a cross/plus shape with a TOP square directly above the BASE square.",
    options: [
      { value: "A", label: "A. The left most square" },
      { value: "B", label: "B. The square directly above the base in the net" },
      { value: "C", label: "C. The right most square" },
      { value: "D", label: "D. Cannot be determined" },
      APTITUDE_OPTION_SUFFIX,
    ],
  },
  {
    section: "APTITUDE",
    order: 64,
    questionCode: "Q64",
    fieldKey: "aptitude_spatial_sr5",
    trait: "SPATIAL",
    traitCode: "SR5",
    difficulty: "HARD",
    weight: 2,
    format: "MCQ_SINGLE",
    questionText:
      "Imagine you are standing inside a hollow cube, looking at the wall directly in front of you. If you rotate 90° to your right and then tilt your head 90° upward, which original face of the cube are you now looking at?",
    options: [
      { value: "A", label: "A. The left face" },
      { value: "B", label: "B. The bottom face" },
      { value: "C", label: "C. The top face" },
      { value: "D", label: "D. The right face" },
      APTITUDE_OPTION_SUFFIX,
    ],
  },
];

export const class9to10AssessmentQuestions: AssessmentQuestionSeed[] = [
  ...likertQuestions("RIASEC", riasecItems, 1),
  ...likertQuestions("BIG_FIVE", bigFiveItems, 25),
  ...aptitudeItems,
  ...likertQuestions("COGNITIVE", cognitiveItems, 65),
];
