// AUTO-GENERATED by scripts/export-assessment-scoring.py — do not edit by hand.
// Source: docs/Class 910_Traits  Weightages (1).xlsx

import type { BigFive20Entry } from "./types.js";

export const bigFive20: BigFive20Entry[] = [
  {
    "code": "O-C",
    "style": "Innovative Planner",
    "description": "Primary personality tendency in Openness: consistently shows creativity, curiosity, and openness to new ideas, perspectives, and experiences. This is complemented by a secondary Conscientiousness tendency toward discipline, responsibility, and a goal-directed, organized approach to tasks. Together, this style suggests a young person who leads with explorer-like tendencies day-to-day, while also drawing on planner-like tendencies as a supporting behavioural pattern, which is useful for counsellors to note when framing stream and activity recommendations.",
    "explanation": "You naturally tend to explore new ideas, ask questions, and welcome different perspectives, and this is supported by a tendency to stay organized, follow through on responsibilities, and work in a disciplined way. This combination of curiosity and openness to new ideas, together with discipline and reliability, is likely to help you approach challenges with fresh thinking and creativity."
  },
  {
    "code": "O-E",
    "style": "Inspired Communicator",
    "description": "Primary personality tendency in Openness: consistently shows creativity, curiosity, and openness to new ideas, perspectives, and experiences. This is complemented by a secondary Extraversion tendency toward social energy, communication, and active engagement with people and surroundings. Together, this style suggests a young person who leads with explorer-like tendencies day-to-day, while also drawing on communicator-like tendencies as a supporting behavioural pattern, which is useful for counsellors to note when framing stream and activity recommendations.",
    "explanation": "You naturally tend to explore new ideas, ask questions, and welcome different perspectives, and this is supported by a tendency to engage actively with people, share your energy, and enjoy social situations. This combination of curiosity and openness to new ideas, together with social energy and communication, is likely to help you approach challenges with fresh thinking and creativity."
  },
  {
    "code": "O-A",
    "style": "Creative Collaborator",
    "description": "Primary personality tendency in Openness: consistently shows creativity, curiosity, and openness to new ideas, perspectives, and experiences. This is complemented by a secondary Agreeableness tendency toward empathy, cooperation, and consideration for the feelings and needs of others. Together, this style suggests a young person who leads with explorer-like tendencies day-to-day, while also drawing on collaborator-like tendencies as a supporting behavioural pattern, which is useful for counsellors to note when framing stream and activity recommendations.",
    "explanation": "You naturally tend to explore new ideas, ask questions, and welcome different perspectives, and this is supported by a tendency to consider others' feelings, cooperate, and build harmonious relationships. This combination of curiosity and openness to new ideas, together with empathy and cooperation, is likely to help you approach challenges with fresh thinking and creativity."
  },
  {
    "code": "O-S",
    "style": "Resilient Visionary",
    "description": "Primary personality tendency in Openness: consistently shows creativity, curiosity, and openness to new ideas, perspectives, and experiences. This is complemented by a secondary Emotional Stability tendency toward calmness, resilience, and the ability to stay emotionally balanced under pressure. Together, this style suggests a young person who leads with explorer-like tendencies day-to-day, while also drawing on achiever-like tendencies as a supporting behavioural pattern, which is useful for counsellors to note when framing stream and activity recommendations.",
    "explanation": "You naturally tend to explore new ideas, ask questions, and welcome different perspectives, and this is supported by a tendency to stay calm and steady, even when things get stressful or uncertain. This combination of curiosity and openness to new ideas, together with calmness and emotional balance, is likely to help you approach challenges with fresh thinking and creativity."
  },
  {
    "code": "C-O",
    "style": "Disciplined Innovator",
    "description": "Primary personality tendency in Conscientiousness: consistently shows discipline, responsibility, and a goal-directed, organized approach to tasks. This is complemented by a secondary Openness tendency toward creativity, curiosity, and openness to new ideas, perspectives, and experiences. Together, this style suggests a young person who leads with planner-like tendencies day-to-day, while also drawing on explorer-like tendencies as a supporting behavioural pattern, which is useful for counsellors to note when framing stream and activity recommendations.",
    "explanation": "You naturally tend to stay organized, follow through on responsibilities, and work in a disciplined way, and this is supported by a tendency to explore new ideas, ask questions, and welcome different perspectives. This combination of discipline and reliability, together with curiosity and openness to new ideas, is likely to help you consistently follow through and meet expectations."
  },
  {
    "code": "C-E",
    "style": "Structured Communicator",
    "description": "Primary personality tendency in Conscientiousness: consistently shows discipline, responsibility, and a goal-directed, organized approach to tasks. This is complemented by a secondary Extraversion tendency toward social energy, communication, and active engagement with people and surroundings. Together, this style suggests a young person who leads with planner-like tendencies day-to-day, while also drawing on communicator-like tendencies as a supporting behavioural pattern, which is useful for counsellors to note when framing stream and activity recommendations.",
    "explanation": "You naturally tend to stay organized, follow through on responsibilities, and work in a disciplined way, and this is supported by a tendency to engage actively with people, share your energy, and enjoy social situations. This combination of discipline and reliability, together with social energy and communication, is likely to help you consistently follow through and meet expectations."
  },
  {
    "code": "C-A",
    "style": "Reliable Team Player",
    "description": "Primary personality tendency in Conscientiousness: consistently shows discipline, responsibility, and a goal-directed, organized approach to tasks. This is complemented by a secondary Agreeableness tendency toward empathy, cooperation, and consideration for the feelings and needs of others. Together, this style suggests a young person who leads with planner-like tendencies day-to-day, while also drawing on collaborator-like tendencies as a supporting behavioural pattern, which is useful for counsellors to note when framing stream and activity recommendations.",
    "explanation": "You naturally tend to stay organized, follow through on responsibilities, and work in a disciplined way, and this is supported by a tendency to consider others' feelings, cooperate, and build harmonious relationships. This combination of discipline and reliability, together with empathy and cooperation, is likely to help you consistently follow through and meet expectations."
  },
  {
    "code": "C-S",
    "style": "Steady Achiever",
    "description": "Primary personality tendency in Conscientiousness: consistently shows discipline, responsibility, and a goal-directed, organized approach to tasks. This is complemented by a secondary Emotional Stability tendency toward calmness, resilience, and the ability to stay emotionally balanced under pressure. Together, this style suggests a young person who leads with planner-like tendencies day-to-day, while also drawing on achiever-like tendencies as a supporting behavioural pattern, which is useful for counsellors to note when framing stream and activity recommendations.",
    "explanation": "You naturally tend to stay organized, follow through on responsibilities, and work in a disciplined way, and this is supported by a tendency to stay calm and steady, even when things get stressful or uncertain. This combination of discipline and reliability, together with calmness and emotional balance, is likely to help you consistently follow through and meet expectations."
  },
  {
    "code": "E-O",
    "style": "Dynamic Explorer",
    "description": "Primary personality tendency in Extraversion: consistently shows social energy, communication, and active engagement with people and surroundings. This is complemented by a secondary Openness tendency toward creativity, curiosity, and openness to new ideas, perspectives, and experiences. Together, this style suggests a young person who leads with communicator-like tendencies day-to-day, while also drawing on explorer-like tendencies as a supporting behavioural pattern, which is useful for counsellors to note when framing stream and activity recommendations.",
    "explanation": "You naturally tend to engage actively with people, share your energy, and enjoy social situations, and this is supported by a tendency to explore new ideas, ask questions, and welcome different perspectives. This combination of social energy and communication, together with curiosity and openness to new ideas, is likely to help you connect with and energize the people around you."
  },
  {
    "code": "E-C",
    "style": "Energetic Organizer",
    "description": "Primary personality tendency in Extraversion: consistently shows social energy, communication, and active engagement with people and surroundings. This is complemented by a secondary Conscientiousness tendency toward discipline, responsibility, and a goal-directed, organized approach to tasks. Together, this style suggests a young person who leads with communicator-like tendencies day-to-day, while also drawing on planner-like tendencies as a supporting behavioural pattern, which is useful for counsellors to note when framing stream and activity recommendations.",
    "explanation": "You naturally tend to engage actively with people, share your energy, and enjoy social situations, and this is supported by a tendency to stay organized, follow through on responsibilities, and work in a disciplined way. This combination of social energy and communication, together with discipline and reliability, is likely to help you connect with and energize the people around you."
  },
  {
    "code": "E-A",
    "style": "Sociable Connector",
    "description": "Primary personality tendency in Extraversion: consistently shows social energy, communication, and active engagement with people and surroundings. This is complemented by a secondary Agreeableness tendency toward empathy, cooperation, and consideration for the feelings and needs of others. Together, this style suggests a young person who leads with communicator-like tendencies day-to-day, while also drawing on collaborator-like tendencies as a supporting behavioural pattern, which is useful for counsellors to note when framing stream and activity recommendations.",
    "explanation": "You naturally tend to engage actively with people, share your energy, and enjoy social situations, and this is supported by a tendency to consider others' feelings, cooperate, and build harmonious relationships. This combination of social energy and communication, together with empathy and cooperation, is likely to help you connect with and energize the people around you."
  },
  {
    "code": "E-S",
    "style": "Confident Communicator",
    "description": "Primary personality tendency in Extraversion: consistently shows social energy, communication, and active engagement with people and surroundings. This is complemented by a secondary Emotional Stability tendency toward calmness, resilience, and the ability to stay emotionally balanced under pressure. Together, this style suggests a young person who leads with communicator-like tendencies day-to-day, while also drawing on achiever-like tendencies as a supporting behavioural pattern, which is useful for counsellors to note when framing stream and activity recommendations.",
    "explanation": "You naturally tend to engage actively with people, share your energy, and enjoy social situations, and this is supported by a tendency to stay calm and steady, even when things get stressful or uncertain. This combination of social energy and communication, together with calmness and emotional balance, is likely to help you connect with and energize the people around you."
  },
  {
    "code": "A-O",
    "style": "Empathic Idealist",
    "description": "Primary personality tendency in Agreeableness: consistently shows empathy, cooperation, and consideration for the feelings and needs of others. This is complemented by a secondary Openness tendency toward creativity, curiosity, and openness to new ideas, perspectives, and experiences. Together, this style suggests a young person who leads with collaborator-like tendencies day-to-day, while also drawing on explorer-like tendencies as a supporting behavioural pattern, which is useful for counsellors to note when framing stream and activity recommendations.",
    "explanation": "You naturally tend to consider others' feelings, cooperate, and build harmonious relationships, and this is supported by a tendency to explore new ideas, ask questions, and welcome different perspectives. This combination of empathy and cooperation, together with curiosity and openness to new ideas, is likely to help you build trust and work well within a team."
  },
  {
    "code": "A-C",
    "style": "Supportive Planner",
    "description": "Primary personality tendency in Agreeableness: consistently shows empathy, cooperation, and consideration for the feelings and needs of others. This is complemented by a secondary Conscientiousness tendency toward discipline, responsibility, and a goal-directed, organized approach to tasks. Together, this style suggests a young person who leads with collaborator-like tendencies day-to-day, while also drawing on planner-like tendencies as a supporting behavioural pattern, which is useful for counsellors to note when framing stream and activity recommendations.",
    "explanation": "You naturally tend to consider others' feelings, cooperate, and build harmonious relationships, and this is supported by a tendency to stay organized, follow through on responsibilities, and work in a disciplined way. This combination of empathy and cooperation, together with discipline and reliability, is likely to help you build trust and work well within a team."
  },
  {
    "code": "A-E",
    "style": "Warm Collaborator",
    "description": "Primary personality tendency in Agreeableness: consistently shows empathy, cooperation, and consideration for the feelings and needs of others. This is complemented by a secondary Extraversion tendency toward social energy, communication, and active engagement with people and surroundings. Together, this style suggests a young person who leads with collaborator-like tendencies day-to-day, while also drawing on communicator-like tendencies as a supporting behavioural pattern, which is useful for counsellors to note when framing stream and activity recommendations.",
    "explanation": "You naturally tend to consider others' feelings, cooperate, and build harmonious relationships, and this is supported by a tendency to engage actively with people, share your energy, and enjoy social situations. This combination of empathy and cooperation, together with social energy and communication, is likely to help you build trust and work well within a team."
  },
  {
    "code": "A-S",
    "style": "Calm Peacemaker",
    "description": "Primary personality tendency in Agreeableness: consistently shows empathy, cooperation, and consideration for the feelings and needs of others. This is complemented by a secondary Emotional Stability tendency toward calmness, resilience, and the ability to stay emotionally balanced under pressure. Together, this style suggests a young person who leads with collaborator-like tendencies day-to-day, while also drawing on achiever-like tendencies as a supporting behavioural pattern, which is useful for counsellors to note when framing stream and activity recommendations.",
    "explanation": "You naturally tend to consider others' feelings, cooperate, and build harmonious relationships, and this is supported by a tendency to stay calm and steady, even when things get stressful or uncertain. This combination of empathy and cooperation, together with calmness and emotional balance, is likely to help you build trust and work well within a team."
  },
  {
    "code": "S-O",
    "style": "Grounded Explorer",
    "description": "Primary personality tendency in Emotional Stability: consistently shows calmness, resilience, and the ability to stay emotionally balanced under pressure. This is complemented by a secondary Openness tendency toward creativity, curiosity, and openness to new ideas, perspectives, and experiences. Together, this style suggests a young person who leads with achiever-like tendencies day-to-day, while also drawing on explorer-like tendencies as a supporting behavioural pattern, which is useful for counsellors to note when framing stream and activity recommendations.",
    "explanation": "You naturally tend to stay calm and steady, even when things get stressful or uncertain, and this is supported by a tendency to explore new ideas, ask questions, and welcome different perspectives. This combination of calmness and emotional balance, together with curiosity and openness to new ideas, is likely to help you stay composed and think clearly under pressure."
  },
  {
    "code": "S-C",
    "style": "Composed Achiever",
    "description": "Primary personality tendency in Emotional Stability: consistently shows calmness, resilience, and the ability to stay emotionally balanced under pressure. This is complemented by a secondary Conscientiousness tendency toward discipline, responsibility, and a goal-directed, organized approach to tasks. Together, this style suggests a young person who leads with achiever-like tendencies day-to-day, while also drawing on planner-like tendencies as a supporting behavioural pattern, which is useful for counsellors to note when framing stream and activity recommendations.",
    "explanation": "You naturally tend to stay calm and steady, even when things get stressful or uncertain, and this is supported by a tendency to stay organized, follow through on responsibilities, and work in a disciplined way. This combination of calmness and emotional balance, together with discipline and reliability, is likely to help you stay composed and think clearly under pressure."
  },
  {
    "code": "S-E",
    "style": "Steady Socializer",
    "description": "Primary personality tendency in Emotional Stability: consistently shows calmness, resilience, and the ability to stay emotionally balanced under pressure. This is complemented by a secondary Extraversion tendency toward social energy, communication, and active engagement with people and surroundings. Together, this style suggests a young person who leads with achiever-like tendencies day-to-day, while also drawing on communicator-like tendencies as a supporting behavioural pattern, which is useful for counsellors to note when framing stream and activity recommendations.",
    "explanation": "You naturally tend to stay calm and steady, even when things get stressful or uncertain, and this is supported by a tendency to engage actively with people, share your energy, and enjoy social situations. This combination of calmness and emotional balance, together with social energy and communication, is likely to help you stay composed and think clearly under pressure."
  },
  {
    "code": "S-A",
    "style": "Balanced Supporter",
    "description": "Primary personality tendency in Emotional Stability: consistently shows calmness, resilience, and the ability to stay emotionally balanced under pressure. This is complemented by a secondary Agreeableness tendency toward empathy, cooperation, and consideration for the feelings and needs of others. Together, this style suggests a young person who leads with achiever-like tendencies day-to-day, while also drawing on collaborator-like tendencies as a supporting behavioural pattern, which is useful for counsellors to note when framing stream and activity recommendations.",
    "explanation": "You naturally tend to stay calm and steady, even when things get stressful or uncertain, and this is supported by a tendency to consider others' feelings, cooperate, and build harmonious relationships. This combination of calmness and emotional balance, together with empathy and cooperation, is likely to help you stay composed and think clearly under pressure."
  }
];
