// AUTO-GENERATED by scripts/export-assessment-scoring.py — do not edit by hand.
// Source: docs/Class 910_Traits  Weightages (1).xlsx

import type { DomainWeightEntry } from "./types.js";

export const domainWeights: DomainWeightEntry[] = [
  {
    "cluster": "Information Technology & Digital",
    "industry": "Data Science & Artificial Intelligence",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Data Science & Artificial Intelligence is best suited to students who bring curiosity and analytical thinking, clear, logical thinking, strong number sense, the ability to adapt and learn quickly, and discipline and reliability. Within the Information Technology & Digital cluster, your curiosity and evidence-based thinking is what tends to make the biggest difference in this line of work.",
    "weights": {
      "INVESTIGATIVE": 35.0,
      "CONSCIENTIOUSNESS": 5.0,
      "NUMERICAL": 20.0,
      "LOGICAL": 25.0,
      "LEARNING_VELOCITY": 15.0
    }
  },
  {
    "cluster": "Food & Agriculture",
    "industry": "Food & Agriculture",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Food & Agriculture is best suited to students who bring practical, hands-on skill, curiosity and analytical thinking, discipline and reliability, clear, logical thinking, and empathy and people skills. Within the Food & Agriculture cluster, your hands-on, practical approach is what tends to make the biggest difference in this line of work.",
    "weights": {
      "REALISTIC": 35.0,
      "INVESTIGATIVE": 25.0,
      "SOCIAL": 5.0,
      "CONSCIENTIOUSNESS": 20.0,
      "LOGICAL": 15.0
    }
  },
  {
    "cluster": "Engineering",
    "industry": "Architecture",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Architecture is best suited to students who bring creativity and original thinking, strong visual and spatial thinking, practical, hands-on skill, discipline and reliability, and clear, logical thinking. Within the Engineering cluster, your creativity and original ideas is what tends to make the biggest difference in this line of work.",
    "weights": {
      "REALISTIC": 20.0,
      "ARTISTIC": 35.0,
      "CONSCIENTIOUSNESS": 15.0,
      "LOGICAL": 5.0,
      "SPATIAL": 25.0
    }
  },
  {
    "cluster": "Media & Entertainment",
    "industry": "Media & Communication",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Media & Communication is best suited to students who bring creativity and original thinking, social energy and communication, strong verbal and language skills, empathy and people skills, and curiosity and openness to new ideas. Within the Media & Entertainment cluster, your creativity and original ideas is what tends to make the biggest difference in this line of work.",
    "weights": {
      "ARTISTIC": 35.0,
      "SOCIAL": 15.0,
      "OPENNESS": 5.0,
      "EXTRAVERSION": 25.0,
      "VERBAL": 20.0
    }
  },
  {
    "cluster": "Arts, Design & Creative",
    "industry": "Design, Animation & Graphics",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Design, Animation & Graphics is best suited to students who bring creativity and original thinking, strong visual and spatial thinking, curiosity and openness to new ideas, discipline and reliability, and the ability to adapt and learn quickly. Within the Arts, Design & Creative cluster, your creativity and original ideas is what tends to make the biggest difference in this line of work.",
    "weights": {
      "ARTISTIC": 35.0,
      "OPENNESS": 20.0,
      "CONSCIENTIOUSNESS": 15.0,
      "SPATIAL": 25.0,
      "LEARNING_VELOCITY": 5.0
    }
  },
  {
    "cluster": "Healthcare & Wellness",
    "industry": "Medicine",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Medicine is best suited to students who bring curiosity and analytical thinking, discipline and reliability, calmness and emotional balance, empathy and people skills, and clear, logical thinking. Within the Healthcare & Wellness cluster, your curiosity and evidence-based thinking is what tends to make the biggest difference in this line of work.",
    "weights": {
      "INVESTIGATIVE": 35.0,
      "SOCIAL": 15.0,
      "CONSCIENTIOUSNESS": 25.0,
      "EMOTIONAL_STABILITY": 20.0,
      "LOGICAL": 5.0
    }
  },
  {
    "cluster": "Business, Sales & Management",
    "industry": "Marketing & Advertisement",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Marketing & Advertisement is best suited to students who bring confidence and initiative, social energy and communication, creativity and original thinking, strong verbal and language skills, and comfort with risk and uncertainty. Within the Business, Sales & Management cluster, your confidence, initiative and leadership is what tends to make the biggest difference in this line of work.",
    "weights": {
      "ARTISTIC": 20.0,
      "ENTERPRISING": 35.0,
      "EXTRAVERSION": 25.0,
      "VERBAL": 15.0,
      "UNCERTAINTY_TOLERANCE": 5.0
    }
  },
  {
    "cluster": "Business, Sales & Management",
    "industry": "Sales & Management",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Sales & Management is best suited to students who bring confidence and initiative, social energy and communication, empathy and people skills, calmness and emotional balance, and strong verbal and language skills. Within the Business, Sales & Management cluster, your confidence, initiative and leadership is what tends to make the biggest difference in this line of work.",
    "weights": {
      "SOCIAL": 20.0,
      "ENTERPRISING": 35.0,
      "EXTRAVERSION": 25.0,
      "EMOTIONAL_STABILITY": 15.0,
      "VERBAL": 5.0
    }
  },
  {
    "cluster": "Finance",
    "industry": "Finance & Banking",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Finance & Banking is best suited to students who bring organization and attention to detail, strong number sense, discipline and reliability, clear, logical thinking, and confidence and initiative. Within the Finance cluster, your organization and attention to detail is what tends to make the biggest difference in this line of work.",
    "weights": {
      "ENTERPRISING": 5.0,
      "CONVENTIONAL": 35.0,
      "CONSCIENTIOUSNESS": 20.0,
      "NUMERICAL": 25.0,
      "LOGICAL": 15.0
    }
  },
  {
    "cluster": "Finance",
    "industry": "Economics",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Economics is best suited to students who bring curiosity and analytical thinking, strong number sense, clear, logical thinking, strong verbal and language skills, and discipline and reliability. Within the Finance cluster, your curiosity and evidence-based thinking is what tends to make the biggest difference in this line of work.",
    "weights": {
      "INVESTIGATIVE": 35.0,
      "CONSCIENTIOUSNESS": 5.0,
      "NUMERICAL": 25.0,
      "VERBAL": 15.0,
      "LOGICAL": 20.0
    }
  },
  {
    "cluster": "Business, Sales & Management",
    "industry": "Hotel Management",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Hotel Management is best suited to students who bring empathy and people skills, social energy and communication, organization and attention to detail, calmness and emotional balance, and warmth and cooperation. Within the Business, Sales & Management cluster, your empathy and ability to connect with people is what tends to make the biggest difference in this line of work.",
    "weights": {
      "SOCIAL": 35.0,
      "CONVENTIONAL": 20.0,
      "EXTRAVERSION": 25.0,
      "AGREEABLENESS": 5.0,
      "EMOTIONAL_STABILITY": 15.0
    }
  },
  {
    "cluster": "Engineering",
    "industry": "Engineering",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Engineering is best suited to students who bring practical, hands-on skill, curiosity and analytical thinking, clear, logical thinking, strong number sense, and discipline and reliability. Within the Engineering cluster, your hands-on, practical approach is what tends to make the biggest difference in this line of work.",
    "weights": {
      "REALISTIC": 35.0,
      "INVESTIGATIVE": 25.0,
      "CONSCIENTIOUSNESS": 5.0,
      "NUMERICAL": 15.0,
      "LOGICAL": 20.0
    }
  },
  {
    "cluster": "Information Technology & Digital",
    "industry": "Ethical Hacking",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Ethical Hacking is best suited to students who bring curiosity and analytical thinking, clear, logical thinking, the ability to adapt and learn quickly, practical, hands-on skill, and discipline and reliability. Within the Information Technology & Digital cluster, your curiosity and evidence-based thinking is what tends to make the biggest difference in this line of work.",
    "weights": {
      "REALISTIC": 15.0,
      "INVESTIGATIVE": 35.0,
      "CONSCIENTIOUSNESS": 5.0,
      "LOGICAL": 25.0,
      "LEARNING_VELOCITY": 20.0
    }
  },
  {
    "cluster": "Aviation",
    "industry": "Aviation",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Aviation is best suited to students who bring practical, hands-on skill, calmness and emotional balance, discipline and reliability, strong visual and spatial thinking, and organization and attention to detail. Within the Aviation cluster, your hands-on, practical approach is what tends to make the biggest difference in this line of work.",
    "weights": {
      "REALISTIC": 35.0,
      "CONVENTIONAL": 5.0,
      "CONSCIENTIOUSNESS": 20.0,
      "EMOTIONAL_STABILITY": 25.0,
      "SPATIAL": 15.0
    }
  },
  {
    "cluster": "Information Technology & Digital",
    "industry": "Computer Applications & IT",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Computer Applications & IT is best suited to students who bring organization and attention to detail, clear, logical thinking, curiosity and analytical thinking, the ability to adapt and learn quickly, and strong number sense. Within the Information Technology & Digital cluster, your organization and attention to detail is what tends to make the biggest difference in this line of work.",
    "weights": {
      "INVESTIGATIVE": 20.0,
      "CONVENTIONAL": 35.0,
      "NUMERICAL": 5.0,
      "LOGICAL": 25.0,
      "LEARNING_VELOCITY": 15.0
    }
  },
  {
    "cluster": "Healthcare & Wellness",
    "industry": "Nutrition & Fitness",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Nutrition & Fitness is best suited to students who bring empathy and people skills, curiosity and analytical thinking, practical, hands-on skill, discipline and reliability, and warmth and cooperation. Within the Healthcare & Wellness cluster, your empathy and ability to connect with people is what tends to make the biggest difference in this line of work.",
    "weights": {
      "REALISTIC": 20.0,
      "INVESTIGATIVE": 25.0,
      "SOCIAL": 35.0,
      "CONSCIENTIOUSNESS": 15.0,
      "AGREEABLENESS": 5.0
    }
  },
  {
    "cluster": "Social Science & Education",
    "industry": "Education & Training",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Education & Training is best suited to students who bring empathy and people skills, strong verbal and language skills, warmth and cooperation, discipline and reliability, and social energy and communication. Within the Social Science & Education cluster, your empathy and ability to connect with people is what tends to make the biggest difference in this line of work.",
    "weights": {
      "SOCIAL": 35.0,
      "CONSCIENTIOUSNESS": 15.0,
      "EXTRAVERSION": 5.0,
      "AGREEABLENESS": 20.0,
      "VERBAL": 25.0
    }
  },
  {
    "cluster": "Logistics & Maritime",
    "industry": "Distribution & Logistics",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Distribution & Logistics is best suited to students who bring organization and attention to detail, practical, hands-on skill, discipline and reliability, clear, logical thinking, and strong number sense. Within the Logistics & Maritime cluster, your organization and attention to detail is what tends to make the biggest difference in this line of work.",
    "weights": {
      "REALISTIC": 25.0,
      "CONVENTIONAL": 35.0,
      "CONSCIENTIOUSNESS": 20.0,
      "NUMERICAL": 5.0,
      "LOGICAL": 15.0
    }
  },
  {
    "cluster": "Healthcare & Wellness",
    "industry": "Psychology",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Psychology is best suited to students who bring curiosity and analytical thinking, empathy and people skills, warmth and cooperation, calmness and emotional balance, and strong verbal and language skills. Within the Healthcare & Wellness cluster, your curiosity and evidence-based thinking is what tends to make the biggest difference in this line of work.",
    "weights": {
      "INVESTIGATIVE": 35.0,
      "SOCIAL": 25.0,
      "AGREEABLENESS": 20.0,
      "EMOTIONAL_STABILITY": 15.0,
      "VERBAL": 5.0
    }
  },
  {
    "cluster": "Social Science & Education",
    "industry": "Language",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Language is best suited to students who bring creativity and original thinking, strong verbal and language skills, curiosity and openness to new ideas, empathy and people skills, and warmth and cooperation. Within the Social Science & Education cluster, your creativity and original ideas is what tends to make the biggest difference in this line of work.",
    "weights": {
      "ARTISTIC": 35.0,
      "SOCIAL": 15.0,
      "OPENNESS": 20.0,
      "AGREEABLENESS": 5.0,
      "VERBAL": 25.0
    }
  },
  {
    "cluster": "Social Science & Education",
    "industry": "Social Services & Humanities",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Social Services & Humanities is best suited to students who bring empathy and people skills, warmth and cooperation, calmness and emotional balance, strong verbal and language skills, and curiosity and openness to new ideas. Within the Social Science & Education cluster, your empathy and ability to connect with people is what tends to make the biggest difference in this line of work.",
    "weights": {
      "SOCIAL": 35.0,
      "OPENNESS": 5.0,
      "AGREEABLENESS": 25.0,
      "EMOTIONAL_STABILITY": 20.0,
      "VERBAL": 15.0
    }
  },
  {
    "cluster": "Finance",
    "industry": "Commerce & Accounts",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Commerce & Accounts is best suited to students who bring organization and attention to detail, strong number sense, discipline and reliability, clear, logical thinking, and confidence and initiative. Within the Finance cluster, your organization and attention to detail is what tends to make the biggest difference in this line of work.",
    "weights": {
      "ENTERPRISING": 5.0,
      "CONVENTIONAL": 35.0,
      "CONSCIENTIOUSNESS": 20.0,
      "NUMERICAL": 25.0,
      "LOGICAL": 15.0
    }
  },
  {
    "cluster": "Law & Governance",
    "industry": "Political Science",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Political Science is best suited to students who bring curiosity and analytical thinking, strong verbal and language skills, empathy and people skills, confidence and initiative, and curiosity and openness to new ideas. Within the Law & Governance cluster, your curiosity and evidence-based thinking is what tends to make the biggest difference in this line of work.",
    "weights": {
      "INVESTIGATIVE": 35.0,
      "SOCIAL": 20.0,
      "ENTERPRISING": 15.0,
      "OPENNESS": 5.0,
      "VERBAL": 25.0
    }
  },
  {
    "cluster": "Law & Governance",
    "industry": "Civil Services",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Civil Services is best suited to students who bring empathy and people skills, discipline and reliability, calmness and emotional balance, strong verbal and language skills, and confidence and initiative. Within the Law & Governance cluster, your empathy and ability to connect with people is what tends to make the biggest difference in this line of work.",
    "weights": {
      "SOCIAL": 35.0,
      "ENTERPRISING": 5.0,
      "CONSCIENTIOUSNESS": 25.0,
      "EMOTIONAL_STABILITY": 20.0,
      "VERBAL": 15.0
    }
  },
  {
    "cluster": "Law & Governance",
    "industry": "Defence",
    "domain": "Armed Forces – Officer",
    "weightSum": 95.0,
    "explanation": "Defence is best suited to students who bring practical, hands-on skill, calmness and emotional balance, discipline and reliability, clear, logical thinking, and confidence in making decisions. Within the Law & Governance cluster, your hands-on, practical approach is what tends to make the biggest difference in this line of work.",
    "weights": {
      "REALISTIC": 35.0,
      "CONSCIENTIOUSNESS": 20.0,
      "EMOTIONAL_STABILITY": 25.0,
      "LOGICAL": 15.0
    }
  },
  {
    "cluster": "Law & Governance",
    "industry": "Defence",
    "domain": "Armed Forces – Soldier",
    "weightSum": 95.0,
    "explanation": "Defence is best suited to students who bring practical, hands-on skill, calmness and emotional balance, discipline and reliability, clear, logical thinking, and confidence in making decisions. Within the Law & Governance cluster, your hands-on, practical approach is what tends to make the biggest difference in this line of work.",
    "weights": {
      "REALISTIC": 35.0,
      "CONSCIENTIOUSNESS": 20.0,
      "EMOTIONAL_STABILITY": 25.0,
      "LOGICAL": 15.0
    }
  },
  {
    "cluster": "Law & Governance",
    "industry": "Defence",
    "domain": "Technical Roles",
    "weightSum": 95.0,
    "explanation": "Defence is best suited to students who bring practical, hands-on skill, clear, logical thinking, discipline and reliability, calmness and emotional balance, and confidence in making decisions. Within the Law & Governance cluster, your hands-on, practical approach is what tends to make the biggest difference in this line of work.",
    "weights": {
      "REALISTIC": 30.0,
      "CONSCIENTIOUSNESS": 20.0,
      "EMOTIONAL_STABILITY": 20.0,
      "LOGICAL": 25.0
    }
  },
  {
    "cluster": "Law & Governance",
    "industry": "Defence",
    "domain": "Intelligence",
    "weightSum": 90.0,
    "explanation": "Defence is best suited to students who bring curiosity and analytical thinking, discipline and reliability, calmness and emotional balance, clear, logical thinking, and confidence in making decisions. Within the Law & Governance cluster, your curiosity and evidence-based thinking is what tends to make the biggest difference in this line of work.",
    "weights": {
      "INVESTIGATIVE": 30.0,
      "CONSCIENTIOUSNESS": 20.0,
      "EMOTIONAL_STABILITY": 20.0,
      "LOGICAL": 20.0
    }
  },
  {
    "cluster": "Law & Governance",
    "industry": "Defence",
    "domain": "R&D",
    "weightSum": 100.0,
    "explanation": "Defence is best suited to students who bring curiosity and analytical thinking, clear, logical thinking, calmness and emotional balance, discipline and reliability, and the ability to adapt and learn quickly. Within the Law & Governance cluster, your curiosity and evidence-based thinking is what tends to make the biggest difference in this line of work.",
    "weights": {
      "INVESTIGATIVE": 30.0,
      "CONSCIENTIOUSNESS": 15.0,
      "EMOTIONAL_STABILITY": 20.0,
      "LOGICAL": 25.0,
      "LEARNING_VELOCITY": 10.0
    }
  },
  {
    "cluster": "Law & Governance",
    "industry": "Defence",
    "domain": "Paramilitary",
    "weightSum": 95.0,
    "explanation": "Defence is best suited to students who bring practical, hands-on skill, calmness and emotional balance, discipline and reliability, clear, logical thinking, and confidence in making decisions. Within the Law & Governance cluster, your hands-on, practical approach is what tends to make the biggest difference in this line of work.",
    "weights": {
      "REALISTIC": 35.0,
      "CONSCIENTIOUSNESS": 20.0,
      "EMOTIONAL_STABILITY": 25.0,
      "LOGICAL": 15.0
    }
  },
  {
    "cluster": "Law & Governance",
    "industry": "Defence",
    "domain": "Special Forces",
    "weightSum": 90.0,
    "explanation": "Defence is best suited to students who bring practical, hands-on skill, calmness and emotional balance, discipline and reliability, clear, logical thinking, and confidence in making decisions. Within the Law & Governance cluster, your hands-on, practical approach is what tends to make the biggest difference in this line of work.",
    "weights": {
      "REALISTIC": 35.0,
      "CONSCIENTIOUSNESS": 15.0,
      "EMOTIONAL_STABILITY": 25.0,
      "LOGICAL": 15.0
    }
  },
  {
    "cluster": "Law & Governance",
    "industry": "Defence",
    "domain": "Administration",
    "weightSum": 90.0,
    "explanation": "Defence is best suited to students who bring organization and attention to detail, discipline and reliability, calmness and emotional balance, strong verbal and language skills, and confidence in making decisions. Within the Law & Governance cluster, your organization and attention to detail is what tends to make the biggest difference in this line of work.",
    "weights": {
      "CONVENTIONAL": 30.0,
      "CONSCIENTIOUSNESS": 25.0,
      "EMOTIONAL_STABILITY": 20.0,
      "VERBAL": 15.0
    }
  },
  {
    "cluster": "Law & Governance",
    "industry": "Defence",
    "domain": "Medical",
    "weightSum": 100.0,
    "explanation": "Defence is best suited to students who bring curiosity and analytical thinking, discipline and reliability, calmness and emotional balance, clear, logical thinking, and warmth and cooperation. Within the Law & Governance cluster, your curiosity and evidence-based thinking is what tends to make the biggest difference in this line of work.",
    "weights": {
      "INVESTIGATIVE": 30.0,
      "CONSCIENTIOUSNESS": 20.0,
      "AGREEABLENESS": 10.0,
      "EMOTIONAL_STABILITY": 20.0,
      "LOGICAL": 20.0
    }
  },
  {
    "cluster": "Law & Governance",
    "industry": "Defence",
    "domain": "Cyber Warfare",
    "weightSum": 100.0,
    "explanation": "Defence is best suited to students who bring curiosity and analytical thinking, clear, logical thinking, calmness and emotional balance, discipline and reliability, and the ability to adapt and learn quickly. Within the Law & Governance cluster, your curiosity and evidence-based thinking is what tends to make the biggest difference in this line of work.",
    "weights": {
      "INVESTIGATIVE": 35.0,
      "CONSCIENTIOUSNESS": 15.0,
      "EMOTIONAL_STABILITY": 20.0,
      "LOGICAL": 25.0,
      "LEARNING_VELOCITY": 5.0
    }
  },
  {
    "cluster": "STEM Career",
    "industry": "Maths & Statistics",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Maths & Statistics is best suited to students who bring curiosity and analytical thinking, strong number sense, clear, logical thinking, discipline and reliability, and the ability to adapt and learn quickly. Within the STEM Career cluster, your curiosity and evidence-based thinking is what tends to make the biggest difference in this line of work.",
    "weights": {
      "INVESTIGATIVE": 35.0,
      "CONSCIENTIOUSNESS": 15.0,
      "NUMERICAL": 25.0,
      "LOGICAL": 20.0,
      "LEARNING_VELOCITY": 5.0
    }
  },
  {
    "cluster": "Law & Governance",
    "industry": "Law",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Law is best suited to students who bring curiosity and analytical thinking, strong verbal and language skills, clear, logical thinking, discipline and reliability, and confidence and initiative. Within the Law & Governance cluster, your curiosity and evidence-based thinking is what tends to make the biggest difference in this line of work.",
    "weights": {
      "INVESTIGATIVE": 35.0,
      "ENTERPRISING": 5.0,
      "CONSCIENTIOUSNESS": 15.0,
      "VERBAL": 25.0,
      "LOGICAL": 20.0
    }
  },
  {
    "cluster": "Arts, Design & Creative",
    "industry": "Applied Arts",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Applied Arts is best suited to students who bring creativity and original thinking, practical, hands-on skill, curiosity and openness to new ideas, discipline and reliability, and strong visual and spatial thinking. Within the Arts, Design & Creative cluster, your creativity and original ideas is what tends to make the biggest difference in this line of work.",
    "weights": {
      "REALISTIC": 25.0,
      "ARTISTIC": 35.0,
      "OPENNESS": 20.0,
      "CONSCIENTIOUSNESS": 15.0,
      "SPATIAL": 5.0
    }
  },
  {
    "cluster": "Healthcare & Wellness",
    "industry": "Applied Medicine",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Applied Medicine is best suited to students who bring curiosity and analytical thinking, empathy and people skills, discipline and reliability, calmness and emotional balance, and warmth and cooperation. Within the Healthcare & Wellness cluster, your curiosity and evidence-based thinking is what tends to make the biggest difference in this line of work.",
    "weights": {
      "INVESTIGATIVE": 35.0,
      "SOCIAL": 25.0,
      "CONSCIENTIOUSNESS": 20.0,
      "AGREEABLENESS": 5.0,
      "EMOTIONAL_STABILITY": 15.0
    }
  },
  {
    "cluster": "Healthcare & Wellness",
    "industry": "Allied Medicine",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Allied Medicine is best suited to students who bring curiosity and analytical thinking, empathy and people skills, discipline and reliability, calmness and emotional balance, and warmth and cooperation. Within the Healthcare & Wellness cluster, your curiosity and evidence-based thinking is what tends to make the biggest difference in this line of work.",
    "weights": {
      "INVESTIGATIVE": 35.0,
      "SOCIAL": 25.0,
      "CONSCIENTIOUSNESS": 20.0,
      "AGREEABLENESS": 5.0,
      "EMOTIONAL_STABILITY": 15.0
    }
  },
  {
    "cluster": "Food & Agriculture",
    "industry": "Life Science & Environment",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Life Science & Environment is best suited to students who bring curiosity and analytical thinking, practical, hands-on skill, curiosity and openness to new ideas, discipline and reliability, and clear, logical thinking. Within the Food & Agriculture cluster, your curiosity and evidence-based thinking is what tends to make the biggest difference in this line of work.",
    "weights": {
      "REALISTIC": 25.0,
      "INVESTIGATIVE": 35.0,
      "OPENNESS": 20.0,
      "CONSCIENTIOUSNESS": 15.0,
      "LOGICAL": 5.0
    }
  },
  {
    "cluster": "Logistics & Maritime",
    "industry": "Merchant Navy",
    "domain": "Deck",
    "weightSum": 95.0,
    "explanation": "Merchant Navy is best suited to students who bring practical, hands-on skill, calmness and emotional balance, discipline and reliability, strong visual and spatial thinking, and confidence in making decisions. Within the Logistics & Maritime cluster, your hands-on, practical approach is what tends to make the biggest difference in this line of work.",
    "weights": {
      "REALISTIC": 35.0,
      "CONSCIENTIOUSNESS": 20.0,
      "EMOTIONAL_STABILITY": 25.0,
      "SPATIAL": 15.0
    }
  },
  {
    "cluster": "Logistics & Maritime",
    "industry": "Merchant Navy",
    "domain": "Engine",
    "weightSum": 95.0,
    "explanation": "Merchant Navy is best suited to students who bring practical, hands-on skill, discipline and reliability, calmness and emotional balance, clear, logical thinking, and confidence in making decisions. Within the Logistics & Maritime cluster, your hands-on, practical approach is what tends to make the biggest difference in this line of work.",
    "weights": {
      "REALISTIC": 35.0,
      "CONSCIENTIOUSNESS": 25.0,
      "EMOTIONAL_STABILITY": 20.0,
      "LOGICAL": 15.0
    }
  },
  {
    "cluster": "Logistics & Maritime",
    "industry": "Merchant Navy",
    "domain": "Electrical",
    "weightSum": 95.0,
    "explanation": "Merchant Navy is best suited to students who bring practical, hands-on skill, discipline and reliability, calmness and emotional balance, clear, logical thinking, and confidence in making decisions. Within the Logistics & Maritime cluster, your hands-on, practical approach is what tends to make the biggest difference in this line of work.",
    "weights": {
      "REALISTIC": 30.0,
      "CONSCIENTIOUSNESS": 25.0,
      "EMOTIONAL_STABILITY": 20.0,
      "LOGICAL": 20.0
    }
  },
  {
    "cluster": "Logistics & Maritime",
    "industry": "Merchant Navy",
    "domain": "Catering",
    "weightSum": 90.0,
    "explanation": "Merchant Navy is best suited to students who bring practical, hands-on skill, discipline and reliability, warmth and cooperation, calmness and emotional balance, and confidence in making decisions. Within the Logistics & Maritime cluster, your hands-on, practical approach is what tends to make the biggest difference in this line of work.",
    "weights": {
      "REALISTIC": 25.0,
      "CONSCIENTIOUSNESS": 25.0,
      "AGREEABLENESS": 20.0,
      "EMOTIONAL_STABILITY": 20.0
    }
  },
  {
    "cluster": "Logistics & Maritime",
    "industry": "Merchant Navy",
    "domain": "Specialized",
    "weightSum": 100.0,
    "explanation": "Merchant Navy is best suited to students who bring practical, hands-on skill, discipline and reliability, calmness and emotional balance, clear, logical thinking, and strong visual and spatial thinking. Within the Logistics & Maritime cluster, your hands-on, practical approach is what tends to make the biggest difference in this line of work.",
    "weights": {
      "REALISTIC": 35.0,
      "CONSCIENTIOUSNESS": 20.0,
      "EMOTIONAL_STABILITY": 20.0,
      "LOGICAL": 15.0,
      "SPATIAL": 10.0
    }
  },
  {
    "cluster": "Logistics & Maritime",
    "industry": "Merchant Navy",
    "domain": "Logistics",
    "weightSum": 90.0,
    "explanation": "Merchant Navy is best suited to students who bring organization and attention to detail, discipline and reliability, calmness and emotional balance, strong number sense, and confidence in making decisions. Within the Logistics & Maritime cluster, your organization and attention to detail is what tends to make the biggest difference in this line of work.",
    "weights": {
      "CONVENTIONAL": 30.0,
      "CONSCIENTIOUSNESS": 25.0,
      "EMOTIONAL_STABILITY": 20.0,
      "NUMERICAL": 15.0
    }
  },
  {
    "cluster": "Logistics & Maritime",
    "industry": "Merchant Navy",
    "domain": "Safety & Research",
    "weightSum": 90.0,
    "explanation": "Merchant Navy is best suited to students who bring curiosity and analytical thinking, discipline and reliability, calmness and emotional balance, clear, logical thinking, and confidence in making decisions. Within the Logistics & Maritime cluster, your curiosity and evidence-based thinking is what tends to make the biggest difference in this line of work.",
    "weights": {
      "INVESTIGATIVE": 30.0,
      "CONSCIENTIOUSNESS": 25.0,
      "EMOTIONAL_STABILITY": 20.0,
      "LOGICAL": 15.0
    }
  },
  {
    "cluster": "Logistics & Maritime",
    "industry": "Merchant Navy",
    "domain": "Cruise",
    "weightSum": 100.0,
    "explanation": "Merchant Navy is best suited to students who bring practical, hands-on skill, warmth and cooperation, discipline and reliability, calmness and emotional balance, and social energy and communication. Within the Logistics & Maritime cluster, your hands-on, practical approach is what tends to make the biggest difference in this line of work.",
    "weights": {
      "REALISTIC": 25.0,
      "CONSCIENTIOUSNESS": 20.0,
      "EXTRAVERSION": 10.0,
      "AGREEABLENESS": 25.0,
      "EMOTIONAL_STABILITY": 20.0
    }
  },
  {
    "cluster": "Logistics & Maritime",
    "industry": "Merchant Navy",
    "domain": "Future Maritime",
    "weightSum": 100.0,
    "explanation": "Merchant Navy is best suited to students who bring curiosity and analytical thinking, discipline and reliability, calmness and emotional balance, the ability to adapt and learn quickly, and clear, logical thinking. Within the Logistics & Maritime cluster, your curiosity and evidence-based thinking is what tends to make the biggest difference in this line of work.",
    "weights": {
      "INVESTIGATIVE": 30.0,
      "CONSCIENTIOUSNESS": 20.0,
      "EMOTIONAL_STABILITY": 20.0,
      "LOGICAL": 10.0,
      "LEARNING_VELOCITY": 20.0
    }
  },
  {
    "cluster": "STEM Career",
    "industry": "Physical Science",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Physical Science is best suited to students who bring curiosity and analytical thinking, strong number sense, clear, logical thinking, practical, hands-on skill, and discipline and reliability. Within the STEM Career cluster, your curiosity and evidence-based thinking is what tends to make the biggest difference in this line of work.",
    "weights": {
      "REALISTIC": 15.0,
      "INVESTIGATIVE": 35.0,
      "CONSCIENTIOUSNESS": 5.0,
      "NUMERICAL": 25.0,
      "LOGICAL": 20.0
    }
  },
  {
    "cluster": "Arts, Design & Creative",
    "industry": "Performing Arts",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Performing Arts is best suited to students who bring creativity and original thinking, social energy and communication, curiosity and openness to new ideas, calmness and emotional balance, and empathy and people skills. Within the Arts, Design & Creative cluster, your creativity and original ideas is what tends to make the biggest difference in this line of work.",
    "weights": {
      "ARTISTIC": 35.0,
      "SOCIAL": 5.0,
      "OPENNESS": 20.0,
      "EXTRAVERSION": 25.0,
      "EMOTIONAL_STABILITY": 15.0
    }
  },
  {
    "cluster": "Aviation",
    "industry": "Cabin Crew",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Cabin Crew is best suited to students who bring social energy and communication, empathy and people skills, warmth and cooperation, calmness and emotional balance, and organization and attention to detail. Within the Aviation cluster, your social energy and communication is what tends to make the biggest difference in this line of work.",
    "weights": {
      "SOCIAL": 25.0,
      "CONVENTIONAL": 5.0,
      "EXTRAVERSION": 35.0,
      "AGREEABLENESS": 20.0,
      "EMOTIONAL_STABILITY": 15.0
    }
  },
  {
    "cluster": "Business, Sales & Management",
    "industry": "Entrepreneurship",
    "domain": "Startup Founding",
    "weightSum": 85.0,
    "explanation": "Entrepreneurship is best suited to students who bring confidence and initiative, comfort with risk and uncertainty, the ability to work independently, confidence in making decisions, and the ability to adapt and learn quickly. Within the Business, Sales & Management cluster, your confidence, initiative and leadership is what tends to make the biggest difference in this line of work.",
    "weights": {
      "ENTERPRISING": 35.0,
      "LEARNING_VELOCITY": 5.0,
      "UNCERTAINTY_TOLERANCE": 25.0,
      "AUTONOMY_PREFERENCE": 20.0
    }
  },
  {
    "cluster": "Business, Sales & Management",
    "industry": "Entrepreneurship",
    "domain": "Tech Entrepreneurship",
    "weightSum": 85.0,
    "explanation": "Entrepreneurship is best suited to students who bring confidence and initiative, curiosity and analytical thinking, comfort with risk and uncertainty, the ability to work independently, and confidence in making decisions. Within the Business, Sales & Management cluster, your confidence, initiative and leadership is what tends to make the biggest difference in this line of work.",
    "weights": {
      "INVESTIGATIVE": 20.0,
      "ENTERPRISING": 30.0,
      "UNCERTAINTY_TOLERANCE": 20.0,
      "AUTONOMY_PREFERENCE": 15.0
    }
  },
  {
    "cluster": "Business, Sales & Management",
    "industry": "Entrepreneurship",
    "domain": "Creative Entrepreneurship",
    "weightSum": 90.0,
    "explanation": "Entrepreneurship is best suited to students who bring confidence and initiative, creativity and original thinking, comfort with risk and uncertainty, the ability to work independently, and confidence in making decisions. Within the Business, Sales & Management cluster, your confidence, initiative and leadership is what tends to make the biggest difference in this line of work.",
    "weights": {
      "ARTISTIC": 25.0,
      "ENTERPRISING": 30.0,
      "UNCERTAINTY_TOLERANCE": 20.0,
      "AUTONOMY_PREFERENCE": 15.0
    }
  },
  {
    "cluster": "Business, Sales & Management",
    "industry": "Entrepreneurship",
    "domain": "Business Entrepreneurship",
    "weightSum": 85.0,
    "explanation": "Entrepreneurship is best suited to students who bring confidence and initiative, comfort with risk and uncertainty, the ability to work independently, confidence in making decisions, and discipline and reliability. Within the Business, Sales & Management cluster, your confidence, initiative and leadership is what tends to make the biggest difference in this line of work.",
    "weights": {
      "ENTERPRISING": 35.0,
      "CONSCIENTIOUSNESS": 5.0,
      "UNCERTAINTY_TOLERANCE": 25.0,
      "AUTONOMY_PREFERENCE": 20.0
    }
  },
  {
    "cluster": "Business, Sales & Management",
    "industry": "Entrepreneurship",
    "domain": "Social Entrepreneurship",
    "weightSum": 90.0,
    "explanation": "Entrepreneurship is best suited to students who bring confidence and initiative, empathy and people skills, comfort with risk and uncertainty, the ability to work independently, and confidence in making decisions. Within the Business, Sales & Management cluster, your confidence, initiative and leadership is what tends to make the biggest difference in this line of work.",
    "weights": {
      "SOCIAL": 25.0,
      "ENTERPRISING": 30.0,
      "UNCERTAINTY_TOLERANCE": 20.0,
      "AUTONOMY_PREFERENCE": 15.0
    }
  },
  {
    "cluster": "Business, Sales & Management",
    "industry": "Entrepreneurship",
    "domain": "Franchise Business",
    "weightSum": 85.0,
    "explanation": "Entrepreneurship is best suited to students who bring confidence and initiative, organization and attention to detail, comfort with risk and uncertainty, the ability to work independently, and confidence in making decisions. Within the Business, Sales & Management cluster, your confidence, initiative and leadership is what tends to make the biggest difference in this line of work.",
    "weights": {
      "ENTERPRISING": 35.0,
      "CONVENTIONAL": 20.0,
      "UNCERTAINTY_TOLERANCE": 15.0,
      "AUTONOMY_PREFERENCE": 15.0
    }
  },
  {
    "cluster": "Business, Sales & Management",
    "industry": "Entrepreneurship",
    "domain": "Investment Entrepreneurship",
    "weightSum": 90.0,
    "explanation": "Entrepreneurship is best suited to students who bring confidence and initiative, strong number sense, comfort with risk and uncertainty, the ability to work independently, and confidence in making decisions. Within the Business, Sales & Management cluster, your confidence, initiative and leadership is what tends to make the biggest difference in this line of work.",
    "weights": {
      "ENTERPRISING": 35.0,
      "NUMERICAL": 25.0,
      "UNCERTAINTY_TOLERANCE": 20.0,
      "AUTONOMY_PREFERENCE": 10.0
    }
  },
  {
    "cluster": "Business, Sales & Management",
    "industry": "Entrepreneurship",
    "domain": "Food Entrepreneurship",
    "weightSum": 85.0,
    "explanation": "Entrepreneurship is best suited to students who bring confidence and initiative, practical, hands-on skill, comfort with risk and uncertainty, the ability to work independently, and confidence in making decisions. Within the Business, Sales & Management cluster, your confidence, initiative and leadership is what tends to make the biggest difference in this line of work.",
    "weights": {
      "REALISTIC": 20.0,
      "ENTERPRISING": 30.0,
      "UNCERTAINTY_TOLERANCE": 20.0,
      "AUTONOMY_PREFERENCE": 15.0
    }
  },
  {
    "cluster": "Business, Sales & Management",
    "industry": "Entrepreneurship",
    "domain": "Manufacturing",
    "weightSum": 90.0,
    "explanation": "Entrepreneurship is best suited to students who bring confidence and initiative, practical, hands-on skill, discipline and reliability, comfort with risk and uncertainty, and confidence in making decisions. Within the Business, Sales & Management cluster, your confidence, initiative and leadership is what tends to make the biggest difference in this line of work.",
    "weights": {
      "REALISTIC": 25.0,
      "ENTERPRISING": 30.0,
      "CONSCIENTIOUSNESS": 20.0,
      "UNCERTAINTY_TOLERANCE": 15.0
    }
  },
  {
    "cluster": "Business, Sales & Management",
    "industry": "Entrepreneurship",
    "domain": "Wellness Entrepreneurship",
    "weightSum": 90.0,
    "explanation": "Entrepreneurship is best suited to students who bring confidence and initiative, empathy and people skills, comfort with risk and uncertainty, the ability to work independently, and confidence in making decisions. Within the Business, Sales & Management cluster, your confidence, initiative and leadership is what tends to make the biggest difference in this line of work.",
    "weights": {
      "SOCIAL": 25.0,
      "ENTERPRISING": 30.0,
      "UNCERTAINTY_TOLERANCE": 20.0,
      "AUTONOMY_PREFERENCE": 15.0
    }
  },
  {
    "cluster": "Business, Sales & Management",
    "industry": "Entrepreneurship",
    "domain": "Education Entrepreneurship",
    "weightSum": 100.0,
    "explanation": "Entrepreneurship is best suited to students who bring confidence and initiative, empathy and people skills, comfort with risk and uncertainty, the ability to work independently, and the ability to adapt and learn quickly. Within the Business, Sales & Management cluster, your confidence, initiative and leadership is what tends to make the biggest difference in this line of work.",
    "weights": {
      "SOCIAL": 25.0,
      "ENTERPRISING": 30.0,
      "LEARNING_VELOCITY": 10.0,
      "UNCERTAINTY_TOLERANCE": 20.0,
      "AUTONOMY_PREFERENCE": 15.0
    }
  },
  {
    "cluster": "Business, Sales & Management",
    "industry": "Entrepreneurship",
    "domain": "Real Estate",
    "weightSum": 90.0,
    "explanation": "Entrepreneurship is best suited to students who bring confidence and initiative, organization and attention to detail, strong number sense, comfort with risk and uncertainty, and confidence in making decisions. Within the Business, Sales & Management cluster, your confidence, initiative and leadership is what tends to make the biggest difference in this line of work.",
    "weights": {
      "ENTERPRISING": 35.0,
      "CONVENTIONAL": 20.0,
      "NUMERICAL": 20.0,
      "UNCERTAINTY_TOLERANCE": 15.0
    }
  },
  {
    "cluster": "Business, Sales & Management",
    "industry": "Entrepreneurship",
    "domain": "Future Entrepreneurship",
    "weightSum": 90.0,
    "explanation": "Entrepreneurship is best suited to students who bring confidence and initiative, curiosity and analytical thinking, the ability to adapt and learn quickly, comfort with risk and uncertainty, and confidence in making decisions. Within the Business, Sales & Management cluster, your confidence, initiative and leadership is what tends to make the biggest difference in this line of work.",
    "weights": {
      "INVESTIGATIVE": 20.0,
      "ENTERPRISING": 30.0,
      "LEARNING_VELOCITY": 20.0,
      "UNCERTAINTY_TOLERANCE": 20.0
    }
  },
  {
    "cluster": "Finance",
    "industry": "Actuarial Science",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Actuarial Science is best suited to students who bring organization and attention to detail, strong number sense, clear, logical thinking, curiosity and analytical thinking, and discipline and reliability. Within the Finance cluster, your organization and attention to detail is what tends to make the biggest difference in this line of work.",
    "weights": {
      "INVESTIGATIVE": 15.0,
      "CONVENTIONAL": 35.0,
      "CONSCIENTIOUSNESS": 5.0,
      "NUMERICAL": 25.0,
      "LOGICAL": 20.0
    }
  },
  {
    "cluster": "Business, Sales & Management",
    "industry": "Culinary Arts",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Culinary Arts is best suited to students who bring practical, hands-on skill, creativity and original thinking, discipline and reliability, calmness and emotional balance, and warmth and cooperation. Within the Business, Sales & Management cluster, your hands-on, practical approach is what tends to make the biggest difference in this line of work.",
    "weights": {
      "REALISTIC": 35.0,
      "ARTISTIC": 25.0,
      "CONSCIENTIOUSNESS": 20.0,
      "AGREEABLENESS": 5.0,
      "EMOTIONAL_STABILITY": 15.0
    }
  },
  {
    "cluster": "Social Science & Education",
    "industry": "Geography",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Geography is best suited to students who bring curiosity and analytical thinking, practical, hands-on skill, strong visual and spatial thinking, curiosity and openness to new ideas, and discipline and reliability. Within the Social Science & Education cluster, your curiosity and evidence-based thinking is what tends to make the biggest difference in this line of work.",
    "weights": {
      "REALISTIC": 25.0,
      "INVESTIGATIVE": 35.0,
      "OPENNESS": 15.0,
      "CONSCIENTIOUSNESS": 5.0,
      "SPATIAL": 20.0
    }
  },
  {
    "cluster": "Media & Entertainment",
    "industry": "Film Making",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Film Making is best suited to students who bring creativity and original thinking, confidence and initiative, curiosity and openness to new ideas, empathy and people skills, and the ability to adapt and learn quickly. Within the Media & Entertainment cluster, your creativity and original ideas is what tends to make the biggest difference in this line of work.",
    "weights": {
      "ARTISTIC": 35.0,
      "SOCIAL": 15.0,
      "ENTERPRISING": 25.0,
      "OPENNESS": 20.0,
      "LEARNING_VELOCITY": 5.0
    }
  },
  {
    "cluster": "Law & Governance",
    "industry": "International Relations",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "International Relations is best suited to students who bring curiosity and analytical thinking, strong verbal and language skills, empathy and people skills, curiosity and openness to new ideas, and social energy and communication. Within the Law & Governance cluster, your curiosity and evidence-based thinking is what tends to make the biggest difference in this line of work.",
    "weights": {
      "INVESTIGATIVE": 35.0,
      "SOCIAL": 20.0,
      "OPENNESS": 15.0,
      "EXTRAVERSION": 5.0,
      "VERBAL": 25.0
    }
  },
  {
    "cluster": "Social Science & Education",
    "industry": "Museology",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Museology is best suited to students who bring creativity and original thinking, curiosity and analytical thinking, discipline and reliability, curiosity and openness to new ideas, and organization and attention to detail. Within the Social Science & Education cluster, your creativity and original ideas is what tends to make the biggest difference in this line of work.",
    "weights": {
      "INVESTIGATIVE": 25.0,
      "ARTISTIC": 35.0,
      "CONVENTIONAL": 5.0,
      "OPENNESS": 15.0,
      "CONSCIENTIOUSNESS": 20.0
    }
  },
  {
    "cluster": "Social Science & Education",
    "industry": "Sustainability",
    "domain": "All Domains",
    "weightSum": 100.0,
    "explanation": "Sustainability is best suited to students who bring curiosity and analytical thinking, empathy and people skills, curiosity and openness to new ideas, clear, logical thinking, and comfort with risk and uncertainty. Within the Social Science & Education cluster, your curiosity and evidence-based thinking is what tends to make the biggest difference in this line of work.",
    "weights": {
      "INVESTIGATIVE": 35.0,
      "SOCIAL": 25.0,
      "OPENNESS": 20.0,
      "LOGICAL": 15.0,
      "UNCERTAINTY_TOLERANCE": 5.0
    }
  }
];
