// AUTO-GENERATED by scripts/export-assessment-scoring.py — do not edit by hand.
// Source: docs/Class 910_Traits  Weightages (1).xlsx

import type { GraduateStreamEntry } from "./types.js";

export const graduateStreams: GraduateStreamEntry[] = [
  {
    "clusterHead": "Engg, Tech & Pure Science",
    "mainStream": "Engineering & Technology",
    "subStream": "B.Tech / B.E.",
    "specialisations": "Computer Science, Mechanical, Civil, Electronics, AI, Robotics, Aerospace",
    "eligibility": "Mainly PCM",
    "keyExams": "JEE Main, JEE Advanced, BITSAT, VITEEE, SRMJEEE, WBJEE, KEAM, COMEDK UGET, MET (Manipal), KCET, MHT-CET, AEEE, UGEE, Plaksha UG Admission, SNU Admission Process, KIITEE, LPUNEST, PESSAT, JET, UPESEAT, SUAT, MRNAT, GUAT, AUAT, CUCET (Chandigarh Univ.), RVU Admission Process, Presidency PUCET, GAT (GITAM), BU-CET, NPAT, Christ University Entrance Test, CUET UG, NSAT, Sai University Admission Process, IUCET",
    "explanation": "B.Tech / B.E. is best suited to students who bring curiosity and analytical thinking, clear, logical thinking, strong number sense, discipline and reliability, and the ability to adapt and learn quickly. This blend of strengths supports you in areas like Computer Science, Mechanical, Civil, Electronics, AI, Robotics, Aerospace, where your curiosity and evidence-based thinking really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 30.0,
      "CONSCIENTIOUSNESS": 15.0,
      "NUMERICAL": 20.0,
      "LOGICAL": 25.0,
      "LEARNING_VELOCITY": 10.0
    }
  },
  {
    "clusterHead": "Engg, Tech & Pure Science",
    "mainStream": "Engineering & Technology",
    "subStream": "B.Arch",
    "specialisations": "Architecture",
    "eligibility": "PCM with aptitude test",
    "keyExams": "JEE Main, NATA, KCET, WBJEE, KEAM, CEPT Admission Process, Sushant School Admission Process, GAT (GITAM), JMI Entrance Exam",
    "explanation": "B.Arch is best suited to students who bring curiosity and analytical thinking, clear, logical thinking, strong number sense, discipline and reliability, and the ability to adapt and learn quickly. This blend of strengths supports you in areas like Architecture, where your curiosity and evidence-based thinking really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 30.0,
      "CONSCIENTIOUSNESS": 15.0,
      "NUMERICAL": 20.0,
      "LOGICAL": 25.0,
      "LEARNING_VELOCITY": 10.0
    }
  },
  {
    "clusterHead": "Engg, Tech & Pure Science",
    "mainStream": "Engineering & Technology",
    "subStream": "BCA",
    "specialisations": "Computer Applications",
    "eligibility": "Any stream (often Maths preferred)",
    "keyExams": "CUET UG, Christ University Entrance Test, IPU CET, WAT",
    "explanation": "BCA is best suited to students who bring curiosity and analytical thinking, clear, logical thinking, strong number sense, discipline and reliability, and the ability to adapt and learn quickly. This blend of strengths supports you in areas like Computer Applications, where your curiosity and evidence-based thinking really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 30.0,
      "CONSCIENTIOUSNESS": 15.0,
      "NUMERICAL": 20.0,
      "LOGICAL": 25.0,
      "LEARNING_VELOCITY": 10.0
    }
  },
  {
    "clusterHead": "Engg, Tech & Pure Science",
    "mainStream": "Engineering & Technology",
    "subStream": "B.Sc Computer Science",
    "specialisations": "CS, Data Science, AI",
    "eligibility": "PCM / Maths preferred",
    "keyExams": "CUET UG, Scaler Admission Test, Christ University Entrance Test",
    "explanation": "B.Sc Computer Science is best suited to students who bring curiosity and analytical thinking, clear, logical thinking, strong number sense, discipline and reliability, and the ability to adapt and learn quickly. This blend of strengths supports you in areas like CS, Data Science, AI, where your curiosity and evidence-based thinking really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 30.0,
      "CONSCIENTIOUSNESS": 15.0,
      "NUMERICAL": 20.0,
      "LOGICAL": 25.0,
      "LEARNING_VELOCITY": 10.0
    }
  },
  {
    "clusterHead": "Engg, Tech & Pure Science",
    "mainStream": "Engineering & Technology",
    "subStream": "B.Des (Tech Design)",
    "specialisations": "UI/UX, Product Design",
    "eligibility": "Any stream",
    "keyExams": "NIFT Entrance Test, NID DAT, UCEED, SEED, ADEPT, SMEAT, WUDAT, ISDI Challenge, MITID DAT, ICAT Admission Process, KIITEE, LPUNEST, PESSAT, JET, UPESEAT, SUAT, MRNAT, GUAT, CUCET (Chandigarh Univ.), RVU Admission Process, Presidency PUCET",
    "explanation": "B.Des (Tech Design) is best suited to students who bring curiosity and analytical thinking, clear, logical thinking, strong number sense, discipline and reliability, and the ability to adapt and learn quickly. This blend of strengths supports you in areas like UI/UX, Product Design, where your curiosity and evidence-based thinking really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 30.0,
      "CONSCIENTIOUSNESS": 15.0,
      "NUMERICAL": 20.0,
      "LOGICAL": 25.0,
      "LEARNING_VELOCITY": 10.0
    }
  },
  {
    "clusterHead": "Engg, Tech & Pure Science",
    "mainStream": "Pure Sciences",
    "subStream": "B.Sc",
    "specialisations": "Physics, Chemistry, Maths",
    "eligibility": "PCM",
    "keyExams": "CUET UG, IISER Aptitude Test, IISER Aptitude Test (SCB Channel), NEST, INSPIRE Scholarship, KVPY (merged into INSPIRE), ISI Admission Test",
    "explanation": "B.Sc is best suited to students who bring curiosity and analytical thinking, strong number sense, clear, logical thinking, the ability to work independently, and the ability to adapt and learn quickly. This blend of strengths supports you in areas like Physics, Chemistry, Maths, where your curiosity and evidence-based thinking really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 35.0,
      "NUMERICAL": 20.0,
      "LOGICAL": 20.0,
      "LEARNING_VELOCITY": 10.0,
      "AUTONOMY_PREFERENCE": 15.0
    }
  },
  {
    "clusterHead": "Engg, Tech & Pure Science",
    "mainStream": "Pure Sciences",
    "subStream": "B.Sc Life Sciences",
    "specialisations": "Zoology, Botany, Genetics",
    "eligibility": "PCB",
    "keyExams": "CUET UG, IISER Aptitude Test, IISER Aptitude Test (SCB Channel), NEST, INSPIRE Scholarship, KVPY (merged into INSPIRE)",
    "explanation": "B.Sc Life Sciences is best suited to students who bring curiosity and analytical thinking, strong number sense, clear, logical thinking, the ability to work independently, and the ability to adapt and learn quickly. This blend of strengths supports you in areas like Zoology, Botany, Genetics, where your curiosity and evidence-based thinking really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 35.0,
      "NUMERICAL": 20.0,
      "LOGICAL": 20.0,
      "LEARNING_VELOCITY": 10.0,
      "AUTONOMY_PREFERENCE": 15.0
    }
  },
  {
    "clusterHead": "Engg, Tech & Pure Science",
    "mainStream": "Pure Sciences",
    "subStream": "B.Sc Statistics",
    "specialisations": "Statistics",
    "eligibility": "Maths required",
    "keyExams": "CUET UG, ISI Admission Test, INSPIRE Scholarship",
    "explanation": "B.Sc Statistics is best suited to students who bring curiosity and analytical thinking, strong number sense, clear, logical thinking, the ability to work independently, and the ability to adapt and learn quickly. This blend of strengths supports you in areas like Statistics, where your curiosity and evidence-based thinking really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 35.0,
      "NUMERICAL": 20.0,
      "LOGICAL": 20.0,
      "LEARNING_VELOCITY": 10.0,
      "AUTONOMY_PREFERENCE": 15.0
    }
  },
  {
    "clusterHead": "Engg, Tech & Pure Science",
    "mainStream": "Pure Sciences",
    "subStream": "B.Sc Data Science",
    "specialisations": "Data Science, AI",
    "eligibility": "Maths preferred",
    "keyExams": "CUET UG, ISI Admission Test, INSPIRE Scholarship, Scaler Admission Test",
    "explanation": "B.Sc Data Science is best suited to students who bring curiosity and analytical thinking, strong number sense, clear, logical thinking, the ability to work independently, and the ability to adapt and learn quickly. This blend of strengths supports you in areas like Data Science, AI, where your curiosity and evidence-based thinking really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 35.0,
      "NUMERICAL": 20.0,
      "LOGICAL": 20.0,
      "LEARNING_VELOCITY": 10.0,
      "AUTONOMY_PREFERENCE": 15.0
    }
  },
  {
    "clusterHead": "Engg, Tech & Pure Science",
    "mainStream": "Pure Sciences",
    "subStream": "Integrated M.Sc",
    "specialisations": "Science disciplines",
    "eligibility": "PCM / PCB",
    "keyExams": "IISER Aptitude Test, IISER Aptitude Test (SCB Channel), NEST, CUET UG, INSPIRE Scholarship",
    "explanation": "Integrated M.Sc is best suited to students who bring curiosity and analytical thinking, strong number sense, clear, logical thinking, the ability to work independently, and the ability to adapt and learn quickly. This blend of strengths supports you in areas like Science disciplines, where your curiosity and evidence-based thinking really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 35.0,
      "NUMERICAL": 20.0,
      "LOGICAL": 20.0,
      "LEARNING_VELOCITY": 10.0,
      "AUTONOMY_PREFERENCE": 15.0
    }
  },
  {
    "clusterHead": "Engg, Tech & Pure Science",
    "mainStream": "Agriculture & Environmental Sciences",
    "subStream": "B.Sc Agriculture",
    "specialisations": "Agriculture",
    "eligibility": "PCB / PCM",
    "keyExams": "ICAR AIEEA UG, CUET UG",
    "explanation": "B.Sc Agriculture is best suited to students who bring practical, hands-on skill, curiosity and analytical thinking, discipline and reliability, clear, logical thinking, and the ability to adapt and learn quickly. This blend of strengths supports you in areas like Agriculture, where your hands-on, practical approach really makes the difference.",
    "weights": {
      "REALISTIC": 30.0,
      "INVESTIGATIVE": 25.0,
      "CONSCIENTIOUSNESS": 20.0,
      "LOGICAL": 15.0,
      "LEARNING_VELOCITY": 10.0
    }
  },
  {
    "clusterHead": "Engg, Tech & Pure Science",
    "mainStream": "Agriculture & Environmental Sciences",
    "subStream": "Forestry",
    "specialisations": "Forestry",
    "eligibility": "PCB / PCM",
    "keyExams": "ICAR AIEEA UG, CUET UG",
    "explanation": "Forestry is best suited to students who bring practical, hands-on skill, curiosity and analytical thinking, discipline and reliability, clear, logical thinking, and the ability to adapt and learn quickly. This blend of strengths supports you in areas like Forestry, where your hands-on, practical approach really makes the difference.",
    "weights": {
      "REALISTIC": 30.0,
      "INVESTIGATIVE": 25.0,
      "CONSCIENTIOUSNESS": 20.0,
      "LOGICAL": 15.0,
      "LEARNING_VELOCITY": 10.0
    }
  },
  {
    "clusterHead": "Engg, Tech & Pure Science",
    "mainStream": "Agriculture & Environmental Sciences",
    "subStream": "Environmental Science",
    "specialisations": "Sustainability",
    "eligibility": "Science preferred",
    "keyExams": "CUET UG",
    "explanation": "Environmental Science is best suited to students who bring practical, hands-on skill, curiosity and analytical thinking, discipline and reliability, clear, logical thinking, and the ability to adapt and learn quickly. This blend of strengths supports you in areas like Sustainability, where your hands-on, practical approach really makes the difference.",
    "weights": {
      "REALISTIC": 30.0,
      "INVESTIGATIVE": 25.0,
      "CONSCIENTIOUSNESS": 20.0,
      "LOGICAL": 15.0,
      "LEARNING_VELOCITY": 10.0
    }
  },
  {
    "clusterHead": "Engg, Tech & Pure Science",
    "mainStream": "Agriculture & Environmental Sciences",
    "subStream": "Food Technology",
    "specialisations": "Food Processing",
    "eligibility": "PCM / PCB",
    "keyExams": "ICAR AIEEA UG, AUEET, CUET UG",
    "explanation": "Food Technology is best suited to students who bring practical, hands-on skill, curiosity and analytical thinking, discipline and reliability, clear, logical thinking, and the ability to adapt and learn quickly. This blend of strengths supports you in areas like Food Processing, where your hands-on, practical approach really makes the difference.",
    "weights": {
      "REALISTIC": 30.0,
      "INVESTIGATIVE": 25.0,
      "CONSCIENTIOUSNESS": 20.0,
      "LOGICAL": 15.0,
      "LEARNING_VELOCITY": 10.0
    }
  },
  {
    "clusterHead": "Engg, Tech & Pure Science",
    "mainStream": "Defence & Security",
    "subStream": "NDA Pathway",
    "specialisations": "Army, Navy, Air Force",
    "eligibility": "PCM for Air Force/Navy",
    "keyExams": "NDA Exam, Indian Navy SSR / AA, Indian Air Force Agniveer",
    "explanation": "NDA Pathway is best suited to students who bring practical, hands-on skill, discipline and reliability, calmness and emotional balance, clear, logical thinking, and the ability to work independently. This blend of strengths supports you in areas like Army, Navy, Air Force, where your hands-on, practical approach really makes the difference.",
    "weights": {
      "REALISTIC": 30.0,
      "CONSCIENTIOUSNESS": 25.0,
      "EMOTIONAL_STABILITY": 25.0,
      "LOGICAL": 15.0,
      "AUTONOMY_PREFERENCE": 5.0
    }
  },
  {
    "clusterHead": "Engg, Tech & Pure Science",
    "mainStream": "Defence & Security",
    "subStream": "B.Sc Nautical Science",
    "specialisations": "Marine",
    "eligibility": "PCM",
    "keyExams": "IMU CET, TMISAT, DG Shipping DNS Exam, Indian Navy SSR / AA",
    "explanation": "B.Sc Nautical Science is best suited to students who bring practical, hands-on skill, discipline and reliability, calmness and emotional balance, clear, logical thinking, and the ability to work independently. This blend of strengths supports you in areas like Marine, where your hands-on, practical approach really makes the difference.",
    "weights": {
      "REALISTIC": 30.0,
      "CONSCIENTIOUSNESS": 25.0,
      "EMOTIONAL_STABILITY": 25.0,
      "LOGICAL": 15.0,
      "AUTONOMY_PREFERENCE": 5.0
    }
  },
  {
    "clusterHead": "Engg, Tech & Pure Science",
    "mainStream": "Defence & Security",
    "subStream": "Fire & Safety",
    "specialisations": "Industrial Safety",
    "eligibility": "Science preferred",
    "keyExams": "No dedicated national/institute entrance exam identified — admission is typically merit- or interview-based",
    "explanation": "Fire & Safety is best suited to students who bring practical, hands-on skill, discipline and reliability, calmness and emotional balance, clear, logical thinking, and the ability to work independently. This blend of strengths supports you in areas like Industrial Safety, where your hands-on, practical approach really makes the difference.",
    "weights": {
      "REALISTIC": 30.0,
      "CONSCIENTIOUSNESS": 25.0,
      "EMOTIONAL_STABILITY": 25.0,
      "LOGICAL": 15.0,
      "AUTONOMY_PREFERENCE": 5.0
    }
  },
  {
    "clusterHead": "Medical",
    "mainStream": "Medical & Allied Health Sciences",
    "subStream": "MBBS",
    "specialisations": "Medicine",
    "eligibility": "PCB",
    "keyExams": "NEET UG",
    "explanation": "MBBS is best suited to students who bring curiosity and analytical thinking, discipline and reliability, empathy and people skills, warmth and cooperation, and calmness and emotional balance. This blend of strengths supports you in areas like Medicine, where your curiosity and evidence-based thinking really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 25.0,
      "SOCIAL": 20.0,
      "CONSCIENTIOUSNESS": 25.0,
      "AGREEABLENESS": 20.0,
      "EMOTIONAL_STABILITY": 10.0
    }
  },
  {
    "clusterHead": "Medical",
    "mainStream": "Medical & Allied Health Sciences",
    "subStream": "BDS",
    "specialisations": "Dentistry",
    "eligibility": "PCB",
    "keyExams": "NEET UG",
    "explanation": "BDS is best suited to students who bring curiosity and analytical thinking, discipline and reliability, empathy and people skills, warmth and cooperation, and calmness and emotional balance. This blend of strengths supports you in areas like Dentistry, where your curiosity and evidence-based thinking really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 25.0,
      "SOCIAL": 20.0,
      "CONSCIENTIOUSNESS": 25.0,
      "AGREEABLENESS": 20.0,
      "EMOTIONAL_STABILITY": 10.0
    }
  },
  {
    "clusterHead": "Medical",
    "mainStream": "Medical & Allied Health Sciences",
    "subStream": "BAMS",
    "specialisations": "Ayurveda",
    "eligibility": "PCB",
    "keyExams": "NEET UG",
    "explanation": "BAMS is best suited to students who bring curiosity and analytical thinking, discipline and reliability, empathy and people skills, warmth and cooperation, and calmness and emotional balance. This blend of strengths supports you in areas like Ayurveda, where your curiosity and evidence-based thinking really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 25.0,
      "SOCIAL": 20.0,
      "CONSCIENTIOUSNESS": 25.0,
      "AGREEABLENESS": 20.0,
      "EMOTIONAL_STABILITY": 10.0
    }
  },
  {
    "clusterHead": "Medical",
    "mainStream": "Medical & Allied Health Sciences",
    "subStream": "BHMS",
    "specialisations": "Homeopathy",
    "eligibility": "PCB",
    "keyExams": "NEET UG",
    "explanation": "BHMS is best suited to students who bring curiosity and analytical thinking, discipline and reliability, empathy and people skills, warmth and cooperation, and calmness and emotional balance. This blend of strengths supports you in areas like Homeopathy, where your curiosity and evidence-based thinking really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 25.0,
      "SOCIAL": 20.0,
      "CONSCIENTIOUSNESS": 25.0,
      "AGREEABLENESS": 20.0,
      "EMOTIONAL_STABILITY": 10.0
    }
  },
  {
    "clusterHead": "Medical",
    "mainStream": "Medical & Allied Health Sciences",
    "subStream": "BPT",
    "specialisations": "Physiotherapy",
    "eligibility": "PCB",
    "keyExams": "AIIMS Paramedical, JIPMER Paramedical, SRIHER Entrance Exam, CUET UG",
    "explanation": "BPT is best suited to students who bring curiosity and analytical thinking, discipline and reliability, empathy and people skills, warmth and cooperation, and calmness and emotional balance. This blend of strengths supports you in areas like Physiotherapy, where your curiosity and evidence-based thinking really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 25.0,
      "SOCIAL": 20.0,
      "CONSCIENTIOUSNESS": 25.0,
      "AGREEABLENESS": 20.0,
      "EMOTIONAL_STABILITY": 10.0
    }
  },
  {
    "clusterHead": "Medical",
    "mainStream": "Medical & Allied Health Sciences",
    "subStream": "B.Sc Nursing",
    "specialisations": "Nursing",
    "eligibility": "PCB",
    "keyExams": "NEET UG, AIIMS Paramedical, JIPMER Paramedical, SRIHER Entrance Exam",
    "explanation": "B.Sc Nursing is best suited to students who bring curiosity and analytical thinking, discipline and reliability, empathy and people skills, warmth and cooperation, and calmness and emotional balance. This blend of strengths supports you in areas like Nursing, where your curiosity and evidence-based thinking really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 25.0,
      "SOCIAL": 20.0,
      "CONSCIENTIOUSNESS": 25.0,
      "AGREEABLENESS": 20.0,
      "EMOTIONAL_STABILITY": 10.0
    }
  },
  {
    "clusterHead": "Medical",
    "mainStream": "Medical & Allied Health Sciences",
    "subStream": "BOT",
    "specialisations": "Occupational Therapy",
    "eligibility": "PCB",
    "keyExams": "AIIMS Paramedical, JIPMER Paramedical, SRIHER Entrance Exam",
    "explanation": "BOT is best suited to students who bring curiosity and analytical thinking, discipline and reliability, empathy and people skills, warmth and cooperation, and calmness and emotional balance. This blend of strengths supports you in areas like Occupational Therapy, where your curiosity and evidence-based thinking really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 25.0,
      "SOCIAL": 20.0,
      "CONSCIENTIOUSNESS": 25.0,
      "AGREEABLENESS": 20.0,
      "EMOTIONAL_STABILITY": 10.0
    }
  },
  {
    "clusterHead": "Medical",
    "mainStream": "Medical & Allied Health Sciences",
    "subStream": "BMLT",
    "specialisations": "Medical Lab Technology",
    "eligibility": "PCB",
    "keyExams": "AIIMS Paramedical, JIPMER Paramedical, SRIHER Entrance Exam",
    "explanation": "BMLT is best suited to students who bring curiosity and analytical thinking, discipline and reliability, empathy and people skills, warmth and cooperation, and calmness and emotional balance. This blend of strengths supports you in areas like Medical Lab Technology, where your curiosity and evidence-based thinking really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 25.0,
      "SOCIAL": 20.0,
      "CONSCIENTIOUSNESS": 25.0,
      "AGREEABLENESS": 20.0,
      "EMOTIONAL_STABILITY": 10.0
    }
  },
  {
    "clusterHead": "Medical",
    "mainStream": "Medical & Allied Health Sciences",
    "subStream": "B.Pharm",
    "specialisations": "Pharmacy",
    "eligibility": "PCB / PCM",
    "keyExams": "KCET, MHT-CET, WBJEE, KEAM, BITSAT, MET (Manipal), GAT (GITAM)",
    "explanation": "B.Pharm is best suited to students who bring curiosity and analytical thinking, discipline and reliability, empathy and people skills, warmth and cooperation, and calmness and emotional balance. This blend of strengths supports you in areas like Pharmacy, where your curiosity and evidence-based thinking really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 25.0,
      "SOCIAL": 20.0,
      "CONSCIENTIOUSNESS": 25.0,
      "AGREEABLENESS": 20.0,
      "EMOTIONAL_STABILITY": 10.0
    }
  },
  {
    "clusterHead": "Medical",
    "mainStream": "Medical & Allied Health Sciences",
    "subStream": "Veterinary Science (BVSc)",
    "specialisations": "Veterinary Medicine",
    "eligibility": "PCB",
    "keyExams": "NEET UG, ICAR AIEEA UG",
    "explanation": "Veterinary Science (BVSc) is best suited to students who bring curiosity and analytical thinking, discipline and reliability, empathy and people skills, warmth and cooperation, and calmness and emotional balance. This blend of strengths supports you in areas like Veterinary Medicine, where your curiosity and evidence-based thinking really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 25.0,
      "SOCIAL": 20.0,
      "CONSCIENTIOUSNESS": 25.0,
      "AGREEABLENESS": 20.0,
      "EMOTIONAL_STABILITY": 10.0
    }
  },
  {
    "clusterHead": "Finance & Law",
    "mainStream": "Commerce & Finance",
    "subStream": "B.Com",
    "specialisations": "General, Taxation, Finance",
    "eligibility": "Any stream",
    "keyExams": "CUET UG",
    "explanation": "B.Com is best suited to students who bring confidence and initiative, strong number sense, discipline and reliability, organization and attention to detail, and clear, logical thinking. This blend of strengths supports you in areas like General, Taxation, Finance, where your confidence, initiative and leadership really makes the difference.",
    "weights": {
      "ENTERPRISING": 30.0,
      "CONVENTIONAL": 15.0,
      "CONSCIENTIOUSNESS": 20.0,
      "NUMERICAL": 25.0,
      "LOGICAL": 10.0
    }
  },
  {
    "clusterHead": "Finance & Law",
    "mainStream": "Commerce & Finance",
    "subStream": "B.Com Honours",
    "specialisations": "Advanced Commerce",
    "eligibility": "Commerce preferred",
    "keyExams": "CUET UG, DU JAT",
    "explanation": "B.Com Honours is best suited to students who bring confidence and initiative, strong number sense, discipline and reliability, organization and attention to detail, and clear, logical thinking. This blend of strengths supports you in areas like Advanced Commerce, where your confidence, initiative and leadership really makes the difference.",
    "weights": {
      "ENTERPRISING": 30.0,
      "CONVENTIONAL": 15.0,
      "CONSCIENTIOUSNESS": 20.0,
      "NUMERICAL": 25.0,
      "LOGICAL": 10.0
    }
  },
  {
    "clusterHead": "Finance & Law",
    "mainStream": "Commerce & Finance",
    "subStream": "BBA",
    "specialisations": "Business Administration",
    "eligibility": "Any stream",
    "keyExams": "CUET UG, NPAT, Symbiosis SET, Christ University Entrance Test, IPMAT, FLAME Entrance Exam, WAT, LPUNEST, PESSAT, JET, UPESEAT, SUAT, MRNAT, GUAT, AUAT, CUCET (Chandigarh Univ.), KIITEE, RVU Admission Process, Presidency PUCET, GAT (GITAM), BU-CET, SPJET, IUCET",
    "explanation": "BBA is best suited to students who bring confidence and initiative, strong number sense, discipline and reliability, organization and attention to detail, and clear, logical thinking. This blend of strengths supports you in areas like Business Administration, where your confidence, initiative and leadership really makes the difference.",
    "weights": {
      "ENTERPRISING": 30.0,
      "CONVENTIONAL": 15.0,
      "CONSCIENTIOUSNESS": 20.0,
      "NUMERICAL": 25.0,
      "LOGICAL": 10.0
    }
  },
  {
    "clusterHead": "Finance & Law",
    "mainStream": "Commerce & Finance",
    "subStream": "BMS",
    "specialisations": "Management Studies",
    "eligibility": "Any stream",
    "keyExams": "DU JAT, CUET UG",
    "explanation": "BMS is best suited to students who bring confidence and initiative, strong number sense, discipline and reliability, organization and attention to detail, and clear, logical thinking. This blend of strengths supports you in areas like Management Studies, where your confidence, initiative and leadership really makes the difference.",
    "weights": {
      "ENTERPRISING": 30.0,
      "CONVENTIONAL": 15.0,
      "CONSCIENTIOUSNESS": 20.0,
      "NUMERICAL": 25.0,
      "LOGICAL": 10.0
    }
  },
  {
    "clusterHead": "Finance & Law",
    "mainStream": "Commerce & Finance",
    "subStream": "BAF",
    "specialisations": "Accounting & Finance",
    "eligibility": "Commerce preferred",
    "keyExams": "CUET UG",
    "explanation": "BAF is best suited to students who bring confidence and initiative, strong number sense, discipline and reliability, organization and attention to detail, and clear, logical thinking. This blend of strengths supports you in areas like Accounting & Finance, where your confidence, initiative and leadership really makes the difference.",
    "weights": {
      "ENTERPRISING": 30.0,
      "CONVENTIONAL": 15.0,
      "CONSCIENTIOUSNESS": 20.0,
      "NUMERICAL": 25.0,
      "LOGICAL": 10.0
    }
  },
  {
    "clusterHead": "Finance & Law",
    "mainStream": "Commerce & Finance",
    "subStream": "BFM",
    "specialisations": "Financial Markets",
    "eligibility": "Commerce / Maths",
    "keyExams": "CUET UG",
    "explanation": "BFM is best suited to students who bring confidence and initiative, strong number sense, discipline and reliability, organization and attention to detail, and clear, logical thinking. This blend of strengths supports you in areas like Financial Markets, where your confidence, initiative and leadership really makes the difference.",
    "weights": {
      "ENTERPRISING": 30.0,
      "CONVENTIONAL": 15.0,
      "CONSCIENTIOUSNESS": 20.0,
      "NUMERICAL": 25.0,
      "LOGICAL": 10.0
    }
  },
  {
    "clusterHead": "Finance & Law",
    "mainStream": "Commerce & Finance",
    "subStream": "BBI",
    "specialisations": "Banking & Insurance",
    "eligibility": "Commerce",
    "keyExams": "CUET UG",
    "explanation": "BBI is best suited to students who bring confidence and initiative, strong number sense, discipline and reliability, organization and attention to detail, and clear, logical thinking. This blend of strengths supports you in areas like Banking & Insurance, where your confidence, initiative and leadership really makes the difference.",
    "weights": {
      "ENTERPRISING": 30.0,
      "CONVENTIONAL": 15.0,
      "CONSCIENTIOUSNESS": 20.0,
      "NUMERICAL": 25.0,
      "LOGICAL": 10.0
    }
  },
  {
    "clusterHead": "Finance & Law",
    "mainStream": "Commerce & Finance",
    "subStream": "Actuarial Science",
    "specialisations": "Risk Analysis",
    "eligibility": "Maths preferred",
    "keyExams": "CUET UG, ISI Admission Test",
    "explanation": "Actuarial Science is best suited to students who bring confidence and initiative, strong number sense, discipline and reliability, organization and attention to detail, and clear, logical thinking. This blend of strengths supports you in areas like Risk Analysis, where your confidence, initiative and leadership really makes the difference.",
    "weights": {
      "ENTERPRISING": 30.0,
      "CONVENTIONAL": 15.0,
      "CONSCIENTIOUSNESS": 20.0,
      "NUMERICAL": 25.0,
      "LOGICAL": 10.0
    }
  },
  {
    "clusterHead": "Finance & Law",
    "mainStream": "Commerce & Finance",
    "subStream": "Economics Honours",
    "specialisations": "Economics",
    "eligibility": "Maths preferred",
    "keyExams": "CUET UG, GIPE Admission, Ashoka Aptitude Test, Christ University Entrance Test",
    "explanation": "Economics Honours is best suited to students who bring confidence and initiative, strong number sense, discipline and reliability, organization and attention to detail, and clear, logical thinking. This blend of strengths supports you in areas like Economics, where your confidence, initiative and leadership really makes the difference.",
    "weights": {
      "ENTERPRISING": 30.0,
      "CONVENTIONAL": 15.0,
      "CONSCIENTIOUSNESS": 20.0,
      "NUMERICAL": 25.0,
      "LOGICAL": 10.0
    }
  },
  {
    "clusterHead": "Finance & Law",
    "mainStream": "Law",
    "subStream": "Integrated Law Programs",
    "specialisations": "BA LLB, BBA LLB, B.Com LLB",
    "eligibility": "Any stream",
    "keyExams": "CLAT, AILET, SLAT, LSAT India, Christ University Entrance Test, JSAT-Law, BU-CET, LPUNEST, UPESEAT, SUAT, AUAT, NFSU Entrance Test, RRUCET",
    "explanation": "Integrated Law Programs is best suited to students who bring strong verbal and language skills, curiosity and analytical thinking, discipline and reliability, clear, logical thinking, and calmness and emotional balance. This blend of strengths supports you in areas like BA LLB, BBA LLB, B.Com LLB, where your strong verbal and language skills really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 25.0,
      "CONSCIENTIOUSNESS": 15.0,
      "EMOTIONAL_STABILITY": 10.0,
      "VERBAL": 35.0,
      "LOGICAL": 15.0
    }
  },
  {
    "clusterHead": "Finance & Law",
    "mainStream": "Law",
    "subStream": "LLB (3 year)",
    "specialisations": "Law",
    "eligibility": "After graduation",
    "keyExams": "CLAT, LSAT India",
    "explanation": "LLB (3 year) is best suited to students who bring strong verbal and language skills, curiosity and analytical thinking, discipline and reliability, clear, logical thinking, and calmness and emotional balance. This blend of strengths supports you in areas like Law, where your strong verbal and language skills really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 25.0,
      "CONSCIENTIOUSNESS": 15.0,
      "EMOTIONAL_STABILITY": 10.0,
      "VERBAL": 35.0,
      "LOGICAL": 15.0
    }
  },
  {
    "clusterHead": "Humanities",
    "mainStream": "Humanities & Social Sciences",
    "subStream": "BA",
    "specialisations": "History, Political Science, Sociology",
    "eligibility": "Any stream",
    "keyExams": "CUET UG, Ashoka Aptitude Test, FLAME Entrance Exam, Symbiosis SET, TISS BAT, Christ University Entrance Test, APU NET, KAT, Sai University Admission Process",
    "explanation": "BA is best suited to students who bring strong verbal and language skills, empathy and people skills, curiosity and openness to new ideas, warmth and cooperation, and the ability to work independently. This blend of strengths supports you in areas like History, Political Science, Sociology, where your strong verbal and language skills really makes the difference.",
    "weights": {
      "SOCIAL": 25.0,
      "OPENNESS": 20.0,
      "AGREEABLENESS": 15.0,
      "VERBAL": 30.0,
      "AUTONOMY_PREFERENCE": 10.0
    }
  },
  {
    "clusterHead": "Humanities",
    "mainStream": "Humanities & Social Sciences",
    "subStream": "BA Psychology",
    "specialisations": "Psychology",
    "eligibility": "Any stream",
    "keyExams": "CUET UG, Symbiosis SET, Christ University Entrance Test, Ashoka Aptitude Test, FLAME Entrance Exam, APU NET",
    "explanation": "BA Psychology is best suited to students who bring strong verbal and language skills, empathy and people skills, curiosity and openness to new ideas, warmth and cooperation, and the ability to work independently. This blend of strengths supports you in areas like Psychology, where your strong verbal and language skills really makes the difference.",
    "weights": {
      "SOCIAL": 25.0,
      "OPENNESS": 20.0,
      "AGREEABLENESS": 15.0,
      "VERBAL": 30.0,
      "AUTONOMY_PREFERENCE": 10.0
    }
  },
  {
    "clusterHead": "Humanities",
    "mainStream": "Humanities & Social Sciences",
    "subStream": "BA Economics",
    "specialisations": "Economics",
    "eligibility": "Maths preferred",
    "keyExams": "CUET UG, GIPE Admission, Ashoka Aptitude Test, Christ University Entrance Test, KAT",
    "explanation": "BA Economics is best suited to students who bring strong verbal and language skills, empathy and people skills, curiosity and openness to new ideas, warmth and cooperation, and the ability to work independently. This blend of strengths supports you in areas like Economics, where your strong verbal and language skills really makes the difference.",
    "weights": {
      "SOCIAL": 25.0,
      "OPENNESS": 20.0,
      "AGREEABLENESS": 15.0,
      "VERBAL": 30.0,
      "AUTONOMY_PREFERENCE": 10.0
    }
  },
  {
    "clusterHead": "Humanities",
    "mainStream": "Humanities & Social Sciences",
    "subStream": "BA English",
    "specialisations": "Literature, Communication",
    "eligibility": "Any stream",
    "keyExams": "CUET UG, Christ University Entrance Test, Ashoka Aptitude Test, FLAME Entrance Exam",
    "explanation": "BA English is best suited to students who bring strong verbal and language skills, empathy and people skills, curiosity and openness to new ideas, warmth and cooperation, and the ability to work independently. This blend of strengths supports you in areas like Literature, Communication, where your strong verbal and language skills really makes the difference.",
    "weights": {
      "SOCIAL": 25.0,
      "OPENNESS": 20.0,
      "AGREEABLENESS": 15.0,
      "VERBAL": 30.0,
      "AUTONOMY_PREFERENCE": 10.0
    }
  },
  {
    "clusterHead": "Humanities",
    "mainStream": "Humanities & Social Sciences",
    "subStream": "BA Journalism",
    "specialisations": "Journalism, Media",
    "eligibility": "Any stream",
    "keyExams": "CUET UG, Christ University Entrance Test, MECAT, JMI Entrance Exam",
    "explanation": "BA Journalism is best suited to students who bring strong verbal and language skills, empathy and people skills, curiosity and openness to new ideas, warmth and cooperation, and the ability to work independently. This blend of strengths supports you in areas like Journalism, Media, where your strong verbal and language skills really makes the difference.",
    "weights": {
      "SOCIAL": 25.0,
      "OPENNESS": 20.0,
      "AGREEABLENESS": 15.0,
      "VERBAL": 30.0,
      "AUTONOMY_PREFERENCE": 10.0
    }
  },
  {
    "clusterHead": "Humanities",
    "mainStream": "Humanities & Social Sciences",
    "subStream": "BA Sociology",
    "specialisations": "Sociology",
    "eligibility": "Any stream",
    "keyExams": "CUET UG, TISS BAT, Christ University Entrance Test",
    "explanation": "BA Sociology is best suited to students who bring strong verbal and language skills, empathy and people skills, curiosity and openness to new ideas, warmth and cooperation, and the ability to work independently. This blend of strengths supports you in areas like Sociology, where your strong verbal and language skills really makes the difference.",
    "weights": {
      "SOCIAL": 25.0,
      "OPENNESS": 20.0,
      "AGREEABLENESS": 15.0,
      "VERBAL": 30.0,
      "AUTONOMY_PREFERENCE": 10.0
    }
  },
  {
    "clusterHead": "Humanities",
    "mainStream": "Humanities & Social Sciences",
    "subStream": "BA Public Policy",
    "specialisations": "Governance",
    "eligibility": "Any stream",
    "keyExams": "CUET UG, Ashoka Aptitude Test, APU NET",
    "explanation": "BA Public Policy is best suited to students who bring strong verbal and language skills, empathy and people skills, curiosity and openness to new ideas, warmth and cooperation, and the ability to work independently. This blend of strengths supports you in areas like Governance, where your strong verbal and language skills really makes the difference.",
    "weights": {
      "SOCIAL": 25.0,
      "OPENNESS": 20.0,
      "AGREEABLENESS": 15.0,
      "VERBAL": 30.0,
      "AUTONOMY_PREFERENCE": 10.0
    }
  },
  {
    "clusterHead": "Humanities",
    "mainStream": "Humanities & Social Sciences",
    "subStream": "BA International Relations",
    "specialisations": "Diplomacy",
    "eligibility": "Any stream",
    "keyExams": "CUET UG, Ashoka Aptitude Test, Christ University Entrance Test",
    "explanation": "BA International Relations is best suited to students who bring strong verbal and language skills, empathy and people skills, curiosity and openness to new ideas, warmth and cooperation, and the ability to work independently. This blend of strengths supports you in areas like Diplomacy, where your strong verbal and language skills really makes the difference.",
    "weights": {
      "SOCIAL": 25.0,
      "OPENNESS": 20.0,
      "AGREEABLENESS": 15.0,
      "VERBAL": 30.0,
      "AUTONOMY_PREFERENCE": 10.0
    }
  },
  {
    "clusterHead": "Humanities",
    "mainStream": "Education & Teaching",
    "subStream": "Integrated B.Ed",
    "specialisations": "BA/B.Sc B.Ed",
    "eligibility": "Relevant stream",
    "keyExams": "CUET UG",
    "explanation": "Integrated B.Ed is best suited to students who bring empathy and people skills, strong verbal and language skills, warmth and cooperation, discipline and reliability, and calmness and emotional balance. This blend of strengths supports you in areas like BA/B.Sc B.Ed, where your empathy and ability to connect with people really makes the difference.",
    "weights": {
      "SOCIAL": 30.0,
      "CONSCIENTIOUSNESS": 15.0,
      "AGREEABLENESS": 20.0,
      "EMOTIONAL_STABILITY": 10.0,
      "VERBAL": 25.0
    }
  },
  {
    "clusterHead": "Humanities",
    "mainStream": "Education & Teaching",
    "subStream": "Elementary Education",
    "specialisations": "Education",
    "eligibility": "Any stream",
    "keyExams": "CUET UG",
    "explanation": "Elementary Education is best suited to students who bring empathy and people skills, strong verbal and language skills, warmth and cooperation, discipline and reliability, and calmness and emotional balance. This blend of strengths supports you in areas like Education, where your empathy and ability to connect with people really makes the difference.",
    "weights": {
      "SOCIAL": 30.0,
      "CONSCIENTIOUSNESS": 15.0,
      "AGREEABLENESS": 20.0,
      "EMOTIONAL_STABILITY": 10.0,
      "VERBAL": 25.0
    }
  },
  {
    "clusterHead": "Arts & Media",
    "mainStream": "Design, Fine Arts & Creative Fields",
    "subStream": "B.Des",
    "specialisations": "Fashion, Product, UI/UX",
    "eligibility": "Any stream",
    "keyExams": "NIFT Entrance Test, NID DAT, UCEED, SEED, ADEPT, SMEAT, WUDAT, ISDI Challenge, MITID DAT, ICAT Admission Process, KIITEE, LPUNEST, PESSAT, JET, UPESEAT, SUAT, MRNAT, GUAT, CUCET (Chandigarh Univ.), RVU Admission Process, Presidency PUCET, PAE",
    "explanation": "B.Des is best suited to students who bring creativity and original thinking, curiosity and openness to new ideas, strong visual and spatial thinking, discipline and reliability, and the ability to work independently. This blend of strengths supports you in areas like Fashion, Product, UI/UX, where your creativity and original ideas really makes the difference.",
    "weights": {
      "ARTISTIC": 35.0,
      "OPENNESS": 25.0,
      "CONSCIENTIOUSNESS": 10.0,
      "SPATIAL": 20.0,
      "AUTONOMY_PREFERENCE": 10.0
    }
  },
  {
    "clusterHead": "Arts & Media",
    "mainStream": "Design, Fine Arts & Creative Fields",
    "subStream": "BFA",
    "specialisations": "Fine Arts",
    "eligibility": "Any stream",
    "keyExams": "SMEAT, ICAT Admission Process, CUET UG",
    "explanation": "BFA is best suited to students who bring creativity and original thinking, curiosity and openness to new ideas, strong visual and spatial thinking, discipline and reliability, and the ability to work independently. This blend of strengths supports you in areas like Fine Arts, where your creativity and original ideas really makes the difference.",
    "weights": {
      "ARTISTIC": 35.0,
      "OPENNESS": 25.0,
      "CONSCIENTIOUSNESS": 10.0,
      "SPATIAL": 20.0,
      "AUTONOMY_PREFERENCE": 10.0
    }
  },
  {
    "clusterHead": "Arts & Media",
    "mainStream": "Design, Fine Arts & Creative Fields",
    "subStream": "Fashion Design",
    "specialisations": "Apparel, Textile",
    "eligibility": "Any stream",
    "keyExams": "NIFT Entrance Test, PAE",
    "explanation": "Fashion Design is best suited to students who bring creativity and original thinking, curiosity and openness to new ideas, strong visual and spatial thinking, discipline and reliability, and the ability to work independently. This blend of strengths supports you in areas like Apparel, Textile, where your creativity and original ideas really makes the difference.",
    "weights": {
      "ARTISTIC": 35.0,
      "OPENNESS": 25.0,
      "CONSCIENTIOUSNESS": 10.0,
      "SPATIAL": 20.0,
      "AUTONOMY_PREFERENCE": 10.0
    }
  },
  {
    "clusterHead": "Arts & Media",
    "mainStream": "Design, Fine Arts & Creative Fields",
    "subStream": "Animation & VFX",
    "specialisations": "Animation, Gaming",
    "eligibility": "Any stream",
    "keyExams": "ICAT Admission Process, MECAT, AAFT Admission Test",
    "explanation": "Animation & VFX is best suited to students who bring creativity and original thinking, curiosity and openness to new ideas, strong visual and spatial thinking, discipline and reliability, and the ability to work independently. This blend of strengths supports you in areas like Animation, Gaming, where your creativity and original ideas really makes the difference.",
    "weights": {
      "ARTISTIC": 35.0,
      "OPENNESS": 25.0,
      "CONSCIENTIOUSNESS": 10.0,
      "SPATIAL": 20.0,
      "AUTONOMY_PREFERENCE": 10.0
    }
  },
  {
    "clusterHead": "Arts & Media",
    "mainStream": "Design, Fine Arts & Creative Fields",
    "subStream": "Film Making",
    "specialisations": "Direction, Cinematography",
    "eligibility": "Any stream",
    "keyExams": "MECAT, AAFT Admission Test",
    "explanation": "Film Making is best suited to students who bring creativity and original thinking, curiosity and openness to new ideas, strong visual and spatial thinking, discipline and reliability, and the ability to work independently. This blend of strengths supports you in areas like Direction, Cinematography, where your creativity and original ideas really makes the difference.",
    "weights": {
      "ARTISTIC": 35.0,
      "OPENNESS": 25.0,
      "CONSCIENTIOUSNESS": 10.0,
      "SPATIAL": 20.0,
      "AUTONOMY_PREFERENCE": 10.0
    }
  },
  {
    "clusterHead": "Arts & Media",
    "mainStream": "Design, Fine Arts & Creative Fields",
    "subStream": "Interior Design",
    "specialisations": "Space Design",
    "eligibility": "Any stream",
    "keyExams": "CEPT Admission Process, Sushant School Admission Process, ICAT Admission Process",
    "explanation": "Interior Design is best suited to students who bring creativity and original thinking, curiosity and openness to new ideas, strong visual and spatial thinking, discipline and reliability, and the ability to work independently. This blend of strengths supports you in areas like Space Design, where your creativity and original ideas really makes the difference.",
    "weights": {
      "ARTISTIC": 35.0,
      "OPENNESS": 25.0,
      "CONSCIENTIOUSNESS": 10.0,
      "SPATIAL": 20.0,
      "AUTONOMY_PREFERENCE": 10.0
    }
  },
  {
    "clusterHead": "Arts & Media",
    "mainStream": "Media, Communication & Entertainment",
    "subStream": "BJMC",
    "specialisations": "Journalism & Mass Communication",
    "eligibility": "Any stream",
    "keyExams": "CUET UG, Christ University Entrance Test, MECAT, JMI Entrance Exam",
    "explanation": "BJMC is best suited to students who bring creativity and original thinking, strong verbal and language skills, curiosity and openness to new ideas, social energy and communication, and comfort with risk and uncertainty. This blend of strengths supports you in areas like Journalism & Mass Communication, where your creativity and original ideas really makes the difference.",
    "weights": {
      "ARTISTIC": 25.0,
      "OPENNESS": 20.0,
      "EXTRAVERSION": 20.0,
      "VERBAL": 25.0,
      "UNCERTAINTY_TOLERANCE": 10.0
    }
  },
  {
    "clusterHead": "Arts & Media",
    "mainStream": "Media, Communication & Entertainment",
    "subStream": "Mass Media",
    "specialisations": "Advertising, PR",
    "eligibility": "Any stream",
    "keyExams": "CUET UG, MECAT, AAFT Admission Test",
    "explanation": "Mass Media is best suited to students who bring creativity and original thinking, strong verbal and language skills, curiosity and openness to new ideas, social energy and communication, and comfort with risk and uncertainty. This blend of strengths supports you in areas like Advertising, PR, where your creativity and original ideas really makes the difference.",
    "weights": {
      "ARTISTIC": 25.0,
      "OPENNESS": 20.0,
      "EXTRAVERSION": 20.0,
      "VERBAL": 25.0,
      "UNCERTAINTY_TOLERANCE": 10.0
    }
  },
  {
    "clusterHead": "Arts & Media",
    "mainStream": "Media, Communication & Entertainment",
    "subStream": "Digital Media",
    "specialisations": "Content, Social Media",
    "eligibility": "Any stream",
    "keyExams": "MECAT, AAFT Admission Test, CUET UG",
    "explanation": "Digital Media is best suited to students who bring creativity and original thinking, strong verbal and language skills, curiosity and openness to new ideas, social energy and communication, and comfort with risk and uncertainty. This blend of strengths supports you in areas like Content, Social Media, where your creativity and original ideas really makes the difference.",
    "weights": {
      "ARTISTIC": 25.0,
      "OPENNESS": 20.0,
      "EXTRAVERSION": 20.0,
      "VERBAL": 25.0,
      "UNCERTAINTY_TOLERANCE": 10.0
    }
  },
  {
    "clusterHead": "Arts & Media",
    "mainStream": "Media, Communication & Entertainment",
    "subStream": "Event Management",
    "specialisations": "Events & PR",
    "eligibility": "Any stream",
    "keyExams": "CUET UG",
    "explanation": "Event Management is best suited to students who bring creativity and original thinking, strong verbal and language skills, curiosity and openness to new ideas, social energy and communication, and comfort with risk and uncertainty. This blend of strengths supports you in areas like Events & PR, where your creativity and original ideas really makes the difference.",
    "weights": {
      "ARTISTIC": 25.0,
      "OPENNESS": 20.0,
      "EXTRAVERSION": 20.0,
      "VERBAL": 25.0,
      "UNCERTAINTY_TOLERANCE": 10.0
    }
  },
  {
    "clusterHead": "Arts & Media",
    "mainStream": "Hospitality, Tourism & Aviation",
    "subStream": "BHM",
    "specialisations": "Hotel Management",
    "eligibility": "Any stream",
    "keyExams": "NCHM JEE, IIHM eCAT",
    "explanation": "BHM is best suited to students who bring empathy and people skills, social energy and communication, warmth and cooperation, calmness and emotional balance, and discipline and reliability. This blend of strengths supports you in areas like Hotel Management, where your empathy and ability to connect with people really makes the difference.",
    "weights": {
      "SOCIAL": 30.0,
      "CONSCIENTIOUSNESS": 10.0,
      "EXTRAVERSION": 25.0,
      "AGREEABLENESS": 20.0,
      "EMOTIONAL_STABILITY": 15.0
    }
  },
  {
    "clusterHead": "Arts & Media",
    "mainStream": "Hospitality, Tourism & Aviation",
    "subStream": "Tourism Studies",
    "specialisations": "Tourism & Travel",
    "eligibility": "Any stream",
    "keyExams": "CUET UG, IIHM eCAT",
    "explanation": "Tourism Studies is best suited to students who bring empathy and people skills, social energy and communication, warmth and cooperation, calmness and emotional balance, and discipline and reliability. This blend of strengths supports you in areas like Tourism & Travel, where your empathy and ability to connect with people really makes the difference.",
    "weights": {
      "SOCIAL": 30.0,
      "CONSCIENTIOUSNESS": 10.0,
      "EXTRAVERSION": 25.0,
      "AGREEABLENESS": 20.0,
      "EMOTIONAL_STABILITY": 15.0
    }
  },
  {
    "clusterHead": "Arts & Media",
    "mainStream": "Hospitality, Tourism & Aviation",
    "subStream": "Aviation Management",
    "specialisations": "Airline Operations",
    "eligibility": "Any stream",
    "keyExams": "UPESEAT",
    "explanation": "Aviation Management is best suited to students who bring empathy and people skills, social energy and communication, warmth and cooperation, calmness and emotional balance, and discipline and reliability. This blend of strengths supports you in areas like Airline Operations, where your empathy and ability to connect with people really makes the difference.",
    "weights": {
      "SOCIAL": 30.0,
      "CONSCIENTIOUSNESS": 10.0,
      "EXTRAVERSION": 25.0,
      "AGREEABLENESS": 20.0,
      "EMOTIONAL_STABILITY": 15.0
    }
  },
  {
    "clusterHead": "Arts & Media",
    "mainStream": "Hospitality, Tourism & Aviation",
    "subStream": "Cabin Crew Training",
    "specialisations": "Aviation Services",
    "eligibility": "Any stream",
    "keyExams": "No dedicated national/institute entrance exam identified — admission is typically merit- or interview-based",
    "explanation": "Cabin Crew Training is best suited to students who bring empathy and people skills, social energy and communication, warmth and cooperation, calmness and emotional balance, and discipline and reliability. This blend of strengths supports you in areas like Aviation Services, where your empathy and ability to connect with people really makes the difference.",
    "weights": {
      "SOCIAL": 30.0,
      "CONSCIENTIOUSNESS": 10.0,
      "EXTRAVERSION": 25.0,
      "AGREEABLENESS": 20.0,
      "EMOTIONAL_STABILITY": 15.0
    }
  },
  {
    "clusterHead": "Humanities",
    "mainStream": "Vocational & Skill-Based Degrees",
    "subStream": "Bachelor of Vocation (B.Voc)",
    "specialisations": "Retail, Logistics, Healthcare",
    "eligibility": "Any stream",
    "keyExams": "TISS BAT, CUET UG",
    "explanation": "Bachelor of Vocation (B.Voc) is best suited to students who bring practical, hands-on skill, discipline and reliability, the ability to adapt and learn quickly, organization and attention to detail, and clear, logical thinking. This blend of strengths supports you in areas like Retail, Logistics, Healthcare, where your hands-on, practical approach really makes the difference.",
    "weights": {
      "REALISTIC": 30.0,
      "CONVENTIONAL": 15.0,
      "CONSCIENTIOUSNESS": 25.0,
      "LOGICAL": 10.0,
      "LEARNING_VELOCITY": 20.0
    }
  },
  {
    "clusterHead": "Finance & Law",
    "mainStream": "Vocational & Skill-Based Degrees",
    "subStream": "Retail Management",
    "specialisations": "Retail Operations",
    "eligibility": "Any stream",
    "keyExams": "CUET UG",
    "explanation": "Retail Management is best suited to students who bring practical, hands-on skill, discipline and reliability, the ability to adapt and learn quickly, organization and attention to detail, and clear, logical thinking. This blend of strengths supports you in areas like Retail Operations, where your hands-on, practical approach really makes the difference.",
    "weights": {
      "REALISTIC": 30.0,
      "CONVENTIONAL": 15.0,
      "CONSCIENTIOUSNESS": 25.0,
      "LOGICAL": 10.0,
      "LEARNING_VELOCITY": 20.0
    }
  },
  {
    "clusterHead": "Finance & Law",
    "mainStream": "Vocational & Skill-Based Degrees",
    "subStream": "Logistics & Supply Chain",
    "specialisations": "SCM",
    "eligibility": "Any stream",
    "keyExams": "CUET UG",
    "explanation": "Logistics & Supply Chain is best suited to students who bring practical, hands-on skill, discipline and reliability, the ability to adapt and learn quickly, organization and attention to detail, and clear, logical thinking. This blend of strengths supports you in areas like SCM, where your hands-on, practical approach really makes the difference.",
    "weights": {
      "REALISTIC": 30.0,
      "CONVENTIONAL": 15.0,
      "CONSCIENTIOUSNESS": 25.0,
      "LOGICAL": 10.0,
      "LEARNING_VELOCITY": 20.0
    }
  },
  {
    "clusterHead": "Engg, Tech & Pure Science",
    "mainStream": "Vocational & Skill-Based Degrees",
    "subStream": "Automotive Technology",
    "specialisations": "Automobile",
    "eligibility": "PCM preferred",
    "keyExams": "CUET UG",
    "explanation": "Automotive Technology is best suited to students who bring practical, hands-on skill, discipline and reliability, the ability to adapt and learn quickly, organization and attention to detail, and clear, logical thinking. This blend of strengths supports you in areas like Automobile, where your hands-on, practical approach really makes the difference.",
    "weights": {
      "REALISTIC": 30.0,
      "CONVENTIONAL": 15.0,
      "CONSCIENTIOUSNESS": 25.0,
      "LOGICAL": 10.0,
      "LEARNING_VELOCITY": 20.0
    }
  },
  {
    "clusterHead": "Arts & Media",
    "mainStream": "Emerging Interdisciplinary Streams",
    "subStream": "Liberal Arts",
    "specialisations": "Multidisciplinary",
    "eligibility": "Any stream",
    "keyExams": "Ashoka Aptitude Test, FLAME Entrance Exam, Sai University Admission Process, CUET UG, KAT",
    "explanation": "Liberal Arts is best suited to students who bring curiosity and openness to new ideas, curiosity and analytical thinking, comfort with risk and uncertainty, the ability to adapt and learn quickly, and the ability to work independently. This blend of strengths supports you in areas like Multidisciplinary, where your openness to new ideas and perspectives really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 25.0,
      "OPENNESS": 30.0,
      "LEARNING_VELOCITY": 15.0,
      "UNCERTAINTY_TOLERANCE": 20.0,
      "AUTONOMY_PREFERENCE": 10.0
    }
  },
  {
    "clusterHead": "Humanities",
    "mainStream": "Emerging Interdisciplinary Streams",
    "subStream": "Cognitive Science",
    "specialisations": "Psychology + AI",
    "eligibility": "Science/Humanities",
    "keyExams": "CUET UG, Ashoka Aptitude Test",
    "explanation": "Cognitive Science is best suited to students who bring curiosity and openness to new ideas, curiosity and analytical thinking, comfort with risk and uncertainty, the ability to adapt and learn quickly, and the ability to work independently. This blend of strengths supports you in areas like Psychology + AI, where your openness to new ideas and perspectives really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 25.0,
      "OPENNESS": 30.0,
      "LEARNING_VELOCITY": 15.0,
      "UNCERTAINTY_TOLERANCE": 20.0,
      "AUTONOMY_PREFERENCE": 10.0
    }
  },
  {
    "clusterHead": "Finance & Law",
    "mainStream": "Emerging Interdisciplinary Streams",
    "subStream": "Behavioural Economics",
    "specialisations": "Economics + Psychology",
    "eligibility": "Maths preferred",
    "keyExams": "CUET UG, GIPE Admission, Ashoka Aptitude Test",
    "explanation": "Behavioural Economics is best suited to students who bring curiosity and openness to new ideas, curiosity and analytical thinking, comfort with risk and uncertainty, the ability to adapt and learn quickly, and the ability to work independently. This blend of strengths supports you in areas like Economics + Psychology, where your openness to new ideas and perspectives really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 25.0,
      "OPENNESS": 30.0,
      "LEARNING_VELOCITY": 15.0,
      "UNCERTAINTY_TOLERANCE": 20.0,
      "AUTONOMY_PREFERENCE": 10.0
    }
  },
  {
    "clusterHead": "Arts & Media",
    "mainStream": "Emerging Interdisciplinary Streams",
    "subStream": "Sports Management",
    "specialisations": "Sports Business",
    "eligibility": "Any stream",
    "keyExams": "CUET UG",
    "explanation": "Sports Management is best suited to students who bring curiosity and openness to new ideas, curiosity and analytical thinking, comfort with risk and uncertainty, the ability to adapt and learn quickly, and the ability to work independently. This blend of strengths supports you in areas like Sports Business, where your openness to new ideas and perspectives really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 25.0,
      "OPENNESS": 30.0,
      "LEARNING_VELOCITY": 15.0,
      "UNCERTAINTY_TOLERANCE": 20.0,
      "AUTONOMY_PREFERENCE": 10.0
    }
  },
  {
    "clusterHead": "Arts & Media",
    "mainStream": "Emerging Interdisciplinary Streams",
    "subStream": "Esports & Gaming",
    "specialisations": "Gaming Industry",
    "eligibility": "Any stream",
    "keyExams": "CUET UG, ICAT Admission Process",
    "explanation": "Esports & Gaming is best suited to students who bring curiosity and openness to new ideas, curiosity and analytical thinking, comfort with risk and uncertainty, the ability to adapt and learn quickly, and the ability to work independently. This blend of strengths supports you in areas like Gaming Industry, where your openness to new ideas and perspectives really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 25.0,
      "OPENNESS": 30.0,
      "LEARNING_VELOCITY": 15.0,
      "UNCERTAINTY_TOLERANCE": 20.0,
      "AUTONOMY_PREFERENCE": 10.0
    }
  },
  {
    "clusterHead": "Engg, Tech & Pure Science",
    "mainStream": "Emerging Interdisciplinary Streams",
    "subStream": "Sustainability Studies",
    "specialisations": "Climate & Policy",
    "eligibility": "Any stream",
    "keyExams": "CUET UG",
    "explanation": "Sustainability Studies is best suited to students who bring curiosity and openness to new ideas, curiosity and analytical thinking, comfort with risk and uncertainty, the ability to adapt and learn quickly, and the ability to work independently. This blend of strengths supports you in areas like Climate & Policy, where your openness to new ideas and perspectives really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 25.0,
      "OPENNESS": 30.0,
      "LEARNING_VELOCITY": 15.0,
      "UNCERTAINTY_TOLERANCE": 20.0,
      "AUTONOMY_PREFERENCE": 10.0
    }
  }
];
