// AUTO-GENERATED by scripts/export-assessment-scoring.py — do not edit by hand.
// Source: docs/Class 910_Traits  Weightages (1).xlsx

import type { StreamWeightEntry } from "./types.js";

export const streamWeights: StreamWeightEntry[] = [
  {
    "mainStream": "Science",
    "subStream": "PCM (Physics, Chemistry, Maths)",
    "coreSubjects": "Physics, Chemistry, Mathematics, English",
    "electiveSubjects": "Computer Science, Informatics Practices, Physical Education, Economics, Engineering Graphics",
    "explanation": "PCM (Physics, Chemistry, Maths) is best suited to students who bring curiosity and analytical thinking, clear, logical thinking, strong number sense, discipline and reliability, and the ability to adapt and learn quickly. This blend of strengths supports you in subjects like Physics, Chemistry, Mathematics, English, where your curiosity and evidence-based thinking really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 30.0,
      "CONSCIENTIOUSNESS": 15.0,
      "NUMERICAL": 20.0,
      "LOGICAL": 25.0,
      "LEARNING_VELOCITY": 10.0
    }
  },
  {
    "mainStream": "Science",
    "subStream": "PCB (Physics, Chemistry, Biology)",
    "coreSubjects": "Physics, Chemistry, Biology, English",
    "electiveSubjects": "Psychology, Physical Education, Biotechnology, Mathematics",
    "explanation": "PCB (Physics, Chemistry, Biology) is best suited to students who bring curiosity and analytical thinking, clear, logical thinking, the ability to adapt and learn quickly, discipline and reliability, and curiosity and openness to new ideas. This blend of strengths supports you in subjects like Physics, Chemistry, Biology, English, where your curiosity and evidence-based thinking really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 30.0,
      "OPENNESS": 10.0,
      "CONSCIENTIOUSNESS": 15.0,
      "LOGICAL": 25.0,
      "LEARNING_VELOCITY": 20.0
    }
  },
  {
    "mainStream": "Science",
    "subStream": "PCMB",
    "coreSubjects": "Physics, Chemistry, Mathematics, Biology",
    "electiveSubjects": "Computer Science, Psychology, Physical Education",
    "explanation": "PCMB is best suited to students who bring curiosity and analytical thinking, clear, logical thinking, strong number sense, the ability to adapt and learn quickly, and discipline and reliability. This blend of strengths supports you in subjects like Physics, Chemistry, Mathematics, Biology, where your curiosity and evidence-based thinking really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 30.0,
      "CONSCIENTIOUSNESS": 10.0,
      "NUMERICAL": 20.0,
      "LOGICAL": 25.0,
      "LEARNING_VELOCITY": 15.0
    }
  },
  {
    "mainStream": "Science",
    "subStream": "PCM + Computer Science",
    "coreSubjects": "Physics, Chemistry, Mathematics, Computer Science",
    "electiveSubjects": "Physical Education, Economics",
    "explanation": "PCM + Computer Science is best suited to students who bring clear, logical thinking, curiosity and analytical thinking, strong number sense, the ability to adapt and learn quickly, and the ability to work independently. This blend of strengths supports you in subjects like Physics, Chemistry, Mathematics, Computer Science, where your clear, logical thinking really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 25.0,
      "NUMERICAL": 20.0,
      "LOGICAL": 30.0,
      "LEARNING_VELOCITY": 15.0,
      "AUTONOMY_PREFERENCE": 10.0
    }
  },
  {
    "mainStream": "Science",
    "subStream": "PCM + Economics",
    "coreSubjects": "Physics, Chemistry, Mathematics, Economics",
    "electiveSubjects": "Computer Science",
    "explanation": "PCM + Economics is best suited to students who bring strong number sense, curiosity and analytical thinking, clear, logical thinking, discipline and reliability, and confidence and initiative. This blend of strengths supports you in subjects like Physics, Chemistry, Mathematics, Economics, where your strong number sense really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 25.0,
      "ENTERPRISING": 10.0,
      "CONSCIENTIOUSNESS": 15.0,
      "NUMERICAL": 30.0,
      "LOGICAL": 20.0
    }
  },
  {
    "mainStream": "Science",
    "subStream": "PCB + Psychology",
    "coreSubjects": "Physics, Chemistry, Biology, Psychology",
    "electiveSubjects": "Physical Education",
    "explanation": "PCB + Psychology is best suited to students who bring curiosity and analytical thinking, empathy and people skills, curiosity and openness to new ideas, warmth and cooperation, and clear, logical thinking. This blend of strengths supports you in subjects like Physics, Chemistry, Biology, Psychology, where your curiosity and evidence-based thinking really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 30.0,
      "SOCIAL": 20.0,
      "OPENNESS": 20.0,
      "AGREEABLENESS": 20.0,
      "LOGICAL": 10.0
    }
  },
  {
    "mainStream": "Commerce",
    "subStream": "Commerce with Maths",
    "coreSubjects": "Accountancy, Business Studies, Economics, Mathematics, English",
    "electiveSubjects": "Informatics Practices, Entrepreneurship",
    "explanation": "Commerce with Maths is best suited to students who bring confidence and initiative, strong number sense, discipline and reliability, curiosity and analytical thinking, and clear, logical thinking. This blend of strengths supports you in subjects like Accountancy, Business Studies, Economics, Mathematics, English, where your confidence, initiative and leadership really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 15.0,
      "ENTERPRISING": 30.0,
      "CONSCIENTIOUSNESS": 20.0,
      "NUMERICAL": 25.0,
      "LOGICAL": 10.0
    }
  },
  {
    "mainStream": "Commerce",
    "subStream": "Commerce without Maths",
    "coreSubjects": "Accountancy, Business Studies, Economics, English",
    "electiveSubjects": "Entrepreneurship, Marketing, Physical Education",
    "explanation": "Commerce without Maths is best suited to students who bring confidence and initiative, strong verbal and language skills, social energy and communication, discipline and reliability, and curiosity and analytical thinking. This blend of strengths supports you in subjects like Accountancy, Business Studies, Economics, English, where your confidence, initiative and leadership really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 10.0,
      "ENTERPRISING": 30.0,
      "CONSCIENTIOUSNESS": 15.0,
      "EXTRAVERSION": 20.0,
      "VERBAL": 25.0
    }
  },
  {
    "mainStream": "Commerce",
    "subStream": "Commerce + Informatics Practices",
    "coreSubjects": "Accountancy, Business Studies, Economics, IP",
    "electiveSubjects": "Mathematics, Entrepreneurship",
    "explanation": "Commerce + Informatics Practices is best suited to students who bring confidence and initiative, strong number sense, clear, logical thinking, the ability to adapt and learn quickly, and discipline and reliability. This blend of strengths supports you in subjects like Accountancy, Business Studies, Economics, IP, where your confidence, initiative and leadership really makes the difference.",
    "weights": {
      "ENTERPRISING": 25.0,
      "CONSCIENTIOUSNESS": 15.0,
      "NUMERICAL": 20.0,
      "LOGICAL": 20.0,
      "LEARNING_VELOCITY": 20.0
    }
  },
  {
    "mainStream": "Commerce",
    "subStream": "Commerce + Computer Science",
    "coreSubjects": "Accountancy, Economics, CS",
    "electiveSubjects": "Mathematics",
    "explanation": "Commerce + Computer Science is best suited to students who bring confidence and initiative, clear, logical thinking, curiosity and analytical thinking, strong number sense, and the ability to adapt and learn quickly. This blend of strengths supports you in subjects like Accountancy, Economics, CS, where your confidence, initiative and leadership really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 20.0,
      "ENTERPRISING": 25.0,
      "NUMERICAL": 20.0,
      "LOGICAL": 25.0,
      "LEARNING_VELOCITY": 10.0
    }
  },
  {
    "mainStream": "Humanities / Arts",
    "subStream": "Humanities with Economics",
    "coreSubjects": "History, Political Science, Economics, English",
    "electiveSubjects": "Psychology, Sociology",
    "explanation": "Humanities with Economics is best suited to students who bring strong verbal and language skills, curiosity and analytical thinking, strong number sense, curiosity and openness to new ideas, and discipline and reliability. This blend of strengths supports you in subjects like History, Political Science, Economics, English, where your strong verbal and language skills really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 25.0,
      "OPENNESS": 10.0,
      "CONSCIENTIOUSNESS": 10.0,
      "NUMERICAL": 20.0,
      "VERBAL": 35.0
    }
  },
  {
    "mainStream": "Humanities / Arts",
    "subStream": "Humanities with Psychology",
    "coreSubjects": "Psychology, Sociology, Political Science, English",
    "electiveSubjects": "Economics, Physical Education",
    "explanation": "Humanities with Psychology is best suited to students who bring empathy and people skills, curiosity and openness to new ideas, warmth and cooperation, strong verbal and language skills, and calmness and emotional balance. This blend of strengths supports you in subjects like Psychology, Sociology, Political Science, English, where your empathy and ability to connect with people really makes the difference.",
    "weights": {
      "SOCIAL": 25.0,
      "OPENNESS": 20.0,
      "AGREEABLENESS": 20.0,
      "EMOTIONAL_STABILITY": 15.0,
      "VERBAL": 20.0
    }
  },
  {
    "mainStream": "Humanities / Arts",
    "subStream": "Humanities with Maths",
    "coreSubjects": "Geography, Economics, Mathematics, English",
    "electiveSubjects": "Political Science",
    "explanation": "Humanities with Maths is best suited to students who bring strong number sense, curiosity and analytical thinking, clear, logical thinking, curiosity and openness to new ideas, and discipline and reliability. This blend of strengths supports you in subjects like Geography, Economics, Mathematics, English, where your strong number sense really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 25.0,
      "OPENNESS": 15.0,
      "CONSCIENTIOUSNESS": 10.0,
      "NUMERICAL": 30.0,
      "LOGICAL": 20.0
    }
  },
  {
    "mainStream": "Humanities / Arts",
    "subStream": "Humanities with Legal Studies",
    "coreSubjects": "Political Science, Legal Studies, History",
    "electiveSubjects": "Economics",
    "explanation": "Humanities with Legal Studies is best suited to students who bring strong verbal and language skills, curiosity and analytical thinking, clear, logical thinking, empathy and people skills, and discipline and reliability. This blend of strengths supports you in subjects like Political Science, Legal Studies, History, where your strong verbal and language skills really makes the difference.",
    "weights": {
      "INVESTIGATIVE": 20.0,
      "SOCIAL": 15.0,
      "CONSCIENTIOUSNESS": 15.0,
      "VERBAL": 30.0,
      "LOGICAL": 20.0
    }
  },
  {
    "mainStream": "Humanities / Arts",
    "subStream": "Humanities with Fine Arts",
    "coreSubjects": "Fine Arts, History, English",
    "electiveSubjects": "Psychology, Multimedia",
    "explanation": "Humanities with Fine Arts is best suited to students who bring creativity and original thinking, curiosity and openness to new ideas, strong visual and spatial thinking, the ability to work independently, and discipline and reliability. This blend of strengths supports you in subjects like Fine Arts, History, English, where your creativity and original ideas really makes the difference.",
    "weights": {
      "ARTISTIC": 35.0,
      "OPENNESS": 25.0,
      "CONSCIENTIOUSNESS": 10.0,
      "SPATIAL": 15.0,
      "AUTONOMY_PREFERENCE": 15.0
    }
  },
  {
    "mainStream": "Humanities / Arts",
    "subStream": "Humanities with Mass Media",
    "coreSubjects": "Political Science, Sociology, English",
    "electiveSubjects": "Multimedia, Psychology",
    "explanation": "Humanities with Mass Media is best suited to students who bring creativity and original thinking, strong verbal and language skills, social energy and communication, empathy and people skills, and curiosity and openness to new ideas. This blend of strengths supports you in subjects like Political Science, Sociology, English, where your creativity and original ideas really makes the difference.",
    "weights": {
      "ARTISTIC": 25.0,
      "SOCIAL": 15.0,
      "OPENNESS": 15.0,
      "EXTRAVERSION": 20.0,
      "VERBAL": 25.0
    }
  }
];
