// AUTO-GENERATED by scripts/export-assessment-scoring.py — do not edit by hand.
// Source: docs/Class 910_Traits  Weightages (1).xlsx

import type { TraitDefinition } from "./types.js";

export const traitDefinitions: TraitDefinition[] = [
  {
    "layer": "RIASEC",
    "key": "REALISTIC",
    "trait": "Realistic",
    "traitName": "Applied Thinker",
    "description": "Preference for practical, hands-on activities involving tools, machines, building, fixing, or physical problem solving."
  },
  {
    "layer": "RIASEC",
    "key": "INVESTIGATIVE",
    "trait": "Investigative",
    "traitName": "Analytical Explorer",
    "description": "Interest in analytical thinking, research, problem solving, scientific exploration, and understanding how things work."
  },
  {
    "layer": "RIASEC",
    "key": "ARTISTIC",
    "trait": "Artistic",
    "traitName": "Creative Thinker",
    "description": "Preference for creativity, imagination, self-expression, design, music, storytelling, or innovative thinking."
  },
  {
    "layer": "RIASEC",
    "key": "SOCIAL",
    "trait": "Social",
    "traitName": "Interpersonal Mindset",
    "description": "Interest in helping, teaching, guiding, supporting, and positively interacting with people."
  },
  {
    "layer": "RIASEC",
    "key": "ENTERPRISING",
    "trait": "Enterprising",
    "traitName": "Ambitious Initiator",
    "description": "Preference for leadership, persuasion, initiative-taking, business activities, and influencing others."
  },
  {
    "layer": "RIASEC",
    "key": "CONVENTIONAL",
    "trait": "Conventional",
    "traitName": "Systematic & Disciplined",
    "description": "Preference for structured work, planning, organization, accuracy, routines, and systematic processes."
  },
  {
    "layer": "Big FIVE",
    "key": "OPENNESS",
    "trait": "Openness",
    "traitName": "Intellectual Curiosity",
    "description": "Willingness to explore new ideas, experiences, perspectives, creativity, and intellectual curiosity."
  },
  {
    "layer": "Big FIVE",
    "key": "CONSCIENTIOUSNESS",
    "trait": "Conscientiousness",
    "traitName": "Organised Executor",
    "description": "Ability to stay organized, disciplined, responsible, goal-oriented, and focused on completing tasks."
  },
  {
    "layer": "Big FIVE",
    "key": "EXTRAVERSION",
    "trait": "Extraversion",
    "traitName": "Outwardly Engaged",
    "description": "Preference for social interaction, teamwork, communication, energy from people, and active participation."
  },
  {
    "layer": "Big FIVE",
    "key": "AGREEABLENESS",
    "trait": "Agreeableness",
    "traitName": "Harmonious Orientation",
    "description": "Tendency to be cooperative, empathetic, supportive, understanding, and considerate toward others."
  },
  {
    "layer": "Big FIVE",
    "key": "EMOTIONAL_STABILITY",
    "trait": "Emotional Stability",
    "traitName": "Pressure Tolerance",
    "description": "Ability to remain calm, resilient, emotionally balanced, and handle stress effectively."
  },
  {
    "layer": "Aptitude",
    "key": "NUMERICAL",
    "trait": "Numerical Reasoning",
    "traitName": "Computational Thinking",
    "description": "Ability to understand numbers, perform calculations, interpret quantitative information, and solve mathematical problems."
  },
  {
    "layer": "Aptitude",
    "key": "VERBAL",
    "trait": "Verbal Reasoning",
    "traitName": "Textual Intelligence",
    "description": "Ability to understand language, interpret written information, analyze meaning, and communicate effectively."
  },
  {
    "layer": "Aptitude",
    "key": "LOGICAL",
    "trait": "Logical Reasoning",
    "traitName": "Deductive Reasoning",
    "description": "Ability to identify patterns, apply logic, analyze relationships, and solve reasoning-based problems."
  },
  {
    "layer": "Aptitude",
    "key": "SPATIAL",
    "trait": "Spatial Reasoning",
    "traitName": "Visual Thinking",
    "description": "Ability to visualize objects, understand shapes, directions, dimensions, and mentally manipulate spatial information."
  },
  {
    "layer": "Cognitive & Decision",
    "key": "LEARNING_VELOCITY",
    "trait": "Learning Velocity",
    "traitName": "Knowledge Agility",
    "description": "Ability and willingness to learn new skills, adapt quickly, and absorb new concepts efficiently."
  },
  {
    "layer": "Cognitive & Decision",
    "key": "UNCERTAINTY_TOLERANCE",
    "trait": "Uncertainty Tolerance",
    "traitName": "Risk Openness",
    "description": "Comfort level in dealing with ambiguity, change, risk, and situations with uncertain outcomes."
  },
  {
    "layer": "Cognitive & Decision",
    "key": "AUTONOMY_PREFERENCE",
    "trait": "Autonomy Preference",
    "traitName": "Self-Direction Drive",
    "description": "Preference for independent decision-making, self-direction, ownership, and working with minimal supervision."
  }
];
