import { CLARITY_CONFIDENCE_SCALE, EFFECTIVENESS_SCALE, RECOMMEND_SCALE } from "./feedbackScales.js";
import type { FormQuestionSeed } from "../types.js";

// Source: 5_student_feedback_form.html
// Respondent header fields (student name/code, counsellor, date) are not stored as
// FormQuestions — they're derivable from FormSubmission.studentId/submittedAt and the
// student's assigned counsellor, so storing them again would be redundant.
export const feedbackStudentQuestions: FormQuestionSeed[] = [
  {
    order: 1,
    questionCode: "sse_q1",
    fieldKey: "sse_q1",
    sectionLabel: "Section 1 — Session Experience [S-SE]",
    questionText: "The counsellor explained my assessment results in a way I clearly understood.",
    questionType: "SCALE",
    options: EFFECTIVENESS_SCALE,
  },
  {
    order: 2,
    questionCode: "sse_q2",
    fieldKey: "sse_q2",
    sectionLabel: "Section 1 — Session Experience [S-SE]",
    questionText: "I felt comfortable, safe, and genuinely heard throughout the sessions.",
    questionType: "SCALE",
    options: EFFECTIVENESS_SCALE,
  },
  {
    order: 3,
    questionCode: "sse_q3",
    fieldKey: "sse_q3",
    sectionLabel: "Section 1 — Session Experience [S-SE]",
    questionText: "The counsellor asked meaningful questions to understand me as an individual, not just my marks.",
    questionType: "SCALE",
    options: EFFECTIVENESS_SCALE,
  },
  {
    order: 4,
    questionCode: "sse_q4",
    fieldKey: "sse_q4",
    sectionLabel: "Section 1 — Session Experience [S-SE]",
    questionText:
      "The session felt personalised to my specific stream, strengths, and career interests, and not generic.",
    questionType: "SCALE",
    options: EFFECTIVENESS_SCALE,
  },
  {
    order: 5,
    questionCode: "scd_q1",
    fieldKey: "scd_q1",
    sectionLabel: "Section 2 — Clarity & Decision Confidence [S-CD]",
    questionText: "I clearly understand my top 2 career options.",
    questionType: "SCALE",
    options: CLARITY_CONFIDENCE_SCALE,
  },
  {
    order: 6,
    questionCode: "scd_q2",
    fieldKey: "scd_q2",
    sectionLabel: "Section 2 — Clarity & Decision Confidence [S-CD]",
    questionText: "I understand why these career options suit my personality, strengths, and aptitude.",
    questionType: "SCALE",
    options: CLARITY_CONFIDENCE_SCALE,
  },
  {
    order: 7,
    questionCode: "scd_q3",
    fieldKey: "scd_q3",
    sectionLabel: "Section 2 — Clarity & Decision Confidence [S-CD]",
    questionText: "I feel confident about the career direction I am now heading in.",
    questionType: "SCALE",
    options: CLARITY_CONFIDENCE_SCALE,
  },
  {
    order: 8,
    questionCode: "scd_q4",
    fieldKey: "scd_q4",
    sectionLabel: "Section 2 — Clarity & Decision Confidence [S-CD]",
    questionText: "I know the next steps (subjects, exams, colleges).",
    questionType: "SCALE",
    options: CLARITY_CONFIDENCE_SCALE,
  },
  {
    order: 9,
    questionCode: "soq_q1",
    fieldKey: "soq_q1",
    sectionLabel: "Section 3 — Outcome Quality [S-OQ]",
    questionText: "The career options suggested felt relevant to me.",
    questionType: "SCALE",
    options: CLARITY_CONFIDENCE_SCALE,
  },
  {
    order: 10,
    questionCode: "soq_q2",
    fieldKey: "soq_q2",
    sectionLabel: "Section 3 — Outcome Quality [S-OQ]",
    questionText: "The roadmap (Plan A & Plan B) is practical and achievable.",
    questionType: "SCALE",
    options: CLARITY_CONFIDENCE_SCALE,
  },
  {
    order: 11,
    questionCode: "soq_q3",
    fieldKey: "soq_q3",
    sectionLabel: "Section 3 — Outcome Quality [S-OQ]",
    questionText: "My doubts were resolved during the sessions.",
    questionType: "SCALE",
    options: CLARITY_CONFIDENCE_SCALE,
  },
  {
    order: 12,
    questionCode: "sos_q1",
    fieldKey: "sos_q1",
    sectionLabel: "Section 4 — Overall Satisfaction [S-OS]",
    questionText: "This programme reduced my confusion about the future.",
    questionType: "SCALE",
    options: EFFECTIVENESS_SCALE,
  },
  {
    order: 13,
    questionCode: "sos_q2",
    fieldKey: "sos_q2",
    sectionLabel: "Section 4 — Overall Satisfaction [S-OS]",
    questionText: "I would recommend this programme to my friends.",
    questionType: "SCALE",
    options: RECOMMEND_SCALE,
  },
  {
    order: 14,
    questionCode: "open_q1",
    fieldKey: "most_helpful_part",
    sectionLabel: "Section 5 — Open Feedback (Not scored)",
    questionText: "What was the most helpful part?",
    questionType: "OPEN_TEXT",
  },
  {
    order: 15,
    questionCode: "open_q2",
    fieldKey: "could_be_improved",
    sectionLabel: "Section 5 — Open Feedback (Not scored)",
    questionText: "What could be improved?",
    questionType: "OPEN_TEXT",
  },
];
