import { CLARITY_CONFIDENCE_SCALE, EFFECTIVENESS_SCALE, RECOMMEND_SCALE } from "./feedbackScales.js";
import type { FormQuestionSeed } from "../types.js";

// Source: 6_parent_feedback_form.html
// Respondent header fields (parent name, student code, date) are not stored as
// FormQuestions — derivable from FormSubmission relations, same reasoning as the
// student feedback form.
export const feedbackParentQuestions: FormQuestionSeed[] = [
  {
    order: 1,
    questionCode: "ppe_q1",
    fieldKey: "ppe_q1",
    sectionLabel: "Section 1 — Programme Effectiveness [P-PE]",
    questionText: "The assessment results were explained to us clearly and in a way we could understand.",
    questionType: "SCALE",
    options: EFFECTIVENESS_SCALE,
  },
  {
    order: 2,
    questionCode: "ppe_q2",
    fieldKey: "ppe_q2",
    sectionLabel: "Section 1 — Programme Effectiveness [P-PE]",
    questionText: "The career recommendations made were realistic and practical given my child's stream and strengths.",
    questionType: "SCALE",
    options: EFFECTIVENESS_SCALE,
  },
  {
    order: 3,
    questionCode: "ppe_q3",
    fieldKey: "ppe_q3",
    sectionLabel: "Section 1 — Programme Effectiveness [P-PE]",
    questionText: "The career roadmap (Plan A and Plan B) was actionable and clearly laid out.",
    questionType: "SCALE",
    options: EFFECTIVENESS_SCALE,
  },
  {
    order: 4,
    questionCode: "pce_q1",
    fieldKey: "pce_q1",
    sectionLabel: "Section 2 — Counsellor Effectiveness [P-CE]",
    questionText: "The counsellor understood my child's individual strengths, personality, and career interests.",
    questionType: "SCALE",
    options: EFFECTIVENESS_SCALE,
  },
  {
    order: 5,
    questionCode: "pce_q2",
    fieldKey: "pce_q2",
    sectionLabel: "Section 2 — Counsellor Effectiveness [P-CE]",
    questionText: "The counsellor balanced my concerns as a parent with my child's own aspirations effectively.",
    questionType: "SCALE",
    options: EFFECTIVENESS_SCALE,
  },
  {
    order: 6,
    questionCode: "pce_q3",
    fieldKey: "pce_q3",
    sectionLabel: "Section 2 — Counsellor Effectiveness [P-CE]",
    questionText: "The counsellor communicated clearly, confidently, and with subject matter expertise.",
    questionType: "SCALE",
    options: EFFECTIVENESS_SCALE,
  },
  {
    order: 7,
    questionCode: "pce_q4",
    fieldKey: "pce_q4",
    sectionLabel: "Section 2 — Counsellor Effectiveness [P-CE]",
    questionText: "The counsellor built trust and credibility with both me and my child during the sessions.",
    questionType: "SCALE",
    options: EFFECTIVENESS_SCALE,
  },
  {
    order: 8,
    questionCode: "poa_q1",
    fieldKey: "poa_q1",
    sectionLabel: "Section 3 — Outcome & Alignment [P-OA]",
    questionText: "My child now has greater clarity about their career direction within their chosen stream.",
    questionType: "SCALE",
    options: CLARITY_CONFIDENCE_SCALE,
  },
  {
    order: 9,
    questionCode: "poa_q2",
    fieldKey: "poa_q2",
    sectionLabel: "Section 3 — Outcome & Alignment [P-OA]",
    questionText: "The programme helped bring my expectations and my child's aspirations closer together.",
    questionType: "SCALE",
    options: CLARITY_CONFIDENCE_SCALE,
  },
  {
    order: 10,
    questionCode: "poa_q3",
    fieldKey: "poa_q3",
    sectionLabel: "Section 3 — Outcome & Alignment [P-OA]",
    questionText: "My own understanding of my child's strengths, personality, and career options has improved.",
    questionType: "SCALE",
    options: CLARITY_CONFIDENCE_SCALE,
  },
  {
    order: 11,
    questionCode: "pdc_q1",
    fieldKey: "pdc_q1",
    sectionLabel: "Section 4 — Decision Confidence [P-DC]",
    questionText: "I feel confident in the career direction and final choices made for my child.",
    questionType: "SCALE",
    options: CLARITY_CONFIDENCE_SCALE,
  },
  {
    order: 12,
    questionCode: "pdc_q2",
    fieldKey: "pdc_q2",
    sectionLabel: "Section 4 — Decision Confidence [P-DC]",
    questionText: "I believe the career plan and roadmap presented is achievable and appropriate for my child.",
    questionType: "SCALE",
    options: CLARITY_CONFIDENCE_SCALE,
  },
  {
    order: 13,
    questionCode: "prc_q1",
    fieldKey: "prc_q1",
    sectionLabel: "Section 5 — Recommendation [P-RC]",
    questionText: "How likely are you to recommend this programme?",
    questionType: "SCALE",
    options: RECOMMEND_SCALE,
  },
  {
    order: 14,
    questionCode: "open_q1",
    fieldKey: "most_appreciated",
    sectionLabel: "Section 6 — Open Feedback (Not scored)",
    questionText: "What did you appreciate most about this career counselling programme?",
    questionType: "OPEN_TEXT",
  },
  {
    order: 15,
    questionCode: "open_q2",
    fieldKey: "improve_suggestion",
    sectionLabel: "Section 6 — Open Feedback (Not scored)",
    questionText: "What should we improve to make this programme more valuable for parents?",
    questionType: "OPEN_TEXT",
  },
];
