import { STRENGTH_ITEMS } from "../shared/strengthItems.js";
import type { FormQuestionSeed } from "../types.js";

// Source: 2_parent_pre_counselling_form.html — 22 questions, 5 sections.
export const preCounsellingParentQuestions: FormQuestionSeed[] = [
  {
    order: 1,
    questionCode: "Q1",
    fieldKey: "strong_subjects_block",
    sectionLabel: "Section 1 — How I See My Child's Academic Strengths",
    questionText: "Which subjects do you consider your child genuinely strong in?",
    helpText:
      "Strong means they understand it well, perform consistently, or show real interest (not based on scores).",
    questionType: "MATRIX",
    options: {
      fields: [
        { key: "strong_subject_1", label: "Strong Subject 1", type: "SHORT_TEXT" },
        { key: "strong_subject_2", label: "Strong Subject 2", type: "SHORT_TEXT" },
        { key: "strong_subject_3", label: "Strong Subject 3", type: "SHORT_TEXT" },
      ],
    },
  },
  {
    order: 2,
    questionCode: "Q2",
    fieldKey: "struggle_subjects_block",
    sectionLabel: "Section 1 — How I See My Child's Academic Strengths",
    questionText: "Which subjects do you feel your child struggles with the most?",
    questionType: "MATRIX",
    options: {
      fields: [
        { key: "struggle_subject_1", label: "Struggling Subject 1", type: "SHORT_TEXT" },
        { key: "struggle_subject_2", label: "Struggling Subject 2", type: "SHORT_TEXT" },
        { key: "struggle_subject_3", label: "Struggling Subject 3", type: "SHORT_TEXT" },
      ],
    },
  },
  {
    order: 3,
    questionCode: "Q3",
    fieldKey: "p_strengths_table",
    sectionLabel: "Section 2 — Strengths & Interests I Observe In My Child",
    questionText: "Tick what you clearly observe, sometimes notice, or rarely see in your child.",
    questionType: "MATRIX",
    options: {
      rows: STRENGTH_ITEMS,
      fields: [
        {
          key: "rating",
          label: "Rating",
          type: "MCQ_SINGLE",
          options: [
            { value: "clearly", label: "Clearly See This" },
            { value: "sometimes", label: "Sometimes" },
            { value: "rarely", label: "Rarely / Never" },
            { value: "not_sure", label: "Not Sure" },
          ],
        },
      ],
    },
  },
  {
    order: 4,
    questionCode: "Q4",
    fieldKey: "p_free_time_activities",
    sectionLabel: "Section 2 — Strengths & Interests I Observe In My Child",
    questionText: "What does your child enjoy doing most in their free time? (Tick all that apply)",
    questionType: "MCQ_MULTI",
    allowOtherText: true,
    otherTextFieldKey: "p_free_time_activities_other",
    options: [
      { value: "a", label: "Sports or physical activities" },
      { value: "b", label: "Gaming — mobile, PC or console" },
      { value: "c", label: "Creative hobbies — drawing, music, writing, crafts" },
      { value: "d", label: "Socialising with friends or on social media" },
      { value: "e", label: "Skill-building — coding, video editing, public speaking" },
      { value: "f", label: "Reading — books, articles, news" },
      { value: "g", label: "Any Other", isOtherOption: true },
      { value: "h", label: "Not Sure" },
    ],
  },
  {
    order: 5,
    questionCode: "Q5",
    fieldKey: "unique_talent",
    sectionLabel: "Section 2 — Strengths & Interests I Observe In My Child",
    questionText: "Have you noticed any one special talent or unique ability in your child?",
    questionType: "OPEN_TEXT",
  },
  {
    order: 6,
    questionCode: "Q6",
    fieldKey: "p_interest_consistency",
    sectionLabel: "Section 2 — Strengths & Interests I Observe In My Child",
    questionText: "How consistent are your child's interests over time?",
    questionType: "MCQ_SINGLE",
    options: [
      { value: "a", label: "Very consistent — same interests have continued for a long time" },
      { value: "b", label: "Mostly consistent — with some natural variation" },
      { value: "c", label: "Frequently changing — new interests appear often and old ones fade" },
      { value: "d", label: "Not Sure" },
    ],
  },
  {
    order: 7,
    questionCode: "Q7",
    fieldKey: "child_personality",
    sectionLabel: "Section 3 — My Child's Personality",
    questionText: "Which of these best describes your child's general personality? (Choose ONE)",
    questionType: "MCQ_SINGLE",
    options: [
      { value: "a", label: "Confident and a natural leader — takes charge in situations" },
      { value: "b", label: "Reserved and reflective — prefers to observe before acting" },
      { value: "c", label: "Social and outgoing — energised by people and interactions" },
      { value: "d", label: "Independent — prefers working alone and self-directed" },
      { value: "e", label: "Practical and hands-on — prefers doing over discussing" },
      { value: "f", label: "Creative and imaginative — always thinking of new things" },
      { value: "g", label: "Not Sure" },
    ],
  },
  {
    order: 8,
    questionCode: "Q8",
    fieldKey: "child_interaction_style",
    sectionLabel: "Section 3 — My Child's Personality",
    questionText: "How does your child generally interact with others — friends, classmates, teachers?",
    questionType: "MCQ_SINGLE",
    allowOtherText: true,
    otherTextFieldKey: "child_interaction_style_other",
    options: [
      { value: "a", label: "Collaborative and friendly — gets along with most people easily" },
      { value: "b", label: "Reserved or formal — keeps appropriate distance with teachers and seniors" },
      { value: "c", label: "Easily influenced by peer pressure — tends to follow the group" },
      { value: "d", label: "More confident online than in person" },
      { value: "e", label: "Any Other", isOtherOption: true },
      { value: "f", label: "Not Sure" },
    ],
  },
  {
    order: 9,
    questionCode: "Q9",
    fieldKey: "child_decision_style",
    sectionLabel: "Section 3 — My Child's Personality",
    questionText: "How does your child typically make important decisions?",
    questionType: "MCQ_SINGLE",
    allowOtherText: true,
    otherTextFieldKey: "child_decision_style_other",
    options: [
      { value: "a", label: "Thinks carefully about pros and cons before deciding" },
      { value: "b", label: "Goes with what feels right and is practical" },
      { value: "c", label: "Seeks guidance from a trusted person" },
      { value: "d", label: "Thinks about long-term consequences" },
      { value: "e", label: "Just tries it out and learns from what happens" },
      { value: "f", label: "Any Other", isOtherOption: true },
      { value: "g", label: "Not Sure" },
    ],
  },
  {
    order: 10,
    questionCode: "Q10",
    fieldKey: "child_failure_response",
    sectionLabel: "Section 3 — My Child's Personality",
    questionText: "How does your child usually handle failure or critical feedback?",
    questionType: "MCQ_SINGLE",
    allowOtherText: true,
    otherTextFieldKey: "child_failure_response_other",
    options: [
      { value: "a", label: "Gives justifications or reasons — deflects responsibility" },
      { value: "b", label: "Becomes visibly demotivated or loses confidence for some time" },
      { value: "c", label: "Brushes it off and moves on without reflecting" },
      { value: "d", label: "Compares with others — becomes competitive or envious" },
      { value: "e", label: "Accepts it, reflects, and genuinely tries to improve" },
      { value: "f", label: "Any Other", isOtherOption: true },
      { value: "g", label: "Not Sure" },
    ],
  },
  {
    order: 11,
    questionCode: "Q11",
    fieldKey: "child_study_obstacle",
    sectionLabel: "Section 3 — My Child's Personality",
    questionText: "What is the biggest obstacle your child faces in studying or performing academically?",
    questionType: "MCQ_SINGLE",
    allowOtherText: true,
    otherTextFieldKey: "child_study_obstacle_other",
    options: [
      { value: "a", label: "Distraction — phone, TV, other activities pull attention away" },
      { value: "b", label: "No clear study strategy or method" },
      { value: "c", label: "Exam anxiety or fear of failure" },
      { value: "d", label: "Pressure from peers or from us as parents" },
      { value: "e", label: "Procrastination — putting off studying" },
      { value: "f", label: "Difficulty understanding concepts — relies on memorisation" },
      { value: "g", label: "Any Other", isOtherOption: true },
      { value: "h", label: "Not Sure" },
    ],
  },
  {
    order: 12,
    questionCode: "Q12",
    fieldKey: "preferred_career",
    sectionLabel: "Section 4 — Career Direction & Expectations",
    questionText:
      "Do you currently have a preferred career path or stream in mind for your child? If yes, please write it.",
    questionType: "OPEN_TEXT",
  },
  {
    order: 13,
    questionCode: "Q13",
    fieldKey: "career_pref_reason",
    sectionLabel: "Section 4 — Career Direction & Expectations",
    questionText: "If you have a preference, what is the main reason behind it? (Choose ONE)",
    questionType: "MCQ_SINGLE",
    allowOtherText: true,
    otherTextFieldKey: "career_pref_reason_other",
    options: [
      { value: "a", label: "I believe my child is genuinely passionate about this field" },
      { value: "b", label: "It offers strong earning potential" },
      { value: "c", label: "It is a stable and respected career path" },
      { value: "d", label: "It brings recognition or social prestige" },
      { value: "e", label: "It offers independence and flexibility in work" },
      { value: "f", label: "It allows my child to contribute to society" },
      { value: "g", label: "Any Other", isOtherOption: true },
      { value: "h", label: 'I have no specific preference — my answer to Q12 was "Nil"' },
    ],
  },
  {
    order: 14,
    questionCode: "Q14",
    fieldKey: "open_to_unconventional",
    sectionLabel: "Section 4 — Career Direction & Expectations",
    questionText:
      "Are you open to your child exploring unconventional or emerging careers if the assessment strongly suggests suitability?",
    helpText: "Examples: UX design, environmental science, data analytics, sports psychology, content creation, etc.",
    questionType: "MCQ_SINGLE",
    options: [
      { value: "a", label: "Yes — I am open to whatever the counsellor recommends" },
      { value: "b", label: "Open but with reservations — I would want to understand it fully first" },
      { value: "c", label: "No — I have a clear plan and prefer to stick to it" },
    ],
  },
  {
    order: 15,
    questionCode: "Q15",
    fieldKey: "financial_constraints",
    sectionLabel: "Section 4 — Career Direction & Expectations",
    questionText:
      "Are there financial or practical constraints that should be considered in planning your child's education?",
    questionType: "MCQ_SINGLE",
    options: [
      { value: "a", label: "No significant constraints — we are open to most options" },
      { value: "b", label: "Moderate constraints — we prefer affordable domestic options" },
      { value: "c", label: "Significant constraints — budget is a key decision factor" },
    ],
  },
  {
    order: 16,
    questionCode: "Q16",
    fieldKey: "study_away_table",
    sectionLabel: "Section 4 — Career Direction & Expectations",
    questionText: "How open are you to your child studying away from home for their higher education?",
    questionType: "MATRIX",
    options: {
      rows: [
        { key: "another_city", label: "Studying in another city (within India)" },
        { key: "abroad", label: "Studying abroad (international)" },
      ],
      fields: [
        {
          key: "openness",
          label: "Openness",
          type: "MCQ_SINGLE",
          options: [
            { value: "open", label: "Open to it" },
            { value: "not_open", label: "Not Open" },
          ],
        },
      ],
    },
  },
  {
    order: 17,
    questionCode: "Q17",
    fieldKey: "final_decision_maker",
    sectionLabel: "Section 4 — Career Direction & Expectations",
    questionText: "Who usually makes the final decisions about your child's education and future?",
    questionType: "MCQ_SINGLE",
    options: [
      { value: "a", label: "Primarily us as parents" },
      { value: "b", label: "Primarily my child" },
      { value: "c", label: "We decide together as a family" },
    ],
  },
  {
    order: 18,
    questionCode: "Q18",
    fieldKey: "child_involvement",
    sectionLabel: "Section 4 — Career Direction & Expectations",
    questionText: "How actively is your child involved in these major education decisions?",
    questionType: "MCQ_SINGLE",
    options: [
      { value: "a", label: "Always — every major decision is discussed with them" },
      { value: "b", label: "Sometimes — for some decisions" },
      { value: "c", label: "Rarely — we prefer to decide on their behalf" },
    ],
  },
  {
    order: 19,
    questionCode: "Q19",
    fieldKey: "biggest_concern",
    sectionLabel: "Section 4 — Career Direction & Expectations",
    questionText: "What is your biggest concern about your child's academic and career future? (Tick all that apply)",
    questionType: "MCQ_MULTI",
    allowOtherText: true,
    otherTextFieldKey: "biggest_concern_other",
    options: [
      { value: "a", label: "My child is confused about what to do" },
      { value: "b", label: "Academic performance is below expectations" },
      { value: "c", label: "My child lacks focus and direction" },
      { value: "d", label: "Peer pressure is a negative influence" },
      { value: "e", label: "I am worried they will make a wrong career choice" },
      { value: "f", label: "Any Other", isOtherOption: true },
    ],
  },
  {
    order: 20,
    questionCode: "Q20",
    fieldKey: "specific_concern_counsellor",
    sectionLabel: "Section 4 — Career Direction & Expectations",
    questionText:
      "Is there any specific concern — academic, behavioural or emotional — you would like the counsellor to address in the session?",
    questionType: "OPEN_TEXT",
  },
  {
    order: 21,
    questionCode: "Q21",
    fieldKey: "programme_hopes",
    sectionLabel: "Section 5 — What You Expect From This Programme",
    questionText: "What are you hoping your child will gain from this counselling programme? (Tick all that apply)",
    questionType: "MCQ_MULTI",
    allowOtherText: true,
    otherTextFieldKey: "programme_hopes_other",
    options: [
      { value: "a", label: "Clarity on which stream to choose (Science / Commerce / Humanities)" },
      { value: "b", label: "A clear career direction with a roadmap" },
      { value: "c", label: "More confidence in themselves and their choices" },
      { value: "d", label: "Better self-awareness — understanding their own personality and strengths" },
      { value: "e", label: "Alignment between what my child wants and what we as parents expect" },
      { value: "f", label: "Any Other", isOtherOption: true },
    ],
  },
  {
    order: 22,
    questionCode: "Q22",
    fieldKey: "family_context",
    sectionLabel: "Section 5 — What You Expect From This Programme",
    questionText:
      "Is there anything you want to personally share with the counsellor — family context, background, or anything relevant?",
    questionType: "OPEN_TEXT",
  },
];
