import { STRENGTH_ITEMS } from "../shared/strengthItems.js";
import type { FormQuestionSeed } from "../types.js";

// Source: 1_student_pre_counselling_form.html — 19 questions, 6 sections.
export const preCounsellingStudentQuestions: FormQuestionSeed[] = [
  {
    order: 1,
    questionCode: "Q1",
    fieldKey: "academic_record_table",
    sectionLabel: "Section 1 — My Academic Record",
    questionText: "Fill in your marks or grade for the last three years.",
    helpText: "This is not to evaluate you based on marks, but to know what you may like or dislike.",
    questionType: "MATRIX",
    options: {
      rows: [
        { key: "english", label: "English" },
        { key: "secondlang", label: "Second Language" },
        { key: "science", label: "Science" },
        { key: "maths", label: "Mathematics" },
        { key: "socsci", label: "Social Science" },
        { key: "cs", label: "Computer Science" },
        { key: "other", label: "Other subject", labelEditable: true },
      ],
      fields: [
        { key: "c7", label: "Class 7", type: "SHORT_TEXT" },
        { key: "c8", label: "Class 8", type: "SHORT_TEXT" },
        { key: "c9", label: "Class 9", type: "SHORT_TEXT" },
      ],
    },
  },
  {
    order: 2,
    questionCode: "Q2",
    fieldKey: "fav_subject_block",
    sectionLabel: "Section 1 — My Academic Record",
    questionText: "Pick the ONE subject you enjoy the most and tell us WHY you enjoy it.",
    helpText: "Think about what subject makes time feel like it's flying by — not just what you score well in.",
    questionType: "MATRIX",
    options: {
      fields: [
        { key: "fav_subject", label: "My favourite subject", type: "SHORT_TEXT" },
        {
          key: "fav_subject_reason",
          label: "I enjoy it because",
          type: "MCQ_SINGLE",
          allowOtherText: true,
          otherTextFieldKey: "fav_subject_reason_other",
          options: [
            { value: "a", label: "I love solving problems and puzzles in this subject" },
            { value: "b", label: "It allows me to be creative and come up with new ideas" },
            { value: "c", label: "It connects to real life — I can see how it is actually used" },
            { value: "d", label: "It just feels easy and natural to me — I simply enjoy it" },
            { value: "e", label: "Any Other Reason", isOtherOption: true },
          ],
        },
      ],
    },
  },
  {
    order: 3,
    questionCode: "Q3",
    fieldKey: "hard_subject_block",
    sectionLabel: "Section 1 — My Academic Record",
    questionText: "Pick the ONE subject you find most difficult and tell us WHY.",
    helpText: "Difficulty does not mean you are bad at it — it just means you enjoy it the least.",
    questionType: "MATRIX",
    options: {
      fields: [
        { key: "hard_subject", label: "My hardest subject", type: "SHORT_TEXT" },
        {
          key: "hard_subject_reason",
          label: "It is difficult because",
          type: "MCQ_SINGLE",
          allowOtherText: true,
          otherTextFieldKey: "hard_subject_reason_other",
          options: [
            { value: "a", label: "I don't understand the concepts — it feels like just memorising" },
            { value: "b", label: "I get anxious during exams or tests for this subject" },
            { value: "c", label: "The way it is taught is too theoretical and boring" },
            { value: "d", label: "I am simply not interested in this topic" },
            { value: "e", label: "Any Other Reason", isOtherOption: true },
          ],
        },
      ],
    },
  },
  {
    order: 4,
    questionCode: "Q4",
    fieldKey: "free_time_activities",
    sectionLabel: "Section 2 — How I Spend My Time",
    questionText: "What do you do most in your free time when you are NOT studying? (Tick all that apply)",
    helpText:
      "Free time includes evenings, weekends, school holidays, any time that is not class or homework time.",
    questionType: "MCQ_MULTI",
    allowOtherText: true,
    otherTextFieldKey: "free_time_activities_other",
    options: [
      { value: "sports", label: "Sports or physical activities (cricket, football, gym, dance, etc.)" },
      { value: "gaming", label: "Gaming — mobile, PC or console" },
      { value: "creative_hobbies", label: "Creative hobbies — drawing, painting, music, writing, etc." },
      { value: "socialising", label: "Socialising — meeting friends or social media" },
      { value: "skill_building", label: "Skill-building — coding, video editing, public speaking, etc." },
      { value: "reading", label: "Reading — books, articles, news, comics" },
      { value: "other", label: "Other", isOtherOption: true },
    ],
  },
  {
    order: 5,
    questionCode: "Q5",
    fieldKey: "hobbies_table",
    sectionLabel: "Section 2 — How I Spend My Time",
    questionText: "Write your top two hobbies and how many hours per week you spend on them.",
    helpText: "Even casual things like watching YouTube or playing with pets count as hobbies.",
    questionType: "MATRIX",
    options: {
      rows: [
        { key: "hobby_1", label: "1" },
        { key: "hobby_2", label: "2" },
      ],
      fields: [
        { key: "name", label: "My Hobby", type: "SHORT_TEXT" },
        { key: "hours", label: "Hours per Week", type: "NUMBER" },
      ],
    },
  },
  {
    order: 6,
    questionCode: "Q6",
    fieldKey: "interest_consistency",
    sectionLabel: "Section 2 — How I Spend My Time",
    questionText: "How consistent are your interests / hobbies over time?",
    helpText: "Even casual things like watching YouTube or playing with pets count as interests / hobbies.",
    questionType: "MCQ_SINGLE",
    options: [
      { value: "a", label: "Very consistent — same interests have continued for a long time" },
      { value: "b", label: "Mostly consistent — mostly interested but at times bored" },
      { value: "c", label: "Frequently changing — new interests appear often, old ones fade" },
    ],
  },
  {
    order: 7,
    questionCode: "Q7",
    fieldKey: "school_activities",
    sectionLabel: "Section 2 — How I Spend My Time",
    questionText: "Which school activities do you enjoy the most? (Tick all that apply)",
    helpText: "These are activities that are not part of your routine academics or studies.",
    questionType: "MCQ_MULTI",
    allowOtherText: true,
    otherTextFieldKey: "school_activities_other",
    options: [
      { value: "assembly", label: "Morning assembly — speeches, prayer, thought for the day" },
      { value: "sports_pe", label: "Sports and physical education periods" },
      { value: "art_music", label: "Art, music and creative periods" },
      { value: "clubs", label: "Club activities — science club, quiz club, coding club, eco club, etc." },
      { value: "competitions", label: "Competitions — debates, elocutions, quizzes, house events" },
      { value: "field_trips", label: "Field trips — company visits, factory visits, nature outings" },
      { value: "other", label: "Any Other", isOtherOption: true },
    ],
  },
  {
    order: 8,
    questionCode: "Q8",
    fieldKey: "learning_style",
    sectionLabel: "Section 2 — How I Spend My Time",
    questionText: "How do you learn best? Choose the ONE option that feels most like you.",
    helpText: "Think about which way of studying actually makes things stick in your mind and you get interested.",
    questionType: "MCQ_SINGLE",
    options: [
      { value: "a", label: "Reading and understanding concepts from books or notes" },
      { value: "b", label: "Doing experiments, projects or hands-on activities" },
      { value: "c", label: "Drawing, designing or expressing ideas through creative work" },
      { value: "d", label: "Solving exercises, case studies and working through problems" },
      { value: "e", label: "Watching videos, listening to podcasts or visual content" },
    ],
  },
  {
    order: 9,
    questionCode: "Q9",
    fieldKey: "strengths_table",
    sectionLabel: "Section 3 — What I Am Good At (My Strengths)",
    questionText:
      "For each strength below, tick whether it is a strong area for you, something average, or not really your strength.",
    helpText: "A strength is something you do noticeably well compared to others — and does not feel like hard work.",
    questionType: "MATRIX",
    options: {
      rows: STRENGTH_ITEMS,
      fields: [
        {
          key: "rating",
          label: "Rating",
          type: "MCQ_SINGLE",
          options: [
            { value: "definitely", label: "Definitely Me" },
            { value: "somewhat", label: "Somewhat Me" },
            { value: "not_really", label: "Not Really Me" },
          ],
        },
      ],
    },
  },
  {
    order: 10,
    questionCode: "Q10",
    fieldKey: "study_challenges",
    sectionLabel: "Section 3 — What I Am Good At (My Strengths)",
    questionText: "What is your biggest challenge when studying? (Choose up to TWO)",
    helpText: "Being honest here helps your counsellor give you practical tips.",
    questionType: "MCQ_MULTI",
    allowOtherText: true,
    otherTextFieldKey: "study_challenges_other",
    options: [
      { value: "a", label: "Too many distractions — phone, TV, noise" },
      { value: "b", label: "I don't have a good study method or plan" },
      { value: "c", label: "I get very anxious before exams or fear of failing" },
      { value: "d", label: "Pressure from parents or peers makes it stressful" },
      { value: "e", label: "I keep postponing studying — procrastination" },
      { value: "f", label: "Concepts are hard to understand — feels like memorising" },
      { value: "g", label: "Any Other", isOtherOption: true },
    ],
  },
  {
    order: 11,
    questionCode: "Q11",
    fieldKey: "energy_type",
    sectionLabel: "Section 4 — My Personality & How I Think",
    questionText: "Which of these best describes you? (Choose ONE)",
    helpText:
      "There is no better or worse option, this just helps us understand how you get your energy or how you think you are.",
    questionType: "MCQ_SINGLE",
    options: [
      { value: "a", label: "Introvert — I prefer working alone and feel recharged after time by myself" },
      { value: "b", label: "Extrovert — I love being around people and feel energised in groups" },
      { value: "c", label: "Ambivert — I am a mix of both depending on the situation" },
    ],
  },
  {
    order: 12,
    questionCode: "Q12",
    fieldKey: "decision_style",
    sectionLabel: "Section 4 — My Personality & How I Think",
    questionText: "How do you usually make an important decision? (Choose ONE)",
    helpText: "Example: Deciding which book to read, which tuition/course to take, which activity to join.",
    questionType: "MCQ_SINGLE",
    allowOtherText: true,
    otherTextFieldKey: "decision_style_other",
    options: [
      { value: "a", label: "I list out the pros and cons and weigh them carefully" },
      { value: "b", label: "I go with what feels right and is also practical" },
      { value: "c", label: "I ask someone I trust — a parent, teacher or friend" },
      { value: "d", label: "I think about how this choice will affect my future" },
      { value: "e", label: "I just try it and see what happens — I learn by doing" },
      { value: "f", label: "Any Other", isOtherOption: true },
    ],
  },
  {
    order: 13,
    questionCode: "Q13",
    fieldKey: "failure_response",
    sectionLabel: "Section 4 — My Personality & How I Think",
    questionText: "When you fail at something or get negative feedback, what do you usually do? (Choose ONE)",
    helpText: "Think of the last time you got a bad mark, lost a competition or were told you did something wrong.",
    questionType: "MCQ_SINGLE",
    allowOtherText: true,
    otherTextFieldKey: "failure_response_other",
    options: [
      { value: "a", label: "I explain or justify why it happened" },
      { value: "b", label: "I lose confidence and feel demotivated for a while" },
      { value: "c", label: "I ignore the feedback and move on" },
      { value: "d", label: "I compare myself with others and feel bad" },
      { value: "e", label: "I accept it, think about what went wrong and try to improve" },
      { value: "f", label: "Any Other", isOtherOption: true },
    ],
  },
  {
    order: 14,
    questionCode: "Q14",
    fieldKey: "career_in_mind",
    sectionLabel: "Section 5 — My Career Thoughts",
    questionText: 'Do you have a specific career/s in mind? If yes, write it. If no, write "Still Exploring".',
    helpText:
      "It is perfectly fine if you are not sure about your career, most students at your age are not! Just answer honestly with what you think right now. Even if you're not sure, write what comes to mind or you might have thought of.",
    questionType: "OPEN_TEXT",
  },
  {
    order: 15,
    questionCode: "Q15",
    fieldKey: "career_interest_reason",
    sectionLabel: "Section 5 — My Career Thoughts",
    questionText:
      'Why are you interested in that career/s? (Choose ONE, or select "Not Applicable" if Q14 was "Still Exploring")',
    helpText:
      "If you have mentioned some career in the previous question, there would be something that you like about it. Just mention that.",
    questionType: "MCQ_SINGLE",
    allowOtherText: true,
    otherTextFieldKey: "career_interest_reason_other",
    options: [
      { value: "a", label: "I genuinely love and am passionate about this field" },
      { value: "b", label: "It pays well — I want financial security" },
      { value: "c", label: "It is a safe, stable and respected career" },
      { value: "d", label: "I want recognition or fame in this field" },
      { value: "e", label: "It gives me freedom and flexibility in how I work" },
      { value: "f", label: "I want to help people or make a difference in society" },
      { value: "g", label: "Any Other", isOtherOption: true },
      { value: "h", label: "Not Applicable" },
    ],
  },
  {
    order: 16,
    questionCode: "Q16",
    fieldKey: "career_influence",
    sectionLabel: "Section 5 — My Career Thoughts",
    questionText: "Who or what has most influenced your thinking about your career? (Choose ONE)",
    helpText: "It is perfectly fine if you are told about the career. We just want to know who or what shaped your thinking.",
    questionType: "MCQ_SINGLE",
    allowOtherText: true,
    otherTextFieldKey: "career_influence_other",
    options: [
      { value: "a", label: "My parent(s)" },
      { value: "b", label: "A teacher or mentor" },
      { value: "c", label: "Friends or classmates" },
      { value: "d", label: "A relative or family friend" },
      { value: "e", label: "A book, movie or documentary I watched" },
      { value: "f", label: "Social media or the internet" },
      { value: "g", label: "My own thinking and self-discovery" },
      { value: "h", label: "Any Other", isOtherOption: true },
    ],
  },
  {
    order: 17,
    questionCode: "Q17",
    fieldKey: "parent_understanding",
    sectionLabel: "Section 5 — My Career Thoughts",
    questionText: "How well do your parents understand what you want to do after school? (Choose ONE)",
    helpText: "It can be about your career plans or stream selection.",
    questionType: "MCQ_SINGLE",
    options: [
      { value: "a", label: "Very well — they fully understand and support my direction" },
      { value: "b", label: "Fairly well — they get it but have some concerns or doubts" },
      { value: "c", label: "Partially — they know what I like but push me towards something else" },
      { value: "d", label: "Not well — there is a big gap between what I want and what they expect" },
      { value: "e", label: "We have not really discussed it yet" },
    ],
  },
  {
    order: 18,
    questionCode: "Q18",
    fieldKey: "programme_expectations",
    sectionLabel: "Section 6 — What I Want From This Programme",
    questionText: "What are you hoping to get from this career counselling programme? (Tick all that apply)",
    helpText:
      "Look at this as a conversation with your best friend and hence choose an answer so that the discussion is meaningful.",
    questionType: "MCQ_MULTI",
    allowOtherText: true,
    otherTextFieldKey: "programme_expectations_other",
    options: [
      { value: "a", label: "Help in choosing the right stream (Science / Commerce / Humanities)" },
      { value: "b", label: "Clarity on what career to aim for and a roadmap to get there" },
      { value: "c", label: "More confidence in myself and my choices" },
      { value: "d", label: "A better understanding of my own personality and strengths" },
      { value: "e", label: "Any Other", isOtherOption: true },
    ],
  },
  {
    order: 19,
    questionCode: "Q19",
    fieldKey: "notes_for_counsellor",
    sectionLabel: "Section 6 — What I Want From This Programme",
    questionText: "Is there anything specific you want your counsellor to know before your session? (optional)",
    helpText:
      "This could be a worry, a dream, a difficulty, or something about your situation at home or school. Confidential.",
    questionType: "OPEN_TEXT",
    isRequired: false,
  },
];
