import { z } from "zod";
import { emailSchema, phoneSchema } from "../../common/validators/shared.js";
import { createStudentSchema } from "../students/students.schema.js";
import { dateSchema, timeSchema } from "../sessions/sessions.schema.js";

// Writable statuses (create/update). DELETED is set/cleared only via the DELETE + restore
// endpoints, never by an arbitrary PATCH, so it's intentionally excluded here.
export const projectStatusSchema = z.enum(["ACTIVE", "CLOSED"]);

// Filter statuses for listing — includes DELETED so the UI can list soft-deleted projects.
export const projectStatusFilterSchema = z.enum(["ACTIVE", "CLOSED", "DELETED"]);

export const createProjectSchema = z
  .object({
    // Admin-supplied human-readable id (e.g. "P0001"). Required — no longer generated by
    // the service.
    code: z.string().trim().min(1),
    name: z.string().trim().min(1),
    // A Project is the institute — these carry what the old standalone Institute model
    // held (name/address/contact). Address is optional; stored as "" when omitted (column
    // is NOT NULL).
    address: z.string().trim().min(1).optional(),
    contactNumber: phoneSchema,
    primaryEmail: emailSchema,
    fromDate: z.coerce.date(),
    toDate: z.coerce.date(),
    status: projectStatusSchema.optional(),
    // Delivery language. Optional for now — omitting it defaults to English (the seeded
    // default). Wired ahead of the UI that will let admins pick another language.
    languageId: z.string().cuid().optional(),
  })
  .refine((d) => d.fromDate <= d.toDate, {
    message: "fromDate must be on or before toDate",
    path: ["toDate"],
  });
export type CreateProjectInput = z.infer<typeof createProjectSchema>;

// Date order is validated in the service (needs the merge with the existing row when only
// one of the two dates is supplied), not here.
export const updateProjectSchema = z.object({
  name: z.string().trim().min(1).optional(),
  address: z.string().trim().min(1).optional(),
  contactNumber: phoneSchema.optional(),
  primaryEmail: emailSchema.optional(),
  fromDate: z.coerce.date().optional(),
  toDate: z.coerce.date().optional(),
  status: projectStatusSchema.optional(),
  languageId: z.string().cuid().optional(),
});
export type UpdateProjectInput = z.infer<typeof updateProjectSchema>;

export const projectIdParamsSchema = z.object({
  id: z.string().cuid(),
});

export const listProjectsQuerySchema = z.object({
  // No status → active + closed (excludes DELETED). `status=DELETED` lists only soft-deleted.
  status: projectStatusFilterSchema.optional(),
});
export type ListProjectsQuery = z.infer<typeof listProjectsQuerySchema>;

// --- Combined wizard (one atomic "Finish" call for the create-project UI) ---
//
// A single admin action that creates the project, onboards its student roster, and
// imports its counsellor-availability sheet in one transaction — all-or-nothing, so a
// failure partway through (a bad row, a duplicate email) never leaves a half-onboarded
// project behind. Each piece mirrors the shape of its own standalone endpoint:
//   - `project` is exactly the POST /projects body.
//   - `students[]` is the POST /students body minus `projectId` (implied by the project
//     being created alongside it).
//   - `counsellorSlots[]` is one row per bookable slot, keyed by `counsellorCode` (not a
//     Prisma id — the sheet doesn't know ids yet). Rows sharing a `counsellorCode` are the
//     same counsellor's slots. If that code already exists (`Counsellor.counsellorCode`),
//     the existing counsellor is reused and assigned to this project; if it doesn't,
//     `firstName`/`lastName`/`email`/`mobile` must be given (on at least one row for that
//     code) so a new Counsellor + User can be created inline.

export const wizardCounsellorSlotSchema = z.object({
  // Matches an existing Counsellor.counsellorCode, or names a brand-new one to create.
  counsellorCode: z.string().trim().min(1),
  // Required only for a counsellorCode that doesn't already exist — validated in the
  // service (Zod can't see across array rows to know which case applies).
  firstName: z.string().trim().min(1).optional(),
  lastName: z.string().trim().min(1).optional(),
  email: emailSchema.optional(),
  mobile: phoneSchema.optional(),
  meetingLink: z.string().trim().url().optional(),
  date: dateSchema,
  startTime: timeSchema,
  endTime: timeSchema,
});
export type WizardCounsellorSlot = z.infer<typeof wizardCounsellorSlotSchema>;

export const createProjectWizardSchema = z.object({
  project: createProjectSchema,
  students: z.array(createStudentSchema.omit({ projectId: true })).default([]),
  counsellorSlots: z.array(wizardCounsellorSlotSchema).default([]),
});
export type CreateProjectWizardInput = z.infer<typeof createProjectWizardSchema>;
