import { z } from "zod";

// Writable statuses (create/update). DELETED is set/cleared only via the DELETE + restore
// endpoints, never by an arbitrary PATCH, so it's intentionally excluded here.
export const projectStatusSchema = z.enum(["ACTIVE", "CLOSED"]);

// Filter statuses for listing — includes DELETED so the UI can list soft-deleted projects.
export const projectStatusFilterSchema = z.enum(["ACTIVE", "CLOSED", "DELETED"]);

export const createProjectSchema = z
  .object({
    instituteId: z.string().cuid(),
    // Admin-supplied human-readable id (e.g. "P0001"). Required — no longer generated by
    // the service.
    code: z.string().trim().min(1),
    name: z.string().trim().min(1),
    fromDate: z.coerce.date(),
    toDate: z.coerce.date(),
    status: projectStatusSchema.optional(),
    // Delivery language. Optional for now — omitting it defaults to English (the seeded
    // default). Wired ahead of the UI that will let admins pick another language.
    languageId: z.string().cuid().optional(),
  })
  .refine((d) => d.fromDate <= d.toDate, {
    message: "fromDate must be on or before toDate",
    path: ["toDate"],
  });
export type CreateProjectInput = z.infer<typeof createProjectSchema>;

// Date order is validated in the service (needs the merge with the existing row when only
// one of the two dates is supplied), not here.
export const updateProjectSchema = z.object({
  name: z.string().trim().min(1).optional(),
  fromDate: z.coerce.date().optional(),
  toDate: z.coerce.date().optional(),
  status: projectStatusSchema.optional(),
  languageId: z.string().cuid().optional(),
});
export type UpdateProjectInput = z.infer<typeof updateProjectSchema>;

export const projectIdParamsSchema = z.object({
  id: z.string().cuid(),
});

export const listProjectsQuerySchema = z.object({
  instituteId: z.string().cuid().optional(),
  // No status → active + closed (excludes DELETED). `status=DELETED` lists only soft-deleted.
  status: projectStatusFilterSchema.optional(),
});
export type ListProjectsQuery = z.infer<typeof listProjectsQuerySchema>;
